### ISSUE TITLE
Modern Village Map

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#143]

**Comment by RDR12313** [comment]
How's it going?

**Comment by PiweeX** [comment]
Builder Fqzoon


build finished 5 days early

![2022-09-07_17 29 43](https://user-images.githubusercontent.com/33425430/188919357-6ddadec6-70b4-448b-adfa-0b93a26d68d2.png)

![2022-09-07_17 29 36](https://user-images.githubusercontent.com/33425430/188919364-cd063e1b-6a48-43c8-b05f-eed6d08edcf8.png)

![2022-09-07_17 29 48](https://user-images.githubusercontent.com/33425430/188919350-9128ce7e-3df1-4ab8-b574-5b72b51de5e1.png)

![2022-09-07_17 29 23](https://user-images.githubusercontent.com/33425430/188919347-fed4b56c-ba12-454b-9873-a1aaa1c7d6cd.png)
