### ISSUE TITLE
Build It Application Tutorials [#1 platform for builds)

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#144]
Long-term cooperation with BuildIt a build app that will be the largest build platform in the world in the future

keep this documented, the app currently has 256 builds, our mission is to build thousands and we will succeed.

![download](https://user-images.githubusercontent.com/33425430/189532524-e7f13b64-bdfc-418b-8c34-58af6f10bc61.png)

our team will build 45 builds of 1000 blocks per week, which is 180 builds per month, we have about 1000 to 1400 builds to build in the next couple of months, and production may only increase to more weekly builds

**the build takes place on our buildstorage1 server on the 1.19.2 version of JAVA minecraft**

Here is more information about the job:

> You build in the flat world on /server buildstorage1 on hogostudios.com, when you build, you demolish part by part and take screenshots at the same time so that afterwards you can reverse the images as if it were being built
> 
> It is important to use the 8 min invisibility potion in order not to see the shadow, before taking a screenshot, make sure that the FOV is at 30% and that everything around the build cyan_terracotta is fixed Terracotta (remove it), if you can see the sky or some empty pieces, you should remove it in photoshop, the superflat must not have any `/time set 8000” or “/time set 4000” mobs in order for the light to be placed on the other side of the build
> 
> After you're done with the screenshots, you go to the screenshots folder they're in, sort the images by date, then rename the file in the correct order with 1, 2, 3, 4, etc. The last image for the last screenshot you make should be 1, the one before that 2, etc.
> 
> An example of how it should be, let's say this: https://builditapp.com/grand-spruce-manor-page-11/ it's good to have as big builds as possible, because the bigger the build, the bigger the profit, it all depends on how many blocks there are and how much There are blocks, you can see them via //distr (you just need to remove the air blocks before the final number)

https://user-images.githubusercontent.com/33425430/189532734-6a06b3a0-1ddc-4892-9739-da1500b5027b.mp4

**Comment by TheFrontView** [comment]
![2022-09-15_16 35 19](https://user-images.githubusercontent.com/71612070/190479637-d64446bd-df56-4ec0-a0f8-002e985f06f7.png)
![2022-09-15_16 41 00](https://user-images.githubusercontent.com/71612070/190479645-ab73589d-50fb-4c8e-be1b-41828f993cf5.png)

Chinese Style House 

The build has 2,788 blocks, excluding air.

**Comment by PiweeX** [comment]
Saradnja na kraju NIJE postignuta do kraja
