### ISSUE TITLE
Mediveal Spawn - MonarchMC (samazzo_) KingRagnar

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#153]
200x200 mediveal spawn

**Comment by Viktor023023** [comment]
Px daj sekire pls

**Comment by PiweeX** [comment]
### 200x200 mediveal spawn as agreed in DM

**More Info:**

> we want a server w a central area and then there will be paths running off w small diff structures all around lakes and shit a prison somewhere which is like the entrace blcoked off and a bit raised then u fall in

**Something for reference**

![2022-09-10_20 16 27](https://user-images.githubusercontent.com/33425430/189545347-e11aeba0-120f-46f0-aac3-96ea6b41b057.png)

![2022-09-10_20 16 13](https://user-images.githubusercontent.com/33425430/189545352-e15ffefe-9065-485f-aa5b-8bf93715407a.png)

![2022-09-10_20 16 46](https://user-images.githubusercontent.com/33425430/189545357-3fef2c9a-1ba3-4ab8-9899-f09e7eb9bed5.png)

**Comment by PiweeX** [comment]
Game version 1.18.2

IP ?

**Comment by samazzo2002** [comment]
you need the ip? for what?

**Comment by PiweeX** [comment]
> you need the ip? for what?

hello, no need, we have our own test server and we are building there, but it is private, so we did not share it

**Comment by samazzo2002** [comment]
Good morning , any updates?

**Comment by PiweeX** [comment]
Gotovo već
