### ISSUE TITLE
Mediveal 75x75 spawn

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#157]
**i would like a medieval themed spawn 75x75 i need a shop built**

### Мedieval 75x75 spawn

Game Version: 1.19.2
Game Type: Java

IP: **PRIVATE**

(delivery time is 6 days, but it could be done earlier)

You can follow the build process (in screenshots) at the link:

https://github.com/PiweeX/HogRealms/issues/157

**Comment by GGMate87m** [comment]
where do i see the pictures ?

**Comment by Fqzoon** [comment]
> where do i see the pictures ?

hello, im builder of project, can i know for what type of server is this spawn? and do you need interrior in houses?

**Comment by GGMate87m** [comment]
what do you mean what type of sever spawn. and yes i would like the insides decorated some like shop interriors tho

**Comment by Fqzoon** [comment]
> what do you mean what type of sever spawn. and yes i would like the insides decorated some like shop interriors tho

i mean like is it for factions, vanilla, prison... etc

**Comment by GGMate87m** [comment]
like a kingdom rp so i guess factions

**Comment by Fqzoon** [comment]
> like a kingdom rp so i guess factions

would you like undeground shop at spawn?

**Comment by GGMate87m** [comment]
sure

**Comment by PiweeX** [comment]
Ended 😄👍🏻
