### ISSUE TITLE
складиште Workspace (skladiste.net - Changelog (MNB - Minecraft na Balkanu udruženje građana)

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#162]
Skladište je privatni Hosting koji je kreiran u svrhu držanja Hogovih mašina na sigurnom mestu i koji nije namenjen za javnu upotrebu

ipak, imamo i deo hostinga u delu društveno korisnih poslovanja gde za Balkan ali i strano tržište dajemo 100% besplatan hosting vrhunske kvalitete, to radimo jer je nama hosting od 2017. predstavljao veliki problem

https://skladiste.net

**Comment by PiweeX** [comment]
Hogovi serveri na mašini 1 ne učitavaju na panelu kako treba, proverena je domena na kojoj je mašina međutim ona neće isteći još dugo, danas je trebalo produžiti domenu od HogRealms-a te je produžena, čeka se odobrenje pa kreću radovi zbog kvara na teksturi, biće odloženi iako su planirani večeras

**Comment by PiweeX** [comment]
Zbog nemogućnosti da se uđe na Proxy server pošto se idalje čeka domena kako za HogRealms bi deo skladišta koji je na mašini 1 radilo normalno danas ipak neće moći da se odviju radovi niti da se Attacku daju permisije, ipak teksture su popravljene od jutros i sa tim nema nikakvih problema više

**Comment by Viktor023023** [comment]
je l ce moci sutra da se odrzi uhc?

**Comment by PiweeX** [comment]
> je l ce moci sutra da se odrzi uhc?

nadamo se, javićemo da li će biti, u suštini idalje je isti problem i ne možemo uticati na to, svi podserveri rade sem UHCa i to baš danas kad je game, pokušali smo transfer međutim ne vredi kad su fajlovi praktično odsečeni od panela tačnije ne mogu se pristupiti zbog problema sa domenom

**Comment by PiweeX** [comment]
Main Button Name na skladiste.net promenjen u Stranica iz Nas Sajt

**Comment by PiweeX** [comment]
Pošto transfer UHC servera zbagao i tako stoji već od juče UHC će biti sređen od nule do večeras, ovo će prebaciti server na 1.8.8 verziju koju su tražili i igrači

**Comment by PiweeX** [comment]
Priče za laku noć radio bot obrisan jer jedini nije bio sastavljen niti ima potrebe za njim

**Comment by PiweeX** [comment]
### Danas je bilo velikih problema sa UHCom jer smo nabavili novu licencu i sve je rađeno od 0 a tu su nastali veliki problemi i puno igrača je 1h čekalo meč jer je nekima ulazak na podserver radio a nekima nije, u suštini meč je održan i kao što su igrači tražili server je prebačen na 1.8.8 i 1.8.9 verziju a na 1.7.10 se više NE može ući, 1.8 je mnogo stabilniji i drago mi je da smo sredili mnoge stvari koje će se pokazati tek od sledećeg meča, recimo discord obavesti na UN polu automatske, nove scenarije, novi tab koji će biti prikazan od sledećeg nadam se

**Comment by PiweeX** [comment]
> ### Danas je bilo velikih problema sa UHCom jer smo nabavili novu licencu i sve je rađeno od 0 a tu su nastali veliki problemi i puno igrača je 1h čekalo meč jer je nekima ulazak na podserver radio a nekima nije, u suštini meč je održan i kao što su igrači tražili server je prebačen na 1.8.8 i 1.8.9 verziju a na 1.7.10 se više NE može ući, 1.8 je mnogo stabilniji i drago mi je da smo sredili mnoge stvari koje će se pokazati tek od sledećeg meča, recimo discord obavesti na UN polu automatske, nove scenarije, novi tab koji će biti prikazan od sledećeg nadam se

Upravo sređen TAB za 1.8 za UHC kao i čet a i tabela sa strane je uređena da piše Balkan UHC Sezona V

![download](https://user-images.githubusercontent.com/33425430/190877701-f573cc22-e833-4067-9214-90ee39af2d42.png)

**Comment by PiweeX** [comment]
> > ### Danas je bilo velikih problema sa UHCom jer smo nabavili novu licencu i sve je rađeno od 0 a tu su nastali veliki problemi i puno igrača je 1h čekalo meč jer je nekima ulazak na podserver radio a nekima nije, u suštini meč je održan i kao što su igrači tražili server je prebačen na 1.8.8 i 1.8.9 verziju a na 1.7.10 se više NE može ući, 1.8 je mnogo stabilniji i drago mi je da smo sredili mnoge stvari koje će se pokazati tek od sledećeg meča, recimo discord obavesti na UN polu automatske, nove scenarije, novi tab koji će biti prikazan od sledećeg nadam se
> 
> Upravo sređen TAB za 1.8 za UHC kao i čet a i tabela sa strane je uređena da piše Balkan UHC Sezona V
> 
> ![download](https://user-images.githubusercontent.com/33425430/190877701-f573cc22-e833-4067-9214-90ee39af2d42.png)

Sklonjeno stejkovanje mobova u potpunosti, nije scenario

**Comment by PiweeX** [comment]
> > > ### Danas je bilo velikih problema sa UHCom jer smo nabavili novu licencu i sve je rađeno od 0 a tu su nastali veliki problemi i puno igrača je 1h čekalo meč jer je nekima ulazak na podserver radio a nekima nije, u suštini meč je održan i kao što su igrači tražili server je prebačen na 1.8.8 i 1.8.9 verziju a na 1.7.10 se više NE može ući, 1.8 je mnogo stabilniji i drago mi je da smo sredili mnoge stvari koje će se pokazati tek od sledećeg meča, recimo discord obavesti na UN polu automatske, nove scenarije, novi tab koji će biti prikazan od sledećeg nadam se
> > 
> > 
> > Upravo sređen TAB za 1.8 za UHC kao i čet a i tabela sa strane je uređena da piše Balkan UHC Sezona V
> > ![download](https://user-images.githubusercontent.com/33425430/190877701-f573cc22-e833-4067-9214-90ee39af2d42.png)
> 
> Sklonjeno stejkovanje mobova u potpunosti, nije scenario

Filecleaner vraćen i biće podešen sutra verovatno, takođe dodat je BPS free i ista konfiguracija koja ima na Decentralandu

napomenuo bih i da je sređen BungeeGuard tako da se server UHC neće stopirati tokom cele nedelje, biće uključen a upravo će biti ubačen i isti folder automatskog restarta kao i na Decentralandu

**Comment by marepleb** [comment]
MARE ZA DZELATA (vodicu uhc marinka mi)

**Comment by PiweeX** [comment]
Ovih dana od kako je oboren rekord (bez reklami) je bilo par krešova, 1 do 2, dakle recimo UHC se krešovao na početku ali na svu sreću je odmah startovan nakon toga u razmaku od 5 minuta ali na način da se smanji CPU na Decentraland podserveru i da se mnogi radio botovi ugase, takođe možda pre nedelju dve sam dobio informaciju da nije reč o ddosu kad se desio poslednji pad servera već je sve overalocateano,

malo pre je ponovo bio pad glavnih podservera i odmah se znalo do čega je iako je bio DB error

puno discord botova su nam imali po 1 GB raspoređeno.. sad sam smanjio sve u 3gb na VPSu gde se drži skladište tako da je hog mašina 1 oslobođena i tu su samo MC serveri sad (za HogRealms i Hogo Studios što uključuje 5 build storage servera za buildere i 1 za lobby i 1 za bungee pošto tu koristimo bungeecord)

problem sa overallocateom je rešen, sve mašine dišu samo imamo problema sa 2 ključna podservera, Lobby i Decentraland, na Lobiju je skroz resetovalo server.properties i kad bi se postavke zamenile server opet nebi želeo da se startuje, na Decentralandu je slučaj da je ostavilo taj fajl prazan, ipak svi ostali fajlovi deluju ok, nadam se da nema nekih većih problema kao što se dešavalo u alfa verziji Decentralanda da se brišu najvažniji fajlovi baza podataka igrača poput za statistiku MMO i ostalo

ovo rešavamo tokom noći ili maksimalno do sutra posle podne, svaka nedelja dođe užasna nedelja sa tehničke strane, baksuzi i to ti je

**Comment by PiweeX** [comment]
Upravo je i poslednji Build Storage 3 server prebačen na Hog mašinu 1 dakle sad su svi podserveri na tom nodeu

**Comment by PiweeX** [comment]
Sve je fixano, potrajao je dan dok se memorija nadograđivala dakle prepunjeno je 2TB storage prostora i nabavljeno je još 1TB ali još uvek je prepunjeno tako da će svi Hogo Studios serveri (za build) biti vraćeni na mašinu 2 tačnije 3

sve je okej i ostalo netaknuto, ima problem samo da se svima MMO statistika resetovala što ćemo pokušati da rešimo jer imamo backupove redovne i na panelu za taj plugin pošto se vrlo često u predhodnim godinama dešavalo slično sa njim

**Comment by PiweeX** [comment]
> Sve je fixano, potrajao je dan dok se memorija nadograđivala dakle prepunjeno je 2TB storage prostora i nabavljeno je još 1TB ali još uvek je prepunjeno tako da će svi Hogo Studios serveri (za build) biti vraćeni na mašinu 2 tačnije 3
> 
> sve je okej i ostalo netaknuto, ima problem samo da se svima MMO statistika resetovala što ćemo pokušati da rešimo jer imamo backupove redovne i na panelu za taj plugin pošto se vrlo često u predhodnim godinama dešavalo slično sa njim

Samo da javim ovde da smo par dana posle ovoga tu opet imali prepunjenje memorijom, totalni overallocate koji je sve plugine pokvario tako da su vraćani od 30.og, i na UHC i na mnogim podserverima, uglavnom rešeno je ali server radi dokle god ne bude UHC event e tad se dešavaju chunk problemi i recimo ovaj petak smo imali velikih problema da je UHC krešovao na pola i posle ga nismo mogli ni startovati zbog problema pa smo vratili backup pa se nije ni održao zbog novih problema, uglavnom zakupili smo još 2 TB storage prostora za Hetzner 1 mašinu ali jako je teško podesiti i kolege će podesiti što pre budu mogli a kad uspeju biće super

ovo nam je napravilo problem sa mašinom 2 jer smo sve Hogo Studios servere prebacili na tu mašinu privremeno i suspendovali ih i stopirali ali smo morali da ugasimo i ostale servere od klijenata koji su besplatno mintovali svoje hostinge a mnogi čekaju da mintuju iako su skupili sve invitove, svakako rešićemo i biće super optimizacija sad

**Comment by PiweeX** [comment]
> > Sve je fixano, potrajao je dan dok se memorija nadograđivala dakle prepunjeno je 2TB storage prostora i nabavljeno je još 1TB ali još uvek je prepunjeno tako da će svi Hogo Studios serveri (za build) biti vraćeni na mašinu 2 tačnije 3
> > sve je okej i ostalo netaknuto, ima problem samo da se svima MMO statistika resetovala što ćemo pokušati da rešimo jer imamo backupove redovne i na panelu za taj plugin pošto se vrlo često u predhodnim godinama dešavalo slično sa njim
> 
> Samo da javim ovde da smo par dana posle ovoga tu opet imali prepunjenje memorijom, totalni overallocate koji je sve plugine pokvario tako da su vraćani od 30.og, i na UHC i na mnogim podserverima, uglavnom rešeno je ali server radi dokle god ne bude UHC event e tad se dešavaju chunk problemi i recimo ovaj petak smo imali velikih problema da je UHC krešovao na pola i posle ga nismo mogli ni startovati zbog problema pa smo vratili backup pa se nije ni održao zbog novih problema, uglavnom zakupili smo još 2 TB storage prostora za Hetzner 1 mašinu ali jako je teško podesiti i kolege će podesiti što pre budu mogli a kad uspeju biće super
> 
> ovo nam je napravilo problem sa mašinom 2 jer smo sve Hogo Studios servere prebacili na tu mašinu privremeno i suspendovali ih i stopirali ali smo morali da ugasimo i ostale servere od klijenata koji su besplatno mintovali svoje hostinge a mnogi čekaju da mintuju iako su skupili sve invitove, svakako rešićemo i biće super optimizacija sad

mogu reći takođe da sam danas upravo predao Decentraland podserver na skladištu Djovaniju kao menadžeru a Attacku Dev server koji je isto na Realmsu samo skriven

Zašto? Attack radi plugine za Decentraland i njemu će trebati, Djovani uređuje spawn kao i mnoge druge stvari sa igračima trenutno bez da mu je iko tražio i prosto vreme je da ja prepustim to sve u ruke igrača kroz odgovornu osobu a to je Djovani u koga imam puno poverenje jer je jedini ostao od dželata kada su svi otišli i pljuvali a mogao je biti admin na drugim proleterskim serverima, pored toga on veruje u celu priču i zbog toga je pre možda mesec i unapređen u Menadžera kompanije, igrom slučaja živimo u istom gradu i prosto jako dobro funkcioniše i rešava probleme bez panike niti kontaktiranja mene, oko 600 tiketa je zatvoreno do sad (na novom botu) a meni ni 1 nije napisana poruka u DM

Sad kad razmislim zaboravih da nadodam da je i PSIHU predat SMP, Psiho radi nove sezone na Hogu od 2017. i nikad nije imao ništa od toga, prosto je radio to što je želeo da uvek imamo dobru sezonu

zaista neverovatno kakve smo osobe skupili uz Hog, na njima će se izgraditi sve na viši nivo u to sam uveren

**Comment by marepleb** [comment]
> 

taman sad ja support preko veze i upadnem na smp preko veze.I da naravno i memoriju dobijem preko veze!

**Comment by PiweeX** [comment]
Većina botova na skladištu fixani, radio botovima je pre koji dan sklonjen automatski restart jer su se stalno krešali i tražili update a sad im je vraćen jer se ram prepuni kad se server dugo ne restartuje.. Uglavnom rešen problem, što se tiče support bota za tradingflow i hogostudios fali im index.js fal i ne znam zbog čega ali i dalje ne rade ni kad se ubace ali pokušavam da rešim, za core bota za tradingflow koji je radio bio je problem i stigla mi je već bila notifikacija da je opet prestigao neki limit od 1k interakcija na discordu tačnije da mu je 1k ljudi videlo profil nemam pojma uglavnom zamenjen je kod i radi kao i što je namešten i radio bot

**Comment by PiweeX** [comment]
Ponovo mi je došlo na pamet dok sam se dopisivao s Dense-om ono što smo pre otvaranja Decentralanda imali u planu a to je da smo hteli da skladište tačnije tad balkannodes hosting bude hostovan od nas od kuće, tad nam je zbog IPova koji bi bili na datacentru u Srbiji trebala firma a takođe zbog interneta optičkog kako bi uopšte proveli treba nam firma, sad imamo registrovanu firmu pa ćemo čim se ukaže prilika prebaciti (ako sve uspe) glavnu Hogovu mašinu u Lazarevac

**Comment by marepleb** [comment]
> Ponovo mi je došlo na pamet dok sam se dopisivao s Dense-om ono što smo pre otvaranja Decentralanda imali u planu a to je da smo hteli da skladište tačnije tad balkannodes hosting bude hostovan od nas od kuće, tad nam je zbog IPova koji bi bili na datacentru u Srbiji trebala firma a takođe zbog interneta optičkog kako bi uopšte proveli treba nam firma, sad imamo registrovanu firmu pa ćemo čim se ukaže prilika prebaciti (ako sve uspe) glavnu Hogovu mašinu u Lazarevac

mogu li da posetim glavnu masinu?

**Comment by PiweeX** [comment]
Na svim podserverima na skladištu su odrađeni updateovi, novi backupovi i optimizacije

pored toga zbog konstantnih napada radimo i bezbedonosne mere, svi bot tokeni tačnije botovi će se prebaciti na moj drugi nalog jer je ovako rizično

**Comment by PiweeX** [comment]
Skladište nakon najave 3 nove mašine gasi svoj discord i zbog bolje organizuje prelazi na Minecraft na Balkanu discord

Više sam okačio u drugom issue-u pa neću pisati
