### ISSUE TITLE
Fishing

### ISSUE THREAD

**Issue by PavlePana** [PiweeX/PiweeX#164]
Dobar dan.

Hteo sam da odrzimo glasanje preko githuba oko pitanja cene riba.Mislim da bi cena trebala da se vrati na staru.Ako se neko ne seca kako se odredjivala cena riba evo nesto ukratko:

Za legy 3x velicina ribe
Za epic 2x velicina ribe
Za uncommon 1x velicina ribe
Za common 1x velicina ribe

Ko glasa za da nek stavi thumbs up
Ko se protivi nek stavi thumbs down

**Comment by NemanjaRusija2** [comment]
Ako bi se povećala svi bi pecali niko ne bi sa wheatom radio čak ni kao drvosječa. Jedino da se poveća za nijansu više ništa više od toga. Još kad dođe mainet pa će se prodavati gold, drva itd... Treba sačekati to pa ekonomiju stabilizovat ili možda neće trebati. Toliko od mene.

**Comment by PiweeX** [comment]
Zatvoriću jer se cena ribe optimizuje po cenama ostalih stvari, mislim da će ribolov dobiti boost vrlo uskoro a sad smo sve i fixali oko toga da par dana nije kikovalo ako bi neko bio afk i pecao preko haka ili autoklikera, nije radilo par dana ili malo duže jer sam greškom obrisao taj jar
