### ISSUE TITLE
Čuvar Energije

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#165]
Plugin koji će se u budućnosti napraviti biće plugin koji bi svaki put dok na serveru nema nikog isključivao sve chunkove i plugine tako da se CPU servera smanji a da server ostane uključen, ovo je recimo korisna stvar koja bi čuvala električnu energiju, nije toliko potrebno ali svakako korisno za imati i verujem da će biti među najviše traženim pluginima

**Comment by marepleb** [comment]
> Plugin koji će se u budućnosti napraviti biće plugin koji bi svaki put dok na serveru nema nikog isključivao sve chunkove i plugine tako da se CPU servera smanji a da server ostane uključen, ovo je recimo korisna stvar koja bi čuvala električnu energiju, nije toliko potrebno ali svakako korisno za imati i verujem da će biti među najviše traženim pluginima

https://www.spigotmc.org/resources/hibernate.4441/ postoji vec prijatelju

**Comment by PiweeX** [comment]
Plugin će biti gotov do kraja Januara

**Comment by PiweeX** [comment]
Prebaceno u poseban issue za sve plugine sa Java Store platforme
