### ISSUE TITLE
Asian themed spawn (mastahlb) Front

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#174]
Hey, I need a medium sized Asian style lobby. I have added a few pictures for you. You should orientate yourself by the styles.

![2022-09-17_23 04 39](https://user-images.githubusercontent.com/33425430/191612741-71b102f1-9200-41e6-8294-d23d5ffdffdb.png)
![2022-09-17_23 05 40](https://user-images.githubusercontent.com/33425430/191612751-a2266d82-0144-40c0-a8b5-dd87e19168eb.png)
![2022-09-17_23 03 06](https://user-images.githubusercontent.com/33425430/191612755-ad186e3c-9587-4e65-bed1-b167eace5930.png)
![2022-09-17_23 04 23](https://user-images.githubusercontent.com/33425430/191612761-4679d42b-2eac-413b-b8d0-55c17a1cab81.png)

Game Version: 1.8.9
Game Type: JAVA
Delivery Time: 10d

Front

**Comment by TheFrontView** [comment]
![2022-09-30_17 25 58](https://user-images.githubusercontent.com/71612070/193304135-01b4a19d-42fc-4774-b5a8-fd631078efab.png)
![2022-09-30_17 25 55](https://user-images.githubusercontent.com/71612070/193304141-da9eb1f2-8807-448a-b82d-cefd7b0c3f9c.png)

Sadly, we do not have most of the newest blocks for building but, we will do with the ones that we have. I have an idea to make this look like a small Asian map. I will give you later more sneak peeks.

**Comment by TheFrontView** [comment]
![2022-09-30_20 02 15](https://user-images.githubusercontent.com/71612070/193329950-b090ceea-0438-4ccc-a87c-d39d84996fb4.png)
![2022-09-30_20 02 19](https://user-images.githubusercontent.com/71612070/193329956-6532a91f-049f-4068-ad69-d9656b006711.png)

More update on build.

**Comment by Angxstupst** [comment]
Its looks nice 😄 (im mastahlb)

**Comment by TheFrontView** [comment]
![2022-10-01_11 21 58](https://user-images.githubusercontent.com/71612070/193402633-a8ff8805-ec44-4ddd-980f-402acc11e4d9.png)
![2022-10-01_11 22 07](https://user-images.githubusercontent.com/71612070/193402636-f358bb0f-1cd1-48c1-95bc-4b328dcb8d88.png)
![2022-10-01_11 21 46](https://user-images.githubusercontent.com/71612070/193402637-a0f0b17e-cebf-4594-be68-c900840dd783.png)
![2022-10-01_11 21 48](https://user-images.githubusercontent.com/71612070/193402638-df149ecf-cb44-4417-be4e-f89b99b6c8a9.png)
![2022-10-01_11 21 51](https://user-images.githubusercontent.com/71612070/193402639-3f3e2321-fb0b-44d2-ba88-f479a06a9509.png)


> Its looks nice 😄 (im mastahlb)

Hi, we are nearly there. We need to make a little more decoration.

**Comment by TheFrontView** [comment]
> Its looks nice 😄 (im mastahlb)

Hey, quick question how many NPC slots do you want?

**Comment by TheFrontView** [comment]
![2022-10-01_12 01 51](https://user-images.githubusercontent.com/71612070/193404075-ed3114e5-1269-4b49-8a60-dd4ce2892a17.png)
![2022-10-01_12 02 01](https://user-images.githubusercontent.com/71612070/193404076-fd337d06-7968-4ef3-a594-8744e45d14f6.png)
![2022-10-01_12 02 10](https://user-images.githubusercontent.com/71612070/193404078-a6b2becd-73d2-484c-b2bf-937b30760c81.png)
![2022-10-01_12 01 43](https://user-images.githubusercontent.com/71612070/193404079-c99fe146-a2f4-4b2d-a4a8-5d6c225b85f6.png)
![2022-10-01_12 01 44](https://user-images.githubusercontent.com/71612070/193404081-cd0e58d6-2358-44cd-bde3-93047c4d3d39.png)
![2022-10-01_12 01 46](https://user-images.githubusercontent.com/71612070/193404082-7e6976cb-1c05-4504-8eca-46b16e5ebae7.png)

**Comment by TheFrontView** [comment]
![2022-10-01_13 41 33](https://user-images.githubusercontent.com/71612070/193407895-38970fba-3d79-4aad-befb-1309051c167d.png)
![2022-10-01_13 41 38](https://user-images.githubusercontent.com/71612070/193407900-65194348-4065-4259-a969-1f770fcfc086.png)
![2022-10-01_13 40 49](https://user-images.githubusercontent.com/71612070/193407903-3cf0fa21-0e87-4316-8992-6946d96f7e0d.png)
![2022-10-01_13 40 55](https://user-images.githubusercontent.com/71612070/193407904-6abe846f-1010-456b-a720-2e168d25a136.png)
![2022-10-01_13 41 01](https://user-images.githubusercontent.com/71612070/193407908-9a72e1f4-2c51-49a6-be11-80b1bb6302ef.png)
![2022-10-01_13 41 08](https://user-images.githubusercontent.com/71612070/193407910-35c631a0-c9df-48de-af02-a2ec1926d20a.png)
![2022-10-01_13 41 16](https://user-images.githubusercontent.com/71612070/193407914-e64ce4fe-5836-4139-8a0d-09718b310a70.png)
