### ISSUE TITLE
Roleplay varijante

### ISSUE THREAD

**Issue by Attack36** [PiweeX/PiweeX#175]
Imam jednostavan ali ključan prijedlog za hog custom iteme, koji glasi: Da se za poznate custom iteme tipa katana naprave varijanti da pašu roleplay drzavama. Tipa da se napravi custom item "Dvoručni Mać" ili "Sablja" ili "Vikinška sjekira" itd. sa istim ability i statovima kao katana te kad se taj item osvoji (npr. na UHCu) osoba koja ga je osvojila bira jedan od to troje koji pašu roleplayu te države.

**Comment by NemanjaRusija2** [comment]
> Imam jednostavan ali ključan prijedlog za hog custom iteme, koji glasi: Da se za poznate custom iteme tipa katana naprave varijanti da pašu roleplay drzavama. Tipa da se napravi custom item "Dvoručni Mać" ili "Sablja" ili "Vikinška sjekira" itd. sa istim ability i statovima kao katana te kad se taj item osvoji (npr. na UHCu) osoba koja ga je osvojila bira jedan od to troje koji pašu roleplayu te države.

Loša ideja. Prvo valjda je logično da custom itemi trebaju da budu rijetki a ne da pripadaju nekim rp državama. Drugo custom itemi će biti na vote. Treće države trebaju da napreduju do novca (hardcore) da bi kupovali stvari. Ako bi dobili bili bi npr. svjetska sila. Zar to nije glupo?

**Comment by galileoba** [comment]
pa svakako svakog petka dobijaju custom item samo sto ce u ovom slucaju moci da biraju izmedju 3 itema koja su zapravo ista samo biras skin

**Comment by NemanjaRusija2** [comment]
Nekad bude i novac. Ali dobro neka odluči većina

**Comment by Attack36** [comment]
> > Imam jednostavan ali ključan prijedlog za hog custom iteme, koji glasi: Da se za poznate custom iteme tipa katana naprave varijanti da pašu roleplay drzavama. Tipa da se napravi custom item "Dvoručni Mać" ili "Sablja" ili "Vikinška sjekira" itd. sa istim ability i statovima kao katana te kad se taj item osvoji (npr. na UHCu) osoba koja ga je osvojila bira jedan od to troje koji pašu roleplayu te države.
> 
> Loša ideja. Prvo valjda je logično da custom itemi trebaju da budu rijetki a ne da pripadaju nekim rp državama. Drugo custom itemi će biti na vote. Treće države trebaju da napreduju do novca (hardcore) da bi kupovali stvari. Ako bi dobili bili bi npr. svjetska sila. Zar to nije glupo?

Krivo si me shavtio. Poanta je da su rijetki, ovo nije vise itema samo biranje skin da pasu uz roleplay. Kakvog je smisla da ne znam Brazil ima Katane. Ovako samo postujemo roleplay

**Comment by NemanjaRusija2** [comment]
> > > Imam jednostavan ali ključan prijedlog za hog custom iteme, koji glasi: Da se za poznate custom iteme tipa katana naprave varijanti da pašu roleplay drzavama. Tipa da se napravi custom item "Dvoručni Mać" ili "Sablja" ili "Vikinška sjekira" itd. sa istim ability i statovima kao katana te kad se taj item osvoji (npr. na UHCu) osoba koja ga je osvojila bira jedan od to troje koji pašu roleplayu te države.
> > 
> > 
> > Loša ideja. Prvo valjda je logično da custom itemi trebaju da budu rijetki a ne da pripadaju nekim rp državama. Drugo custom itemi će biti na vote. Treće države trebaju da napreduju do novca (hardcore) da bi kupovali stvari. Ako bi dobili bili bi npr. svjetska sila. Zar to nije glupo?
> 
> Krivo si me shavtio. Poanta je da su rijetki, ovo nije vise itema samo biranje skin da pasu uz roleplay. Kakvog je smisla da ne znam Brazil ima Katane. Ovako samo postujemo roleplay

Ahh... Greške se dešavaju. Sori

**Comment by NemanjaRusija2** [comment]
Hoće li biti teško da se izvede to?

**Comment by JedemJaja** [comment]
> Imam jednostavan ali ključan prijedlog za hog custom iteme, koji glasi: Da se za poznate custom iteme tipa katana naprave varijanti da pašu roleplay drzavama. Tipa da se napravi custom item "Dvoručni Mać" ili "Sablja" ili "Vikinška sjekira" itd. sa istim ability i statovima kao katana te kad se taj item osvoji (npr. na UHCu) osoba koja ga je osvojila bira jedan od to troje koji pašu roleplayu te države.

Knedla je bolji od tebe

**Comment by PiweeX** [comment]
Možemo praviti to, već je urađena hrpa custom oružja koje će biti rasprostranjeno po celom serveru i to je već duži plan da custom itemi ne budu toliko retki u smsilu da ne budu nešto strano "E px ja bi custom item" nego će svi imati a vredniji će se više vrednovati, kao i sa stvarima

Posle toga sledi ubacivanje novih mobova, mainnet tek stiže i ima puno da se sređuje 😃
