### ISSUE TITLE
UHC Zlato, srebro, bronza..

### ISSUE THREAD

**Issue by DaniloU2008** [PiweeX/PiweeX#176]
Smatram da bi rangiranje bar prvih 3. mesta  trebalo da dobije nagradu jer ulazi dosta ljudi i svi žele prvo mesto i na primer oni koji su imali pola srca vise pobede, a ne postoji drugo mesto za one koji su imali samo malo manje sanse.
Želeo bih da stavim ovo glasanje da se dobiju rankovi
jer ima dosta ljudi koji žele nagradu.
Na pr. 1. mesto za solo vlaška knjiga, 2. 70k, 3. 25k.
Želeo bih da se ovo usvoji jer znam da će ljudi više igrati više jer se dodaje nešto kao na pravim takmičenjima,  postoje šanse i za ostale.
Hvala.

**Comment by nikolaNr7** [comment]
da moze

**Comment by PiweeX** [comment]
Slažem se, to bi bilo super po meni, odradićemo

**Comment by DaniloU2008** [comment]
👍

**Comment by PiweeX** [comment]
UHC je dobio update na 1.7.10 kako ste trazili iako ima problema novih oko toga da igraci ne mogu uci na starije verzije od 1.16 zbog ulaska na lobby koji je na mapi gde postoji veci svet

sto se tice rangiranja po levelima, ako bude moglo napravicemo
