### ISSUE TITLE
Za helpera.

### ISSUE THREAD

**Issue by DaniloU2008** [PiweeX/PiweeX#178]
Pravim ovo glasanje da bih pokušao da poboljsam server.
Aktivan sam svakog dana minimum 5h a najviše 11h
(ujutro u skoli oko 2h, popodne od 14h do 22h sam online na discordu i na hogu, u toku noći uđem na disc. i čitam poruke).
Pomogao sam dželatima  u zadnjih mesec dana u nekoliko istraga.
Mislim da bih se uklopio u tim i bio bih efikasan.
Ako se ovo pravilo usvoji imaću podsticaj da budem još više aktivan i uspostavio bih bolje veze sa adminima.

**Comment by yamizvaniuchicha** [comment]
msm da bi danilo bio dobar helper

**Comment by Siu804** [comment]
Helper?Px ce reci kad ce mu trebati ne treba da smarate a i ne znam ko je od Shagobi-ja i tebe Danilo vredjao server kad je "isao" sa servera...

Veliki dosije:

DaniloU08 - BAN - veliki dosije, nova kradja, pravljenje altova

DaniloU08 - jail 60d - ogromna
 kradja i vec ima dosije

DaniloU08 - jail 4d - grief

Ovo je samo dosije i zasto ne treba biti helper a i nisu potrebni,ne verujem da bi bio dobar sa obzirom da je on vredjao server kad je isao(koliko znam)

**Comment by DaniloU2008** [comment]
Ne ne znas.
Ja nisam vredjao server i napisao sam u chat d aje hog najbolji, shabogiju sam rekao da ne pravi skandal.
Sam je izabrao.
Sve ovo je proslost, okrenuo sam nov list.

**Comment by DaniloU2008** [comment]
Prijavio sam se za dzelata jer sam uvek aktivan i naucio sam pravila, dobro poznajem server i zelim da mu pomognem.

**Comment by Siu804** [comment]
Pa bas ima veze proslost pise da si dobio ban a nisi

**Comment by marepleb** [comment]
braco ako prosite kao ovaj lik dobicete helpera na 31 februar pozdrav

**Comment by PiweeX** [comment]
Što se tiče pozicija helpera primamo ih kad nam zatrebaju i ne razmišljamo mnogo niti gledamo prijave već primamo one koji su aktivni i koji doprinose zajednici na mnoge načine, tako da znate
