### ISSUE TITLE
Dodatci

### ISSUE THREAD

**Issue by yamizvaniuchicha** [PiweeX/PiweeX#180]
Da se vrati stara cena pšenice i da se doda još nešto da da se prodaje na spawnu, da se dodaju sve stvari koje mogu da se kupe na shop, i po mogućosti još 2 dželata (posao će se lakše završavati a i brže plus će onda neko od dželata biti online), da se poprave svi bagovi na serveru i msm da postoji neki plugin koji totalno zabranjuje da se uopste stavi x ray na serveru te će se automatski olakšati posao, imam još predloga ali polako :).

**Comment by TheFrontView** [comment]
2 Još 2 dželata treba plaćati nije to mala stavka xd

**Comment by NemanjaRusija2** [comment]
> 2 Još 2 dželata treba plaćati nije to mala stavka xd

I još 2 supporta hahahhaha

**Comment by Attack36** [comment]
> 2 Još 2 dželata treba plaćati nije to mala stavka xd

Kad meni px da plaću ce biti isti dan kad cu ja ući u mongoliju (no hate zlaji), znači nikada.

**Comment by PiweeX** [comment]
što se tiče dželata dovoljna su 3 jer timovi ne funkcionišu na više ljudi a što se tiče više stvari za prodaju biće drva i razmatramo o ekonomiji u drugom issueu trenutno
