### ISSUE TITLE
Micanje Claimova

### ISSUE THREAD

**Issue by Attack36** [PiweeX/PiweeX#181]
Mislim da je svima ovog dosta pa cu ja izložiti da PX odluči.

Hog ima problema gdje razni claimova ljudima na teritoriji ili od banovanih igrača su posvuda I smetaju posvuda. Vrlo je veliki problem I za sada nece prestati.

Posto px je dosta zauzet i nema vremena ici okolo, ulaziti na acc i tako kako bi svima micao claimove, ja kazem da se jednom od dželata, vjerovatno Djovaniju da moć da moze se force loginat nekom na acc i maknut claim.

Istina da se mice za 30 dana ali ako nekom claim jako smeta kao npr. Kalmarskoj uniji koja se ne moze siriti vise da se treba micati i igraci nemaju toliko strpljenja. 

Mislim da koga god se pita to je najbolja opcija jer ja sam opcenito za to da dželati mogu raditi sto vise stvari bez pxa jer je on zauzet i jer tako su efikasniji jer je za sada ovo bottleneck opcenito, barem ja tako mislim i to ne samo za ovaj issue.

**Comment by PiweeX** [comment]
> 

slažem se, Djovani već ima pristup za forcelogin preko Un četa, dat mu je da bi se to moglo rešavati po nekad ali to nije dugoročno rešenje, moramo imati što više automatizovanih sistema koji će rešavati probleme, zato sam danas ponovo radio na tome da se claimovi brišu nakon 30 dana i MOŽDA bi moglo to biti to, videćemo da li će se sami brisati, i ja bih voleo, ne volim nikako što ima previše claimova pogotovo ovih neaktivnih

**Comment by PiweeX** [comment]
danas je bio dogovor povodom ovoga sa Attackom tako da on sad ima permisije, napišite u ovaj issue za koje sve države mislite da trebaju biti obrisane kako bi se one bolje razvijale (misli se na neaktivne i na one od banovanih igrača i sl.)

**Comment by PiweeX** [comment]
ja pre svega mislim da treba obrisati one veće neaktivne claimove poput CCG ako je još tu i poput Austrougarske jer je poslednji put bila aktivna prošle godine a nismo uspeli da je obrišemo jer komanda ne radi te se moralo ulaziti direktno na naloge tih vlasnika država a automatsko brisanje smo sređivali..

u suštini treba obrisati te veće i neke manje koji smetaju nekim boljim državama da se šire a koje su neaktivne ili skroz male a neaktivne i stare ili stvorene kao drugi claim nekoga, ne moraju sve kažem jer će se nekad brisati i same ali one ključne je bitno što pre obrisati

**Comment by ConeBe** [comment]
Delovi Carevine Crne Gore su podeljene koliko sam video, ja sam owner jednog landa tako da to ne brišite, ima i drugih CCG gradova koji su pripali drugim igračima, tako sa ne verujem da treba da se brišu njihovi stari claimovi, osim onih gde niko nije owner

**Comment by DzingisKan738** [comment]
> Mislim da je svima ovog dosta pa cu ja izložiti da PX odluči.
> 
> Hog ima problema gdje razni claimova ljudima na teritoriji ili od banovanih igrača su posvuda I smetaju posvuda. Vrlo je veliki problem I za sada nece prestati.
> 
> Posto px je dosta zauzet i nema vremena ici okolo, ulaziti na acc i tako kako bi svima micao claimove, ja kazem da se jednom od dželata, vjerovatno Djovaniju da moć da moze se force loginat nekom na acc i maknut claim.
> 
> Istina da se mice za 30 dana ali ako nekom claim jako smeta kao npr. Kalmarskoj uniji koja se ne moze siriti vise da se treba micati i igraci nemaju toliko strpljenja.
> 
> Mislim da koga god se pita to je najbolja opcija jer ja sam opcenito za to da dželati mogu raditi sto vise stvari bez pxa jer je on zauzet i jer tako su efikasniji jer je za sada ovo bottleneck opcenito, barem ja tako mislim i to ne samo za ovaj issue.

Russia - owner dako003
bu - owner Shadow

OsmanskoC - owner Kxxvin (nema ga online da prebaci na nas)
Sivas i Bainkonur isto go i osmansko

Asylum - owner Thundeerrr
VukovTrust - owner smrad Vuk_TheGreat
farmaaa - owner mega_gamer8734
NiggaBalls - owner Tomic
amfibija - owner pavlekss
andelonija - owner andelon
kurgat - owner pavlekss
Petrograd - owner Brumilda
nešto - owner conex999


naleti li jos koja javim

**Comment by NemanjaRusija** [comment]
> > Mislim da je svima ovog dosta pa cu ja izložiti da PX odluči.
> > Hog ima problema gdje razni claimova ljudima na teritoriji ili od banovanih igrača su posvuda I smetaju posvuda. Vrlo je veliki problem I za sada nece prestati.
> > Posto px je dosta zauzet i nema vremena ici okolo, ulaziti na acc i tako kako bi svima micao claimove, ja kazem da se jednom od dželata, vjerovatno Djovaniju da moć da moze se force loginat nekom na acc i maknut claim.
> > Istina da se mice za 30 dana ali ako nekom claim jako smeta kao npr. Kalmarskoj uniji koja se ne moze siriti vise da se treba micati i igraci nemaju toliko strpljenja.
> > Mislim da koga god se pita to je najbolja opcija jer ja sam opcenito za to da dželati mogu raditi sto vise stvari bez pxa jer je on zauzet i jer tako su efikasniji jer je za sada ovo bottleneck opcenito, barem ja tako mislim i to ne samo za ovaj issue.
> 
> Russia - owner dako003 bu - owner Shadow
> 
> OsmanskoC - owner Kxxvin (nema ga online da prebaci na nas) Sivas i Bainkonur isto go i osmansko
> 
> Asylum - owner Thundeerrr VukovTrust - owner smrad Vuk_TheGreat farmaaa - owner mega_gamer8734 NiggaBalls - owner Tomic amfibija - owner pavlekss andelonija - owner andelon kurgat - owner pavlekss Petrograd - owner Brumilda nešto - owner conex999
> 
> naleti li jos koja javim

je li se brišu sami?

**Comment by PiweeX** [comment]
Provlem sa neaktivnim claimovima će se u buduće kad se vrati i optimizuje unkeep claimova biti rešen ali do tad ćemo brisati ne više ulaskom na naloge već će se to rešavati kroz samo par sati preko komande
