### ISSUE TITLE
Brisanje claima Austro Ugarske

### ISSUE THREAD

**Issue by yamizvaniuchicha** [PiweeX/PiweeX#182]
Claim austrougarske stoji samo i skuplja prasinu skoro godinu dana, claim je trebao odavno da se obrise ali ocigledno nije.

**Comment by PiweeX** [comment]
> 

danas me je Attack zamolio za permisije dok Djovani nije tu tako da će nepotrebni claimovi uskoro biti obrisani, kroz naredne dane!

**Comment by PiweeX** [comment]
obrisan je nadam se!
