### ISSUE TITLE
Vuk_TheGreat i drugi članovi uprave (pozicija, rad, ovlasti i drugo)

### ISSUE THREAD

**Issue by galileoba** [PiweeX/PiweeX#183]
Otvorio sam ovaj issue prvenstveno jer sam **bio član ove zajednice i član staff tima**. Tako da veoma dobro poznajem Vuka i mogu da iznesem sve što imam kao dokazni materijal koji bi **DAO** stručnjaci mogli iskoristiti i usvojiti. Cilj mi je da iznesem dokaze koji će **pomoći i vama i zajednici**. S obzirom na to da sam banovan sa hoga te da su pojedini igrači kao i sam Piwex moje kritike prihvatili na neki drugi način ne znam kako ćete ovo protumačiti ali evo u tekstu ispod iznjet ću sve što imam.

Želim početi sa dotičnim Vukom velikim.
On je za vrijeme igranja na Hogu radio sve što je smio i što nije. Sve što kažem potvrdit ću **dokazima**.

- Pomagao je Skleperu u čuvanju abjuzanih itema na Antarktiku nakon što je Skleper banovan. 

**DOKAZ**
![image](https://user-images.githubusercontent.com/107082292/192114309-15bdee53-e138-40a2-aae3-6fcfa2691db7.png)

![image](https://user-images.githubusercontent.com/107082292/192114373-0bdab7c7-3184-43bf-97cf-167452c4d7a6.png)

- Prije nego što je postao dio staffa Vuk je bio banovan pa je čak ulazio i na alt naloge
![image](https://user-images.githubusercontent.com/107082292/192114493-4e9f33f7-8f6f-4c53-9baa-e2be508ad1d6.png)

- Skleperu je davao svoj nalog da igra dok je bio banovan 
![image](https://user-images.githubusercontent.com/107082292/192114511-36a2fc17-4ba5-407b-9573-026d8f57a566.png)

**Comment by galileoba** [comment]
S obzirom na sve što sam napisao iznad mislim da je sasvim jasno da osoba kao sto je vuk ne moze biti clan uprave ove zajednice i svakako bi bilo korektno da on ne moze da odlucuje ko ce dobiti ban

**Comment by vukstrale** [comment]
Dokazi izneti u ovom komentaru su već poznati vlasti servera. (btw slika sa altovima je DjoVanijeva greška, uradi malo back researcha). Abjuzani itemi koji su bili kod mene su predati dželatima, neabjuzovani su ostali. Tri slike sa Skleperom (Skleper?) su vezane za tu situaciju. Zadnja slika je moje objašnjenje daleko kasnije. Skleper je pretpostavio da će dobiti ban i dao mi je svoje iteme, što nije ilegalno, mnogi su to radili. Naknadno, njegov armour i pickaxe su dati lično tebi ne znam šta oćeš (takodje o tim itemima nikad ništa više nismo čuli.)

**Comment by vukstrale** [comment]
Jesi blesav e dao sam mu nalog da igra pre nego što je banovan sad sam video i tekst iznad "dokaza"

**Comment by galileoba** [comment]
> Dokazi izneti u ovom komentaru su već poznati vlasti servera. (btw slika sa altovima je DjoVanijeva greška, uradi malo back researcha). Abjuzani itemi koji su bili kod mene su predati dželatima, neabjuzovani su ostali. Tri slike sa Skleperom (Skleper?) su vezane za tu situaciju. Zadnja slika je moje objašnjenje daleko kasnije. Skleper je pretpostavio da će dobiti ban i dao mi je svoje iteme, što nije ilegalno, mnogi su to radili. Naknadno, njegov armour i pickaxe su dati lično tebi ne znam šta oćeš (takodje o tim itemima nikad ništa više nismo čuli.)

Kako mogu biti djovanijeva greska, jos si skleperu davao svoj acc da igra a slag na tortu zajedno sa skleperom si unloadao chunkove i pokusavao da nadjes razne bagove da abjuzas

**Comment by galileoba** [comment]
> Jesi blesav e dao sam mu nalog da igra pre nego što je banovan sad sam video i tekst iznad "dokaza"

![image](https://user-images.githubusercontent.com/107082292/192115151-675b18b1-7bb5-4663-9883-1798d8d7e74c.png)

**Comment by vukstrale** [comment]
> > Jesi blesav e dao sam mu nalog da igra pre nego što je banovan sad sam video i tekst iznad "dokaza"
> 
> ![image](https://user-images.githubusercontent.com/107082292/192115151-675b18b1-7bb5-4663-9883-1798d8d7e74c.png)

Pa pre bana

**Comment by vukstrale** [comment]
> > Dokazi izneti u ovom komentaru su već poznati vlasti servera. (btw slika sa altovima je DjoVanijeva greška, uradi malo back researcha). Abjuzani itemi koji su bili kod mene su predati dželatima, neabjuzovani su ostali. Tri slike sa Skleperom (Skleper?) su vezane za tu situaciju. Zadnja slika je moje objašnjenje daleko kasnije. Skleper je pretpostavio da će dobiti ban i dao mi je svoje iteme, što nije ilegalno, mnogi su to radili. Naknadno, njegov armour i pickaxe su dati lično tebi ne znam šta oćeš (takodje o tim itemima nikad ništa više nismo čuli.)
> 
> Kako mogu biti djovanijeva greska, jos si skleperu davao svoj acc da igra a slag na tortu zajedno sa skleperom si unloadao chunkove i pokusavao da nadjes razne bagove da abjuzas

Tako lepo pitaj ga

**Comment by galileoba** [comment]
> > > Dokazi izneti u ovom komentaru su već poznati vlasti servera. (btw slika sa altovima je DjoVanijeva greška, uradi malo back researcha). Abjuzani itemi koji su bili kod mene su predati dželatima, neabjuzovani su ostali. Tri slike sa Skleperom (Skleper?) su vezane za tu situaciju. Zadnja slika je moje objašnjenje daleko kasnije. Skleper je pretpostavio da će dobiti ban i dao mi je svoje iteme, što nije ilegalno, mnogi su to radili. Naknadno, njegov armour i pickaxe su dati lično tebi ne znam šta oćeš (takodje o tim itemima nikad ništa više nismo čuli.)
> > 
> > 
> > Kako mogu biti djovanijeva greska, jos si skleperu davao svoj acc da igra a slag na tortu zajedno sa skleperom si unloadao chunkove i pokusavao da nadjes razne bagove da abjuzas
> 
> Tako lepo pitaj ga

ne komuniciram s njim objasni mi it ovdje

**Comment by galileoba** [comment]
> > > Jesi blesav e dao sam mu nalog da igra pre nego što je banovan sad sam video i tekst iznad "dokaza"
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/107082292/192115151-675b18b1-7bb5-4663-9883-1798d8d7e74c.png)
> 
> Pa pre bana

znas li jos u koliko sati kad znas kad je banovan i kad si mu dao acc

**Comment by vukstrale** [comment]
A Skleper je dobijao brojne nagrade za njegovo nalaženje bugova, jedno vreme smo zajedno tražili razne bugove u pokušaju da dobijemo nagrade od staffa

**Comment by galileoba** [comment]
> A Skleper je dobijao brojne nagrade za njegovo nalaženje bugova, jedno vreme smo zajedno tražili razne bugove u pokušaju da dobijemo nagrade od staffa

a ponesto ste i iskoristili to mi je skleper pricao u call

**Comment by vukstrale** [comment]
> > > > Jesi blesav e dao sam mu nalog da igra pre nego što je banovan sad sam video i tekst iznad "dokaza"
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/107082292/192115151-675b18b1-7bb5-4663-9883-1798d8d7e74c.png)
> > 
> > 
> > Pa pre bana
> 
> znas li jos u koliko sati kad znas kad je banovan i kad si mu dao acc

Sa telefona je video da će dobiti ban, ušao na moj komp, bacio iteme u neki chest i završio

**Comment by vukstrale** [comment]
> > A Skleper je dobijao brojne nagrade za njegovo nalaženje bugova, jedno vreme smo zajedno tražili razne bugove u pokušaju da dobijemo nagrade od staffa
> 
> a ponesto ste i iskoristili to mi je skleper pricao u call

Ah da vidim taj dokaz? Skleper je inače strašno pouzdan izvor informacija pogotovo sad kad smo se posvadjali

**Comment by galileoba** [comment]
to mi je pricao mnogo prije nego ste se posvadjali isto kao sto je pouzdan izbor info mnogo je nedvolicna osoba pa tako

**Comment by galileoba** [comment]
> > > A Skleper je dobijao brojne nagrade za njegovo nalaženje bugova, jedno vreme smo zajedno tražili razne bugove u pokušaju da dobijemo nagrade od staffa
> > 
> > 
> > a ponesto ste i iskoristili to mi je skleper pricao u call
> 
> Ah da vidim taj dokaz? Skleper je inače strašno pouzdan izvor informacija pogotovo sad kad smo se posvadjali

a da o pljuvanju servera u jednom razdoblju necu da govorim

**Comment by vukstrale** [comment]
> > > > A Skleper je dobijao brojne nagrade za njegovo nalaženje bugova, jedno vreme smo zajedno tražili razne bugove u pokušaju da dobijemo nagrade od staffa
> > > 
> > > 
> > > a ponesto ste i iskoristili to mi je skleper pricao u call
> > 
> > 
> > Ah da vidim taj dokaz? Skleper je inače strašno pouzdan izvor informacija pogotovo sad kad smo se posvadjali
> 
> a da o pljuvanju servera u jednom razdoblju necu da govorim

Ko?

**Comment by vukstrale** [comment]
> 

Dao sam Skleperu da igra na *mom* nalogu? Lolll

**Comment by Attack36** [comment]
Ne znam brate ne ide zivot al ide gas

**Comment by galileoba** [comment]
> > 
> 
> Dao sam Skleperu da igra na _mom_ nalogu? Lolll

pa nije da si priznao ajhahahhah

**Comment by JedemJaja** [comment]
Skleper?

**Comment by konfix** [comment]
> > > > > Jesi blesav e dao sam mu nalog da igra pre nego što je banovan sad sam video i tekst iznad "dokaza"
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/107082292/192115151-675b18b1-7bb5-4663-9883-1798d8d7e74c.png)
> > > 
> > > 
> > > Pa pre bana
> > 
> > 
> > znas li jos u koliko sati kad znas kad je banovan i kad si mu dao acc
> 
> Sa telefona je video da će dobiti ban, ušao na moj komp, bacio iteme u neki chest i završio

Dobio je ban pa je ulazio, zato smo i provalili da delis nalog sa njim jer Litebans izbacuje crveno ime u cetu kad udjes sa IP adrese na kojoj je neko vec banovan. I mogao bi da objasnis ko je onaj Citi koji je terorisao server danima pre toga sa tvoje IP adrese :)

**Comment by konfix** [comment]
> > 
> 
> Dao sam Skleperu da igra na _mom_ nalogu? Lolll

![hoZ94hc](https://user-images.githubusercontent.com/66477781/192120518-4604560d-5e00-45ec-9857-f30d579b351e.png)

??

**Comment by konfix** [comment]
Svakako ne vidim poentu otvaranja ove teme jer je i px sam rekao da nista nece da uradi. To je taj cuveni DAO sistem gde se sprovode licne odluke nekih ljudi u ime zakona (koji ne postuju ni oni koji su ga napisali). I sve tako vec tri meseca otkad se sve ovo pokrenulo, lepa ideja al lose u praksi.

**Comment by PiweeX** [comment]
Vuk je skinut sa pozicije supporta

**Comment by marepleb** [comment]
> Vuk je skinut sa pozicije supporta

#marezasupporta

**Comment by vukstrale** [comment]
Evo i ja da se oglasim. Galileo svi dokazi tu su tačni sem altova. Altove nisam nikad pravio niti ću ih praviti. Opet kažem, to je bila DjoVanijeva greška kad je banao tog lika, koji je pokušao više puta da mi upadne u nalog.


Što se tiče ovoga sa Skleperom, kad je čuo da će da dobije ban, jedno petnaest minute pre bana on je ušao na server, otključao svoje chestove (one koje je mogao, rekao je da nije ni sve stigao da otvori xD) i dao te stvari meni. Uz pomoć DjoVanija, koji mi je onako razgovorno objasnio jedan vrlo minor i maltene beskoristan bug, te iteme sam stavio u chestove tako da ne piše u konzoli da su promenili mesto. 


Svestan sam da ko god bude našao te iteme, biće mu oduzeti i uništeni... Samo ako je dovoljno smotan da kaže da je našao. Nadji i ćuti jedno mesec dva pa onda kreni da ih koristiš. Čisto kao preporuka, ništa obavezno.

Dželatima: verovatno će najlakše biti preko gamemode 3 da ga nadju, i kad ga nadjete snimite i pošaljite meni treba mi za video nemojte zaboraviti.

Štasamjošteodakažem...

Da! Što je rekao piweeex da "ljudi moje sorte idu na druge servera i kroz tri meseca se vraćaju i mole da igraju"
a) tri meseca mi traje ban, do tad neću se vraćati da molim da igram nego bato upalim majnkraft i cepam.
b) šta očekuješ da radim? Volim da igram minecraft, banovan sam sa tvog servera. Ili da ostavim Minecraft potpuno ili da odem na neki drugi server.
