### ISSUE TITLE
Dodati Brewery Plugin

### ISSUE THREAD

**Issue by Raventhedev** [PiweeX/PiweeX#184]
Vec dugo vremena sam razmisljao da napisem ovaj predlog i odlucio sam,naime mislim da bi bilo dobro ubaciti Brewery plugin iz razloga sto bi **Roleplay** bio mnogo bolji jer bi drzave mogle da izvoze razlicita **Alkoholna** pica jedni drugima. Takodje pored toga mislim da bi bilo dobro ubaciti i razne vrste **Kafa** i **Cajeva** koji isto tako mogu da se ubace u sklopu tog Plugina. 

`Neka Roleplay procveta i na ovom serveru !`

**Comment by Attack36** [comment]
Ima li verzija za 1.18.2?

**Comment by Raventhedev** [comment]
Ima nasao sam,poslao sam ti bio na Discord to je najnovija verzija Plugina ona radi od 1.19 pa na nize sto znaci da bi moglo da se ubaci na server.

**Comment by Attack36** [comment]
Posalji ovde

**Comment by Raventhedev** [comment]
https://dev.bukkit.org/projects/brewery/files/3867134

**Comment by Raventhedev** [comment]
evo ovo je najnovija verzija Plugina,naime radi se o verziji v3.1.1

**Comment by Raventhedev** [comment]
podrzava sve verzije od 1.19 do 1.8

**Comment by galileoba** [comment]
u black uuu

**Comment by Raventhedev** [comment]
> u black uuu

?

**Comment by PiweeX** [comment]
Sređuje se, Attack je krenuo da radi na tome na dev serveru i pri kraju je tako da se može očekivati brzo
