### ISSUE TITLE
Dodati RP-Saopstenja 

### ISSUE THREAD

**Issue by Raventhedev** [PiweeX/PiweeX#185]
Radi boljeg Roleplay-a mislim da bi bilo dobro dodati RP-Saopstenja gde bi se sve RP radnje iznosile. Naime svaki RP dogadjaji koji se ne napise tu bi se vodio kao da nije ni postojao. Roleplay bi ovim dodatkom bio vise nego bolji,tok servera bi se poboljsao,jer nebi bilo toga da Vuk objavljuje svima mogucima rat na serveru,takodje nebi bilo moguce da Igor iz 3 kurca doleti do Kine i odjednom tu napravi grad. Ovo nebi bilo moguce zbog Roleplaya,jer kako da to odjednom Engleska koja je u sred evrope zna tacno gde je Azija i sve ostalo. Isto tako mislim da bi se dosta igraca vratilo kao na primer Zlaja_Challenge mozda denzavkk i jos neki ostali. Takodje bi server bio stabilniji u smislu haranja po svetu i zauzimanja svega sto je na vidiku takodje i ubijanje bez razloga (Svako ubistvo bi moralo da se objavi u RP-Saopstenja i onda bi taj koji je ubijen po RP-u morao da pravi novog RP Karaktera,nebi bilo ubijanja nasumicno itd...).

Ovo je ukratko o RP-Saopstenjima naravno imam jos stvari da dodam ali to samo ukoliko bude moralo,takodje ukoliko vidite neke gramaticke greske ispravite me jer brzo pisem.

`Neka Roleplay procveta i na ovom serveru !`

**RP** = Roleplay
**Roleplay**: Simulacija Stvarnog Zivota,ukoliko je neko igrao SA:MP ili FiveM upoznat je sa ovim pojmom.

**Comment by vukstrale** [comment]
To je po mom RPu. A sad koja si država (pitam za druga)?

**Comment by Raventhedev** [comment]
To bas i nije RP jer ne mozes samo tako objaviti rat Vikinzima koji su skroz u Kanadi. Inace sam u Koreji.

**Comment by vukstrale** [comment]
Koreja kažeš? Taman mi usput e

**Comment by Raventhedev** [comment]
> 

Evo opet, ujutru ce svakako biti dodat /war deny tako da neces moci da Abuse komandu

**Comment by galileoba** [comment]
laughing my ass off

**Comment by vukstrale** [comment]
> > 
> 
> Evo opet, ujutru ce svakako biti dodat /war deny tako da neces moci da Abuse komandu

Naravno da neću. Nisam nikad naravno. Ali ću objaviti rat. Pa nek vide svi ko se koga boji kad odbijete

**Comment by Raventhedev** [comment]
> > > 
> > 
> > 
> > Evo opet, ujutru ce svakako biti dodat /war deny tako da neces moci da Abuse komandu
> 
> Naravno da neću. Nisam nikad naravno. Ali ću objaviti rat. Pa nek vide svi ko se koga boji kad odbijete

Ultra Opasan

**Comment by PiweeX** [comment]
uvedeno umesto slike kanala! dobar predlog.

**Comment by konfix** [comment]
🙏 🙏 
<img width="170" alt="1ada3" src="https://user-images.githubusercontent.com/66477781/192122482-54a8012c-c43b-4c34-b08f-199b99ead850.png">

**Comment by PiweeX** [comment]
> 🙏 🙏 <img alt="1ada3" width="170" src="https://user-images.githubusercontent.com/66477781/192122482-54a8012c-c43b-4c34-b08f-199b99ead850.png">

Evo i vas izdaše kao što ste i vi izdali

**Comment by konfix** [comment]
<img width="89" alt="x6dqr" src="https://user-images.githubusercontent.com/66477781/192126077-a40057d9-537d-4834-a8f0-aff271bb775d.png">

sta rec **says** treba da predstavlja?

**Comment by JaSamIgor** [comment]
> Radi boljeg Roleplay-a mislim da bi bilo dobro dodati RP-Saopstenja gde bi se sve RP radnje iznosile. Naime svaki RP dogadjaji koji se ne napise tu bi se vodio kao da nije ni postojao. Roleplay bi ovim dodatkom bio vise nego bolji,tok servera bi se poboljsao,jer nebi bilo toga da Vuk objavljuje svima mogucima rat na serveru,takodje nebi bilo moguce da Igor iz 3 kurca doleti do Kine i odjednom tu napravi grad. Ovo nebi bilo moguce zbog Roleplaya,jer kako da to odjednom Engleska koja je u sred evrope zna tacno gde je Azija i sve ostalo. Isto tako mislim da bi se dosta igraca vratilo kao na primer Zlaja_Challenge mozda denzavkk i jos neki ostali. Takodje bi server bio stabilniji u smislu haranja po svetu i zauzimanja svega sto je na vidiku takodje i ubijanje bez razloga (Svako ubistvo bi moralo da se objavi u RP-Saopstenja i onda bi taj koji je ubijen po RP-u morao da pravi novog RP Karaktera,nebi bilo ubijanja nasumicno itd...).
> 
> Ovo je ukratko o RP-Saopstenjima naravno imam jos stvari da dodam ali to samo ukoliko bude moralo,takodje ukoliko vidite neke gramaticke greske ispravite me jer brzo pisem.
> 
> `Neka Roleplay procveta i na ovom serveru !`
> 
> **RP** = Roleplay **Roleplay**: Simulacija Stvarnog Zivota,ukoliko je neko igrao SA:MP ili FiveM upoznat je sa ovim pojmom.

jeste ja sam odjednom došao u Kinu i odlučio da uzmem grad
![discord1](https://user-images.githubusercontent.com/107154813/192130671-2e73948c-d8f3-4d24-a35b-1ff171771725.PNG)
i takođe mislim da su Britanci znali gde je Azija u 19 veku?
ali ono za kanale dobra ideja

**Comment by Raventhedev** [comment]
> > Radi boljeg Roleplay-a mislim da bi bilo dobro dodati RP-Saopstenja gde bi se sve RP radnje iznosile. Naime svaki RP dogadjaji koji se ne napise tu bi se vodio kao da nije ni postojao. Roleplay bi ovim dodatkom bio vise nego bolji,tok servera bi se poboljsao,jer nebi bilo toga da Vuk objavljuje svima mogucima rat na serveru,takodje nebi bilo moguce da Igor iz 3 kurca doleti do Kine i odjednom tu napravi grad. Ovo nebi bilo moguce zbog Roleplaya,jer kako da to odjednom Engleska koja je u sred evrope zna tacno gde je Azija i sve ostalo. Isto tako mislim da bi se dosta igraca vratilo kao na primer Zlaja_Challenge mozda denzavkk i jos neki ostali. Takodje bi server bio stabilniji u smislu haranja po svetu i zauzimanja svega sto je na vidiku takodje i ubijanje bez razloga (Svako ubistvo bi moralo da se objavi u RP-Saopstenja i onda bi taj koji je ubijen po RP-u morao da pravi novog RP Karaktera,nebi bilo ubijanja nasumicno itd...).
> > 
> > Ovo je ukratko o RP-Saopstenjima naravno imam jos stvari da dodam ali to samo ukoliko bude moralo,takodje ukoliko vidite neke gramaticke greske ispravite me jer brzo pisem.
> > 
> > `Neka Roleplay procveta i na ovom serveru !`
> > 
> > **RP** = Roleplay **Roleplay**: Simulacija Stvarnog Zivota,ukoliko je neko igrao SA:MP ili FiveM upoznat je sa ovim pojmom.
> 
> jeste ja sam odjednom došao u Kinu i odlučio da uzmem grad
> ![discord1](https://user-images.githubusercontent.com/107154813/192130671-2e73948c-d8f3-4d24-a35b-1ff171771725.PNG)
> i takođe mislim da su Britanci znali gde je Azija u 19 veku?
> ali ono za kanale dobra ideja 

Da jesu znali u 18. Veku ali ti po RP-u na Hogu ne mozes da znas, nisi pokrenuo nikakvu Ekspediciju, plus i da tvoja Ekspedicija pronadje Aziju po RP-u kako oni mogu da znaju da je to Azija? Gledaj to malo kao ono kada su Evropljani u Novom Veku poceli da traze pomorski Put do Indije pa je Kristofer Kolumbo nasao Ameriku ali nije znao da je to Amerika pa je nazvao Indija, tek posle nekoliko godina Amerigo Vesspuci je shvatio da to nije Indija i novi kontinent nazvao Amerika po svom imenu. Sto znaci smisli i ti neki takav RP a ne odjednom da dodjes i napravis Grad i kolko ja znam Kolonije nisu dozvoljene.

**Comment by JaSamIgor** [comment]
> > > Radi boljeg Roleplay-a mislim da bi bilo dobro dodati RP-Saopstenja gde bi se sve RP radnje iznosile. Naime svaki RP dogadjaji koji se ne napise tu bi se vodio kao da nije ni postojao. Roleplay bi ovim dodatkom bio vise nego bolji,tok servera bi se poboljsao,jer nebi bilo toga da Vuk objavljuje svima mogucima rat na serveru,takodje nebi bilo moguce da Igor iz 3 kurca doleti do Kine i odjednom tu napravi grad. Ovo nebi bilo moguce zbog Roleplaya,jer kako da to odjednom Engleska koja je u sred evrope zna tacno gde je Azija i sve ostalo. Isto tako mislim da bi se dosta igraca vratilo kao na primer Zlaja_Challenge mozda denzavkk i jos neki ostali. Takodje bi server bio stabilniji u smislu haranja po svetu i zauzimanja svega sto je na vidiku takodje i ubijanje bez razloga (Svako ubistvo bi moralo da se objavi u RP-Saopstenja i onda bi taj koji je ubijen po RP-u morao da pravi novog RP Karaktera,nebi bilo ubijanja nasumicno itd...).
> > > Ovo je ukratko o RP-Saopstenjima naravno imam jos stvari da dodam ali to samo ukoliko bude moralo,takodje ukoliko vidite neke gramaticke greske ispravite me jer brzo pisem.
> > > `Neka Roleplay procveta i na ovom serveru !`
> > > **RP** = Roleplay **Roleplay**: Simulacija Stvarnog Zivota,ukoliko je neko igrao SA:MP ili FiveM upoznat je sa ovim pojmom.
> > 
> > 
> > jeste ja sam odjednom došao u Kinu i odlučio da uzmem grad
> > ![discord1](https://user-images.githubusercontent.com/107154813/192130671-2e73948c-d8f3-4d24-a35b-1ff171771725.PNG)
> > i takođe mislim da su Britanci znali gde je Azija u 19 veku?
> > ali ono za kanale dobra ideja
> 
> Da jesu znali u 18. Veku ali ti po RP-u na Hogu ne mozes da znas, nisi pokrenuo nikakvu Ekspediciju, plus i da tvoja Ekspedicija pronadje Aziju po RP-u kako oni mogu da znaju da je to Azija? Gledaj to malo kao ono kada su Evropljani u Novom Veku poceli da traze pomorski Put do Indije pa je Kristofer Kolumbo nasao Ameriku ali nije znao da je to Amerika pa je nazvao Indija, tek posle nekoliko godina Amerigo Vesspuci je shvatio da to nije Indija i novi kontinent nazvao Amerika po svom imenu. Sto znaci smisli i ti neki takav RP a ne odjednom da dodjes i napravis Grad i kolko ja znam Kolonije nisu dozvoljene.

brate grad je oduzet a ekspedicije su bile jos nakon mongolskog pohoda na englesku koji je bio u martu

**Comment by JaSamIgor** [comment]
nemoj da pricas ako ne znas pricu pls

**Comment by Raventhedev** [comment]
> nemoj da pricas ako ne znas pricu pls

Znam da tvoja drzava itekako nema Roleplay

**Comment by JaSamIgor** [comment]
> > nemoj da pricas ako ne znas pricu pls
> 
> Znam da tvoja drzava itekako nema Roleplay

ako je nesto nejasno u vezi Britanskog roleplaya javi se na discord
