### ISSUE TITLE
Kakva je ovo war komanda? Vise nista nema smisla.......

### ISSUE THREAD

**Issue by T1GAR** [PiweeX/PiweeX#186]
![image](https://user-images.githubusercontent.com/107375896/192119359-315a2b6b-3e47-4d6e-a1e6-d2a2afebadba.png)

Znaci neko samo moze ne uc na server i rat nikada nece niti biti uz to da je razlog zadovoljen?
dobra vam ova war komanda kada ratova nece niti biti.......

i kada se dobije valjani razlog za rat strana koja se napada nikada nece doc online i vi ovo zoveze rat. dobar vam rat.
Isto tako kakve logike ima da neko odbije rat samo zato jer eto ovi su jaci pa nece bit rata, dobro da je Ukrajina mogla odbit rat od Rusije?????. Ova war komada nema nikakve veze sa vezom sto se tice rl i rpa. Koliko god dobar razlog bio ovi sta brane nece doc.
Ali stvarno kakav god razlog da ste dali oni ce odbit jer "nije dovoljan razlog". Sta ako se neka država želi proširiti? objavi rat susjednoj i ona kaze necu u rat jer nije dobar razlog?... Pa jel zelite da server bude zabavan ili sta?
Molim vas u svoje i u ime drugih igraca kojima je ovo veliki problem da stvarno napravite neka nova pravila sto se tice /war jer ovo je stvarno za nista...

**Comment by yamizvaniuchicha** [comment]
ako cemo iskreno slazem se u potpunosti, normalno je biti neutralna drzava al da se zna da se neutralna drzava kao svajcarska u svetskim ratovima, al sta zar ne mozemo proglasiti rat velikoj opasnoj mongoliji jer oni ne zele, toliko razloga sam naveo napisao i rp pricu a isti ti pod znacima neutralni mongoli ce sutra pokusati osvojiti neku malu drzavu, glupost…

**Comment by T1GAR** [comment]
> ako cemo iskreno slazem se u potpunosti, normalno je biti neutralna drzava al da se zna da se neutralna drzava kao svajcarska u svetskim ratovima, al sta zar ne mozemo proglasiti rat velikoj opasnoj mongoliji jer oni ne zele, toliko razloga sam naveo napisao i rp pricu a isti ti pod znacima neutralni mongoli ce sutra pokusati osvojiti neku malu drzavu, glupost…

doslovno. Koliko god dobar razlog ti dao oni ce odbiti...... ovakav rat nema smisla. Neko ce samo doc rec odbijam rat i nista. Mislim kada se u povijesti moglo odbit rat?

**Comment by T1GAR** [comment]
> ako cemo iskreno slazem se u potpunosti, normalno je biti neutralna drzava al da se zna da se neutralna drzava kao svajcarska u svetskim ratovima, al sta zar ne mozemo proglasiti rat velikoj opasnoj mongoliji jer oni ne zele, toliko razloga sam naveo napisao i rp pricu a isti ti pod znacima neutralni mongoli ce sutra pokusati osvojiti neku malu drzavu, glupost…

Isto tako Antartik po ovome trenutno ne moze objavit rat nikome jer se nalaze na drugom kontinentu i svi odbijaju jer im je razlog "aa pa vi ste na drugom kontinentu" ono nije kao da sutra nece bit???

**Comment by Attack36** [comment]
War komanda ima problem da ova strana ne moze odbiti, i ljudi to eksplojtaju za trolanje te bacanje roleplaya u kantu. Puna je i glitcheva. Px treba je zaustaviti i playtestati i bugfiksati 10 dana i onda da pusti.

**Comment by DaniloU2008** [comment]
i ja se slažem. Jugoslavija nije mogla da bira bombardovanje niko nije pitao za pristup.
Ovo je rp (simulacija stvarnog života).
Zbog rata Antartik i Vikinzi ne mogu da trastam ljude u KrSHS. Što tako?

**Comment by DaniloU2008** [comment]
Bolje da skine onda /war komandu dok ne funkcioniše kako treba. Sorry al tako je.

**Comment by JedemJaja** [comment]
Skleper?

**Comment by PiweeX** [comment]
Gledate na to uga buga načinom, dakle LOGIČNO je i svi znamo da jebena država u RL ne može odbiti rat jer onda nikad nebi bilo ratova ali na serveru je svrha roleplay, da li je roleplay da budete 3h na serveru, napravite claim i proglasite rat sa 13 država? Tu nema roleplaya, svrha je zabava kroz roleplay, ne totalno uništenje servera. UGA BUGA zamisli svi znamo da Jugoslavija nije mogla da odbije rat ali ovo je RPG

**Comment by PiweeX** [comment]
> War komanda ima problem da ova strana ne moze odbiti, i ljudi to eksplojtaju za trolanje te bacanje roleplaya u kantu. Puna je i glitcheva. Px treba je zaustaviti i playtestati i bugfiksati 10 dana i onda da pusti.

upravo to, mora da postoji mogućnost da strana odbija, podešeno je i čekamo restart u 7 pa će proraditi

**Comment by PiweeX** [comment]
Dakle nemojte se praviti da ste pametni kad niste, poštujem vaša mišljenja ali razmislite malo

ako postoji opcija 1)

da države ratuju po RPu, da 1 dnevno bude 1 veliki rat neke države i da to kao i u predhodnim ratovima od pre mesec dana dođe cela jedna zemlja od 30 ljudi na 2 savezničke zemlje od 50 ljudi, jel to bolje za server nego da se svaki dan objavljuju ratovi i da se ne zna ko pije ko plaća

**Comment by PiweeX** [comment]
> Dakle nemojte se praviti da ste pametni kad niste, poštujem vaša mišljenja ali razmislite malo
> 
> ako postoji opcija 1)
> 
> da države ratuju po RPu, da 1 dnevno bude 1 veliki rat neke države i da to kao i u predhodnim ratovima od pre mesec dana dođe cela jedna zemlja od 30 ljudi na 2 savezničke zemlje od 50 ljudi, jel to bolje za server nego da se svaki dan objavljuju ratovi i da se ne zna ko pije ko plaća

i da onda ujedno pored toga što se ne zna ko pije ko plaća na kraju niko ni ne dolazi na te jebene ratove, nemojte se praviti pametni, godinama sam u ovome i pravio sam evente i znam kako oni funkcionišu u srž, prvobitno ne smeju biti redovni nego masivni, neće to ako su eventi stalno aktivirati server ali će to da se napravi manje evenata a da su dobri do srži i masivni zapravo mnogo poboljšati server

**Comment by Raventhedev** [comment]
E ovako, war komanda treba da se izbaci  sve dok se ne sredi a u medju vremenu da se ubaci /nations koji je u sklopu Land plugins. Uz pomoc /nations ljudi ce moci da prave Nacije i da trustacu svoje gradove i naprave Celovitu drzavu, uz pomoc /nations takodje ce se lakse odvijati Ratovi jer nece morati da se objavljuje rat jednom claim vec ce moci celoj Naciji. Sto znaci da ce svi Claimovi koji pripadaju toj Naciji biti umesani u rat, isto tako ce biti lepse videti na mapi claimove u boji npr. Crvenoj,Crnoj itd. I samim tim ce se znati koji claim pripada kojoj Naciji!

**Comment by PiweeX** [comment]
> 

Slažem se, nations je uvedena od ujutru ponovo

**Comment by vukstrale** [comment]
> > Dakle nemojte se praviti da ste pametni kad niste, poštujem vaša mišljenja ali razmislite malo
> > ako postoji opcija 1)
> > da države ratuju po RPu, da 1 dnevno bude 1 veliki rat neke države i da to kao i u predhodnim ratovima od pre mesec dana dođe cela jedna zemlja od 30 ljudi na 2 savezničke zemlje od 50 ljudi, jel to bolje za server nego da se svaki dan objavljuju ratovi i da se ne zna ko pije ko plaća
> 
> i da onda ujedno pored toga što se ne zna ko pije ko plaća na kraju niko ni ne dolazi na te jebene ratove, nemojte se praviti pametni, godinama sam u ovome i pravio sam evente i znam kako oni funkcionišu u srž, prvobitno ne smeju biti redovni nego masivni, neće to ako su eventi stalno aktivirati server ali će to da se napravi manje evenata a da su dobri do srži i masivni zapravo mnogo poboljšati server

Slažem se sa tim u potpunosti, ALI war komanda je puna bugova, potreban je playtest. Komanda postoji dva dana našao sam preko 13 bugova dok sam u isto vreme igrao Assasin's Creed: Black Flag (najbolji AC po meni realno kida). Da je Skleper sa mnom bilo bi i deset puta brže, on što ume da nadje bug u klikeru niko ne ume. Ali svakako potrebno je još testiranja.

**Comment by JedemJaja** [comment]
> > > Dakle nemojte se praviti da ste pametni kad niste, poštujem vaša mišljenja ali razmislite malo
> > > ako postoji opcija 1)
> > > da države ratuju po RPu, da 1 dnevno bude 1 veliki rat neke države i da to kao i u predhodnim ratovima od pre mesec dana dođe cela jedna zemlja od 30 ljudi na 2 savezničke zemlje od 50 ljudi, jel to bolje za server nego da se svaki dan objavljuju ratovi i da se ne zna ko pije ko plaća
> > 
> > 
> > i da onda ujedno pored toga što se ne zna ko pije ko plaća na kraju niko ni ne dolazi na te jebene ratove, nemojte se praviti pametni, godinama sam u ovome i pravio sam evente i znam kako oni funkcionišu u srž, prvobitno ne smeju biti redovni nego masivni, neće to ako su eventi stalno aktivirati server ali će to da se napravi manje evenata a da su dobri do srži i masivni zapravo mnogo poboljšati server
> 
> Slažem se sa tim u potpunosti, ALI war komanda je puna bugova, potreban je playtest. Komanda postoji dva dana našao sam preko 13 bugova dok sam u isto vreme igrao Assasin's Creed: Black Flag (najbolji AC po meni realno kida). Da je Skleper sa mnom bilo bi i deset puta brže, on što ume da nadje bug u klikeru niko ne ume. Ali svakako potrebno je još testiranja.

Skleper?

**Comment by Coplek** [comment]
xD pa jucer smo navecer 5 vinlandjana bili online

**Comment by Coplek** [comment]
svejedno nam je jesmo na srw il ne kad je zbugana cmd i kad me ubije napadac bod ide meni

**Comment by Coplek** [comment]
A rat koji je objavljen prije cmd fixa ne moze se odbit

**Comment by DzingisKan** [comment]
> svejedno nam je jesmo na srw il ne kad je zbugana cmd i kad me ubije napadac bod ide meni

Pogledaj jesi li u claimu države koja ti je objavila rat.

Popravljeno je da se može odbit rat.

Ako bude zloupotrebljavana komanda da nema više veze s roleplayom nego čudnim fetišima VukTheGreata slobodno prijavi u UN.

**Comment by NemanjaRusija2** [comment]
> > svejedno nam je jesmo na srw il ne kad je zbugana cmd i kad me ubije napadac bod ide meni
> 
> Pogledaj jesi li u claimu države koja ti je objavila rat.
> 
> Popravljeno je da se može odbit rat.
> 
> Ako bude zloupotrebljavana komanda da nema više veze s roleplayom nego čudnim fetišima VukTheGreata slobodno prijavi u UN.

Njega ne blokas, mene blokas.

**Comment by DzingisKan** [comment]
> > > svejedno nam je jesmo na srw il ne kad je zbugana cmd i kad me ubije napadac bod ide meni
> > 
> > 
> > Pogledaj jesi li u claimu države koja ti je objavila rat.
> > Popravljeno je da se može odbit rat.
> > Ako bude zloupotrebljavana komanda da nema više veze s roleplayom nego čudnim fetišima VukTheGreata slobodno prijavi u UN.
> 
> Njega ne blokas, mene blokas.

Pozdrav za fana Nemanju Rusiju

**Comment by Coplek** [comment]
> > svejedno nam je jesmo na srw il ne kad je zbugana cmd i kad me ubije napadac bod ide meni
> 
> Pogledaj jesi li u claimu države koja ti je objavila rat.
> 
> Popravljeno je da se može odbit rat.
> 
> Ako bude zloupotrebljavana komanda da nema više veze s roleplayom nego čudnim fetišima VukTheGreata slobodno prijavi u UN.

Da ali rat koji vec traje se ne moze ako se ne varam jucer je xdjomla pokuso

**Comment by NemanjaRusija2** [comment]
> > > > svejedno nam je jesmo na srw il ne kad je zbugana cmd i kad me ubije napadac bod ide meni
> > > 
> > > 
> > > Pogledaj jesi li u claimu države koja ti je objavila rat.
> > > Popravljeno je da se može odbit rat.
> > > Ako bude zloupotrebljavana komanda da nema više veze s roleplayom nego čudnim fetišima VukTheGreata slobodno prijavi u UN.
> > 
> > 
> > Njega ne blokas, mene blokas.
> 
> Pozdrav za fana Nemanju Rusiju

Bojiš se vuka pa ga ne smiješ blokat. Priznaj

**Comment by vukstrale** [comment]
> > svejedno nam je jesmo na srw il ne kad je zbugana cmd i kad me ubije napadac bod ide meni
> 
> Pogledaj jesi li u claimu države koja ti je objavila rat.
> 
> Popravljeno je da se može odbit rat.
> 
> Ako bude zloupotrebljavana komanda da nema više veze s roleplayom nego čudnim fetišima VukTheGreata slobodno prijavi u UN.

Zašto se zanimaš za moje fetiše bebo (⁠~⁠￣⁠³⁠￣⁠)⁠~

**Comment by PiweeX** [comment]
Popravljeno ✅
