### ISSUE TITLE
Roleplay Liga Workspace - Changelog (MNB - Minecraft na Balkanu udruženje građana)

### ISSUE THREAD

**Issue by Attack36** [PiweeX/PiweeX#188]
Ovo će biti mjesto gdje ćemo davati updejtove oko **Roleplay Lige** te glasanja na nove stvari i tako to. Uglavnom da angažiramo community koji je navikao na Github.

Ovo će voditi:

**_CrossFire i Attack36_** za sada, možda dodamo još ovisi kako se Staff tim bude povećavao.

**Comment by stipefire** [comment]
𝗠𝗼𝗻𝗴𝗼𝗹𝗶𝗷𝗮 VS 𝗞𝗼𝗿𝗲𝗷𝗮
Rat se sprema! Mongolski arbani se okupljalju blizu korejske granice, dok Toyotomi klan zove sve muškarce koji su dovoljno stari za rat!

𝐙𝐚š𝐭𝐨?
Nakon poraza Genghis Khana u "Ratu Svih", njegov nasljednik, Živuci sin Toluja Mongke Khan bio je željan krvi. Od dana gubitka skupljao je moć i čekao priliku za napad. Nakon spajanja Osmanskog Carstva sa Mongolijom, skupi je dovoljno ljudi i oružija kako bi pokrenuo invaziju. Sada, u desetom mjesecu kraju monsuna dobio je i okvir u kojem će mu uvjeti odgovarati, jer ionako je tlo još mokro, otežati će koreancima građenje utvrda, te će nešto baruta biti mokro.

Ali Korjea ne spava. Toyotomi Hidenaga se trudio kako bi potaknuo rast populacije i vojske, te je osnovao više gradova kako bi dizao moć. Ali nije očekivao da će Mongke Khan napasti ovoliko rano, zbog nedavnog monsuna tlo je još vlažno.

Kada i Gdje?
Korejski izvori govore kako će se prvi rat odrazi već ovu nedljelju (9.10), ali da će prvi napadi vec krenuti u četvrtak. Prva bitka će se vjerovatno održati kod Thailanda,
jer taj dio je već dugo vremena bio trn u oku Mongke-a iz razloga što sijeće Mongolski teritori na pola.

Tko?
Korejski Car odlučio je da neće pozvati saveznike kao zadnji put, jer smatra da taj potez "Nije časan". Pošto mu fali vojske dozvolio je ograničeni broj volontera iz saveznih država. Pored Mongolskih i Korejskih vođa te njihove vojske, stići će i interesantne osobe poput:

Hoeth
Vođa pacifickog diktata , sposoban taktičar i dostojan borac. Dugo nije izlašao na bojno polje, no nakon izdaje brata, odluke mu postaju sve više i više nepredvidljive.

Thor
Bog munje u ljudskom obliku, dolazi sa dalekog sjevera zbog glasina da Mongolija je Vinland, njegov dom, Prva meta kada krene Mongolski pohod na europu.

Sigmund Holgersen
Nakon što je ćuo da vikinska braća sa druge strane Atlantika idu volonterski u boj, odlučio je uz pomoć Pacifičkog Diktata za transport krenuti prema Koreji.
![image_2022-10-06_213140865](https://user-images.githubusercontent.com/86807500/194402425-ed826ed5-b871-41c2-a695-3863ddb226ca.png)

**Comment by PiweeX** [comment]
very good

**Comment by PiweeX** [comment]
Roleplay liga ovih dana dobija svog tiket bota kao što i LN poseduje, upravo sam kreirao na panelu i treba samo podesiti. Pored toga Hogo Studios discord danas dobija još 1 tiket bota za (za servise koje vraćamo samo na tom Discord-u) i za licenciranje plugina kako bi se sprečilo leakovanje (već je bilo leakova naših plugina na ilegalnim sajtovima)

**Comment by PiweeX** [comment]
ROLEPLAY LIGA se arhivirala, sve je po dogovoru prebačeno tačnije vraćeno na Ligu naroda

više o tome ima u novijim issueovima od ovoga. 

Stoga i ovaj issue će biti zatvoren
