### ISSUE TITLE
Naga Koplje

### ISSUE THREAD

**Issue by Siu804** [PiweeX/PiweeX#191]
Ovako Naga koplje je pre skidalo 22dmg a sada oko 4dmg barem tako pise zato zelim da se poveća barem na 7ndmg opet glupo je da Vuk ima jedini 22dmg a ostali manje ako on ima 22dmg nama povecajte na 7
 dmg opet custom je oruzje i ne dobija se vise mislim sa 22dmg na 4 je mnogo glupo

**Comment by ConeBe** [comment]
Pa nerfalo se jer je bilo OP oruđe, svakako ako se poveća opet će biti OP jer ti treba sreća da nađeš ako još postoji, tako da uvek će biti OP

**Comment by Siu804** [comment]
Postoji imam ja al brt sa 22dmg na 4 mogli su barem na 7 da ostave

**Comment by Siu804** [comment]
Ako vuk ima vec 22dmg

**Comment by ConeBe** [comment]
Pa mislim glupo je da neko ima veći dmg a svi ostali manje, najbolje da se poveća fazon na 10 dmg, dosta stvari se nerflao, poput Olujnog Mača koji je bio najjača stvar u igri.

**Comment by Siu804** [comment]
Pa glupo je zato Vuk ima od 22dmg a mi ostali po 4dmg nek stave brt na 7 da imaju svi pa i Vuk

**Comment by vukstrale** [comment]
U bližoj budućnosti dolazi veliki rebalans custom itema. Izmene će uključivati skoro sve custom iteme (isključujući iteme iz runic kita ako se ne varam)

**Comment by PavlePana** [comment]
Slazem se
