### ISSUE TITLE
PX KAKO TE NIJE SRAMOTA???

### ISSUE THREAD

**Issue by Zav1637** [PiweeX/PiweeX#192]
Evo px daje meni adresu njegovu:Petra Antonijevića 8 Lazarevac i kaze da dodjem tamo ja sam relativno blizu samo mi nije jasno sta hoce i zasto da dodjem zasto je on debil da zove banovanog igraca na kucnu adresu. Px od mene jedino kafu 200 grama mozes da dobijes za goste.

**Comment by DzingisKan738** [comment]
Nije PiweeeX taj koga bi se trebo bojat.... Pazi se strašnog Gorostasa kojeg nazivaju Čorba. Čuješ li igdi harmoniku znaš da je on u blizini I TADA BEŽI!!!!

**Comment by PiweeX** [comment]
zovem te da ti polomim pičku jer pretiš, neću te sigurno ugostiti. Vidimo se

**Comment by Attack36** [comment]
Hvala na px-ovoj adresi! Odo da mu šaljem belgijske vafle

**Comment by marepleb** [comment]
> zovem te da ti polomim pičku jer pretiš, neću te sigurno ugostiti. Vidimo se

mozes mene da ugostis tu sam za 20?

**Comment by konfix** [comment]
hahahahaha kakva komedija

**Comment by galileoba** [comment]
> hahahahaha kakva komedija

Opet provociras⁉️⁉️⁉️⁉️

**Comment by konfix** [comment]
> > hahahahaha kakva komedija
> 
> Opet provociras⁉️⁉️⁉️⁉️

jace je od mene

**Comment by PiweeX** [comment]
> Hvala na px-ovoj adresi! Odo da mu šaljem belgijske vafle

te volim! hehe

**Comment by Viktor023023** [comment]
Px sta dobijam za votanje

**Comment by vukstrale** [comment]
Ha! Ja ovo znam odranije, koji flex sa moje strane

**Comment by PiweeX** [comment]
Ćeraj
