### ISSUE TITLE
UHC natrag na 1.7

### ISSUE THREAD

**Issue by Attack36** [PiweeX/PiweeX#193]
Nema nista da se kaze, bugovi, glitchevi, lag i og igraci odlaze (npr. The Boss Filip)

Neka se vrati na 1.7.10 da nam svima bude lakse, ili neka px playtesta i popravi 1.8.9

UHC ce ovako umrijeti

Rekao je "vi ste ovo trazili" sada izglasajte i pokazite da i ovo zapravo trazite. 

To je to od mene neka svi odluce.

**Comment by T1GAR** [comment]
zasto je MislavX banan na 1h zato jer nije dao kod za anydesk? Lik je legit. Igrao je vec UHC tu. Bolji je i od Gothie

**Comment by Attack36** [comment]
> zasto je MislavX banan na 1h zato jer nije dao kod za anydesk? Lik je legit. Igrao je vec UHC tu. Bolji je i od Gothie

Nije dao anydesk, kako bi ja trebao znati, ja radim svoj posao

**Comment by T1GAR** [comment]
> > zasto je MislavX banan na 1h zato jer nije dao kod za anydesk? Lik je legit. Igrao je vec UHC tu. Bolji je i od Gothie
> 
> Nije dao anydesk, kako bi ja trebao znati, ja radim svoj posao

ali sta je radio da bi trebao dat ikome anydoesk? lik je igrao UHC kao i drugi?

**Comment by Attack36** [comment]
> > > zasto je MislavX banan na 1h zato jer nije dao kod za anydesk? Lik je legit. Igrao je vec UHC tu. Bolji je i od Gothie
> > 
> > 
> > Nije dao anydesk, kako bi ja trebao znati, ja radim svoj posao
> 
> ali sta je radio da bi trebao dat ikome anydoesk? lik je igrao UHC kao i drugi?

Bio je sumnjiv, imao je puno vise dijamanata od ikog drugog. Ja kad nisam bio dželat sam bio anydeskan za to
Poanta je nek ima spreman anydesk iduci put ne znam kako je tesko u gugl download anydesk. Uz to je rekao nesto fazon "neću" ravno prije tak da

**Comment by T1GAR** [comment]
> > > > zasto je MislavX banan na 1h zato jer nije dao kod za anydesk? Lik je legit. Igrao je vec UHC tu. Bolji je i od Gothie
> > > 
> > > 
> > > Nije dao anydesk, kako bi ja trebao znati, ja radim svoj posao
> > 
> > 
> > ali sta je radio da bi trebao dat ikome anydoesk? lik je igrao UHC kao i drugi?
> 
> Bio je sumnjiv, imao je puno vise dijamanata od ikog drugog. Ja kad nisam bio dželat sam bio anydeskan za to Poanta je nek ima spreman anydesk iduci put ne znam kako je tesko u gugl download anydesk. Uz to je rekao nesto fazon "neću" ravno prije tak da

nebi niti ja dao da mi neko prcka po pcu zbog igrice..... Lik je legit. Igrao je i prije kada je bilo TO3 ofc winali su sa razlogom. Naravno da je imao najvise kao sto i uvijek ima. Lik ovo nolifea i zna sta radi. Sada je uopce pitanje ako ce se vratit ili ne. To sto je neko bolji od vecine ne znaci da cheata ili ista takvo

**Comment by PiweeX** [comment]
Problemi rešeni
