### ISSUE TITLE
Cijena Wheata

### ISSUE THREAD

**Issue by Attack36** [PiweeX/PiweeX#194]
U SSRu smo već izglasali da se stavi na github pa ću iznijeti razloge zasto da se cijena wheata sa 38$ na 50$:

1. Cijena coala i odrzavanje traktora
2. Vise zarade jer igracima je polako dosta
3. Stabilizacija ekonomije
4. Stabilizacija trzista custom itema

Uz to da dodamo da se wheat prodaje po stack.

**Comment by NemanjaRusija** [comment]
> U SSRu smo već izglasali da se stavi na github pa ću iznijeti razloge zasto da se cijena wheata sa 38$ na 50$:
> 
> 1. Cijena coala i odrzavanje traktora
> 2. Vise zarade jer igracima je polako dosta
> 3. Stabilizacija ekonomije
> 4. Stabilizacija trzista custom itema
> 
> Uz to da dodamo da se wheat prodaje po stack.

Ekonomija na hogu treba biti stabilna. Ako bi se povećala svi bi radili poljoprivredu. Valjda još hog treba da bude u tom nekom hard modu. Kao u rl. Treba razmišljati da će se dodati za drva i za zlato. Trebalo bi se to sačekati pa vidjeti. A što se tiče custom itema, jeste nekad se pretjera cijena. Trebalo bi se lista napravit custom itema. Pa napisati od najskupljeg itema do najjeftinijeg.

Toliko o meni.

**Comment by PiweeX** [comment]
Ovo je rešeno, samo još da krene sa radom black market koji su Djovani i Djomla napravili
