### ISSUE TITLE
Peticija za izbacivanje "Uchiha_Yami" iz drzave "Asirske Imperije".

### ISSUE THREAD

**Issue by mqtko** [PiweeX/PiweeX#198]
Pozdrav, zelim da pokrenem peticiju za izbacivanje Glavnog Vodje "Uchiha_Yami" iz svoje drzave "Asirske Imperije" 
zato sto je predugo u hagu i igraci iz drzava ne mogu normalno da funkcionisu.
 Napisite svoj glas ili svoje misljenje u komentaru ispod. Hvala Lepo - poorMATKO

**Comment by galileoba** [comment]
slazem se u trostunosti

**Comment by ConeBe** [comment]
U potpunosti, treba vam novi imperator koji će lakše pomagati drugima i vodite svoje ljude

**Comment by yamizvaniuchicha** [comment]
popusite mi bre kurac svi

**Comment by BokiJeIsus21** [comment]
Iskreno da reknem ne. Ono jeste da je on u Hagu ali i dalje smo u voice chatovima na Discordu. S njegovim "leadershipom" smo uspjeli da povecamo ne samo drzavu a i teritorij. Zapoceli smo jedan veliki project a on nam je govorio kako da napravimo cak nam je i nacrtao jednom. Additional info> vi svi pripadnici sekretarijata volvogradskog tribunala mozete da mi popusite ***** (No hate}

**Comment by yamizvaniuchicha** [comment]
> 
toooo bokii respect a ovi stranci sto glasaju njihov glas ni ne znaci, kada bi se svi u drzavi slozili da se promeni imperator ja bih predao moj presti drugome ali matko je samo gej on jedini hoce

**Comment by Mega-Gamer007** [comment]
Matko moze da objavi ovo ali to moraju da glasaju ljudi iz nase drzave nemogu to da glasaju neki ljudi iz drugih drzava koji bi samo da se otarase yami

**Comment by Mega-Gamer007** [comment]
> Pozdrav, zelim da pokrenem peticiju za izbacivanje Glavnog Vodje "Uchiha_Yami" iz svoje drzave "Asirske Imperije" zato sto je predugo u hagu i igraci iz drzava ne mogu normalno da funkcionisu. Napisite svoj glas ili svoje misljenje u komentaru ispod. Hvala Lepo - poorMATKO

👎

**Comment by yamizvaniuchicha** [comment]
> 

i to isto posebno mene boli kurac sta misli cone iz ruskog carstva iz juzne amerike ili galilea admina atlasa

**Comment by MikiRekt** [comment]
au jebem vas zajebava se lik

**Comment by MrKnedla** [comment]
bro moj samo dodes i izbacis ga u cemu je problem? (kazem iz iskustva)
