### ISSUE TITLE
Peticija za izbacivanje POOR_Matka iz Asirskog carstva i ally- drzava

### ISSUE THREAD

**Issue by BokiJeIsus21** [PiweeX/PiweeX#199]
Yami>Galileo,POOR_Matko

**Comment by Mega-Gamer007** [comment]
Slazem se da se izbaci

**Comment by yamizvaniuchicha** [comment]
ljudi zajebavao se matko

**Comment by BokiJeIsus21** [comment]
> ljudi zajebavao se matko

Bmk

**Comment by NemanjaRusija2** [comment]
Ne otvarajte github za ove stvari nemojte biti toliki bolidi

**Comment by BokiJeIsus21** [comment]
> Ne otvarajte github za ove stvari nemojte biti toliki bolidi

https://www.youtube.com/watch?v=8xVR368y4OA&t=69s
