### ISSUE TITLE
Peticija da admini vrate stvari od igraca koji su dosli sa atlasa da kradu stvari iz banata (danasnja vlahija) 

### ISSUE THREAD

**Issue by Mega-Gamer007** [PiweeX/PiweeX#200]
Posto neznaju gde su stvari od 2 igraca koja su krala stvari iz banata ja bih da oni nekako dupliraju iteme ili tako nesto i da se vrate beacon enchenting table moj mac bow i sekira i sve enchenting knjige koje su ukradene

**Comment by yamizvaniuchicha** [comment]
iskreno brate ukradeno je svasta nije fora da dolaze igraci sa atlasa da mi grifaju drzavu

**Comment by PiweeX** [comment]
Vraćeno je ovo koliko znam, uglavnom ako vam treba pomoć otvorite tiket na Ligi naroda ili oko claima na Roleplay ligi biće mnogo brže
