### ISSUE TITLE
Ono kad vlasnik hoga ima mentalni poremecaj...

### ISSUE THREAD

**Issue by Zav1637** [PiweeX/PiweeX#201]
![IMG_20221002_205702](https://user-images.githubusercontent.com/108089196/193471338-3773e35b-d0c7-4e07-aea7-00042801a88f.jpg)

**Comment by PiweeX** [comment]
za koliko ti je deda jutara zemlje prodao veru

**Comment by Zav1637** [comment]
Pitaj kevu

**Comment by JedemJaja** [comment]
Krindz

**Comment by PiweeX** [comment]
Ćeraj
