### ISSUE TITLE
Ideje za ekonomiju HogRealmsa

### ISSUE THREAD

**Issue by djonmla** [PiweeX/PiweeX#202]
Svi znamo da ekonomija servera nije bas najbolja.
Imam predlog koji bi poboljsao ekonomiju i vecini itema pomogao da odrze svoju cenu.

Napravio bi se novi **sell shop** (_mesto gde bi ste mogli da prodajete iteme serveru po nekoj minimalnoj ceni_)
Primer:
Volite da kopate i posedujete ogroman broj **Irona**, na serveru jednostavno ne postoji dovoljno velika potraznja za **Ironom** kako bi uspeli da prodate sve. Zbog toga ste primorani da spustate cenu **Irona** u nedogled kako bi skupili novac za claim ili slicno.

Primer kad bi **sell shop** postojao:
Imate 20 stackova **Iron blokova**, otisli bi u **sell shop** i prodali 15 stackova za 1500$ po stacku (_cena je samo za primer_).
Tih 15 stackova **Iron blokova** bi bili izbrisani iz igre jer su prodati serveru, a ostalih 5 stackova bi prodali na laputi po ceni vecoj od 1500$ (3000 npr).
Na taj nacin svi itemi bi imali svoju **"minimalnu vrednost"** i ekonomija bi bila dosta stabilnija nego sto je sad.

U **sell shopu** itemi bi imali nisku vrednost kako bi motivisalo igrace za medjusobnom prodajom, ali opet bi drzalo vrednost itema.

**Comment by mqtko** [comment]
Rispekt

**Comment by PiweeX** [comment]
> Svi znamo da ekonomija servera nije bas najbolja. Imam predlog koji bi poboljsao ekonomiju i vecini itema pomogao da odrze svoju cenu.
> 
> Napravio bi se novi **sell shop** (_mesto gde bi ste mogli da prodajete iteme serveru po nekoj minimalnoj ceni_) Primer: Volite da kopate i posedujete ogroman broj **Irona**, na serveru jednostavno ne postoji dovoljno velika potraznja za **Ironom** kako bi uspeli da prodate sve. Zbog toga ste primorani da spustate cenu **Irona** u nedogled kako bi skupili novac za claim ili slicno.
> 
> Primer kad bi **sell shop** postojao: Imate 20 stackova **Iron blokova**, otisli bi u **sell shop** i prodali 15 stackova za 1500$ po stacku (_cena je samo za primer_). Tih 15 stackova **Iron blokova** bi bili izbrisani iz igre jer su prodati serveru, a ostalih 5 stackova bi prodali na laputi po ceni vecoj od 1500$ (3000 npr). Na taj nacin svi itemi bi imali svoju **"minimalnu vrednost"** i ekonomija bi bila dosta stabilnija nego sto je sad.
> 
> U **sell shopu** itemi bi imali nisku vrednost kako bi motivisalo igrace za medjusobnom prodajom, ali opet bi drzalo vrednost itema.

problem kod prodaja ruda serveru tačnije mestu gde će igrač samo kliknuti na sign, oduzeti mu rude koje je iskopao i dati pare je taj što bi onda imali nestašicu ruda kroz par godina a rude su tu jer su neophodne za sva dešavanja.. zato je bitno da igrači trejduju prirodnim resursima po ponudi i potražnji a da neke stvari koje se mogu X puta iskopati mogu prodavati za novac poput kao što je sad za wheat, ribe i planiramo duže vreme i drvoseču koji će otkupljivati drva što će povećati potražnju za axeovima i ujedno enčentovima tako da i kopanjem i knjigama

**Comment by PiweeX** [comment]
NAČINI ZA DOBIJANJE CUSTOM ITEMA
napisaću i uređivaću vremenom listu pa ću spojiti sa vašom kad bude gotova


Custom itemi se dobijaju
A) preko HTokena

ovo čini da deo igrača bude online dok su u školi i preko noći

B) preko vote nagrada kroz krejtove

ovo čini da igrači svakodnevno glasaju za Hogov Realms što produktuje novim igračima i odgovornosti igrača prema serveru kroz sticanje navike za vote

NAČINI ZA DOBIJANJE NOVCA

A)

**Comment by PiweeX** [comment]
Gotovo već 😃
