### ISSUE TITLE
Drownedova plata

### ISSUE THREAD

**Issue by bDrowned** [PiweeX/PiweeX#205]
ljudi rekose da ce glasati da ja dobijam platu buduce da vodim platforme, isk nebi skodilo 😂

**Comment by mqtko** [comment]
Podrzavam, treba dati drownedu platu. 👍

**Comment by vukstrale** [comment]
> bDrowned

Iskreno dobićeš platu kad i staff dobije platu

**Comment by galileoba** [comment]
> ljudi rekose da ce glasati da ja dobijam platu buduce da vodim platforme, isk nebi skodilo joy

i ja sam trebao dobiti free NFT u vrijednosti od $1000 za rad ali još ništa

**Comment by vukstrale** [comment]
> > ljudi rekose da ce glasati da ja dobijam platu buduce da vodim platforme, isk nebi skodilo joy
> 
> i ja sam trebao dobiti free NFT u vrijednosti od $1000 za rad ali još ništa

xD zamisli očekuješ platu

**Comment by PiweeX** [comment]
Pa, ko je verovao u Hog kao projekat i u ono što radimo preko njega on i ima platu, u startup firmama imate to da zaposleni rade besplatno u zamenu za procenat kompanije ako uspe i ako je izguraju do kraja, to često budu ili akcije ili prosto % mesečnih prihoda i tu nema ništa loše

Mi smo Hog dizali godinama i mogu reći da su mnogi dobili mesečna primanja upravo tako što su radili besplatno bez da im je iko tražio a primer su Front, Pavle, Fqzon, Psiho. Ni 1 server na balkanu ni 95% u svetu ne plaća staff, moja je dobra volja da plaćamo support jer su oni bili tu i dizali sve to svojim prisustvom i radom

e sad ne možemo da plaćamo radnike dok se to ne digne na nivo na koji ja hoću tačnije dok ne dođe mainnet, to nije lak proces, čak i kad dođe mainnet ja ne mogu ništa da obećam nikom zato i nisam obećao već sam prosto rekao da će biti tako ako sve uspemo a ja črvsto verujem da će biti izgurano do kraja jer nazad nema

Trenutno plaćamo samo buildere i 1 stranog developera i to jako dobro, sledeći na redu je support, pored toga u DAO će biti airdrop to je ovo što galileo stručnjak spominje za NFT od 1000 evra, da tebi je obećano da kad mainnet bude krenuo dobićeš to i to je moje obećanje, to što bi ti prodao veru za večeru i što si to uradio sa svojim drugarima nije moj problem niti imam obavezu prema tebi niti prema ikom

A što se tiče vlasnika podservera za njih nisam planirao platu makar za sad, prvo je cilj da Support dobije ekstra platu koja će biti redovna i od koje bi mogli da žive, dal će vlasnici podservera dobijati to tek ne mogu da obećam, prosto ovo sve dižemo na viši nivo, ako sve bude kako je zamišljeno 2017. godine mogu obećati samo da će Support imati platu u šta uključuju dželati, chat support, support za plugine i naravno 10ak na Hogo Studios, morate razumeti da sve ovo ne diže grupa ljudi već sam ja glavni pokretač svega i treba dosta vremena ali ide u smeru u kom sam zamislio, sledeće godine završićemo video-stripove u svrhu edukativnog sadržaja što smo radili i 2019. pre 3 godine preko M Produkcije i to će biti na nacionalnim frekfencijama, to je recimo deo društveno korisnih poslovanja

Takođe imajte u vidu da smo od nemogućeg i već sad napravili mnogo jaku priču, 98% servera nikada to neće moći da ponove jer se svi oni zasnivaju na nelegalnim stvarima poput kardovanja mašina kako bi se držao host i tako odplaćivao hosting što je klasika, meni je to dosta, ja nemam šta da se dokazujem više, sa 13 godina smo pokrenuli Hog kog je drugi vlasnik moj drug Nido izjebao i izdao a sa 17 ga ja lično uspešno završavam i gurao sam ga svih 6 godina, za sad nekoliko ljudi prima plate i to je već neverovaran uspeh jer recimo idite budite gde god hoćete admini i dobićete kurac u dupe a ne platu, bukvalno

**Comment by PiweeX** [comment]
A vi što pričate mislim na Wolfa, Fropika i tebe a i još neke tu i što znate kog nisam platio, kolko plaćam porez itd druže kolko ste vi poreza platili i kakvu proizvodnju i svrhu imate, vi, vaš rad community i server. Samo ste iskopirali Hog i to jako loše toliko loše da je u prvom mesecu rejdovan 3 puta i to od samih vas lol

**Comment by PiweeX** [comment]
Evo zbog takvih poput vas sam lično ja zahtevao na gašenju shopa i HogRealms je kroz Minecraft na Balkanu postao još 1 od niza društveno korisnih poslovanja, ako ja trošim 100 dolara mesečno za održavanje skladišta za host i sve što ide uz to kako bih držao Hog a onda vi prozivate kad dobijem recimo 20$ od king ranka i jebete mi majku za to, ajde sad čekam vas šta ćete dalje da pričate kad više nema shopa, stvorili smo vrednost od Hoga, plugine koje smo razvili razvijeni su tako što smo mi kroz godine rada shvatili šta fali MC serverima i kako ih održati aktivnim i dobrim, zato mi imamo server aktivan sad će u Decembru godina a vi eto ugašeni drugi mesec i opet imate smelosti da pljujete nekoga bando ulična

**Comment by PiweeX** [comment]
A px šta se hvališ, pa druže svrha firme je da raste, i poenta je da se razvija i da ima što više mesečnih primanja i inovacija, zašto bi ja dolazio i rekao "ja nisam materijalista šta će mi pare držim ovo iz ljubavi" da samo što se takvi serveri ugase posle 4 meseca ne jer nemaju novca već jer niko neće da radi a da nema neke koristi od toga. Svako bi da napravi od nemogućeg nešto, svako bi da napravi server koji ima ogromnu vrednost, onaj ko ne uspe on će da priča da mu pare nisu bitne, meni su bitne samo u kontekstu da se firma kroz svoja poslovanja razvija i onda ima prostora da širi svoju kreativu i apsolutno sve moguće što ide uz to. To što vi prozivate da smo registrovani u Londonu pa svrha je da kroz nešto što radiš uspeš i budeš najbolji u tome, svi težimo ka tome, u 2022. ćemo se proširiti i u Srbiji a kasnije i u Republici Srpskoj iako radimo za globalno želim to jer će nam to otvoriti mnoga polja

možete da prozivate do ujutru i ti i Wolf, kad uspete da održite server 2 meseca aktivnim čestitaću vam javno, a kamoli nivo da poslujete legalno i makar paušalno plaćate porez na fizička lica
