### ISSUE TITLE
Preglednost drzava

### ISSUE THREAD

**Issue by DzingisKan738** [PiweeX/PiweeX#206]
stavi bataljug senegalskih crnaca i par britanaca u prostoriju i daj im svima po nož i eto ti pokolja.

jeste kasno pa se gubim, al evo jednog predloga kojeg sam ovako poetski usporedia gore. 

Kanal za promoviranje drzava izgleda ko ratno bojiste drzava. Neko posalje promociju, iste sekunde neka druga drzava posalje tako da je njihova prva po redu. Pa nismo hotline za kurve, promovirate roleplay! Uglavnom, u vezi predloga.

Da se svaka drzava moze prikazat u obliku jednog webhooka. Webhook bi sadrzava:
-ime drzave u prvom embedu kao title
-ispod tog opis kakav je njihov roleplay, opis itd...
-zastava države u obliku thumbnaila u prvom embedu
-proizvoljna slika u image odjelu webhooka
-link za discord države

Mogu prijavit državu za taj oglas i izmjenjivat ga otvaranjem ticketa u UN ili HogMaps.
Sve što je potrebno je da se dželatima da webhook URL za stvaranje poruke. U slučaju incidenata samo se promeni URL. 

I eto malo organiziranja da se senegalski crnci ne napale.

**Comment by vukstrale** [comment]
Nema novih igrača? Sve Britanci pouzimali? U tome je i stvar, države koje su najaktivnije će češće slati poruke i dobijati više igrača, to i jeste ideja.

**Comment by Attack36** [comment]
> Nema novih igrača? Sve Britanci pouzimali? U tome je i stvar, države koje su najaktivnije će češće slati poruke i dobijati više igrača, to i jeste ideja.

Problem sa ovime je da dobivaš snowball efekt. Država koja dobije imalu prednost u količini igrača automatski dobiva više i više od ostalih zbog ovakvog promo. Onda oni imaju sve više i više pa dominacija. Uz to ovo tjera sve da se trude svaki dan da šalju i šalju šta više i više i na kraju dobivamo jedan ili dva monopola i skupinu očajnika. Da ne govorim da ove manje populirane države gube igrače koji žele u veliki community. Zato za dosta ljudi je server suh usprko velikom količinom igrača. Jedna pokupi sve, ostali ili naprave svoje državice sa 3 chunka i 2 igrača (to zaslužuje tiket sam za sebe) ili se dosađuju u manjim državama. 

Sada riješenje. Napravimo kanal za encikolopediju svih državica koje su na server (za listu napravimo vrstu prijave, tipa unutar prijave za političku mapu tako da se oboje riješi u jednom sustavu) te se taj webhook napravi sa trajnim linkom od discorda. Ako je država neaktivna mjesec dana briše se. To daje novima da pogledaju sve države i da znaju šta sve ima, čak iako je neka država prva na popisu idalje će netko ići jedan po jedan i razmišljati šta mu je draže. Uz to bolje je od wikipedije jer je lakše čitati i treba nam centralizacija da nema zabune. Pre jaka decentralizacija je razlog zašto ima toliko glupih igrača i malih 3 chunk država itd. 

P.S. Jel država član roleplay lige se treba dodati tamo, te ja mislim da kasnije da imamo i enciklopediju saveza (Onih koji nisu tajni, poput SSRa)

**Comment by PiweeX** [comment]
> stavi bataljug senegalskih crnaca i par britanaca u prostoriju i daj im svima po nož i eto ti pokolja.
> 
> jeste kasno pa se gubim, al evo jednog predloga kojeg sam ovako poetski usporedia gore.
> 
> Kanal za promoviranje drzava izgleda ko ratno bojiste drzava. Neko posalje promociju, iste sekunde neka druga drzava posalje tako da je njihova prva po redu. Pa nismo hotline za kurve, promovirate roleplay! Uglavnom, u vezi predloga.
> 
> Da se svaka drzava moze prikazat u obliku jednog webhooka. Webhook bi sadrzava: -ime drzave u prvom embedu kao title -ispod tog opis kakav je njihov roleplay, opis itd... -zastava države u obliku thumbnaila u prvom embedu -proizvoljna slika u image odjelu webhooka -link za discord države
> 
> Mogu prijavit državu za taj oglas i izmjenjivat ga otvaranjem ticketa u UN ili HogMaps. Sve što je potrebno je da se dželatima da webhook URL za stvaranje poruke. U slučaju incidenata samo se promeni URL.
> 
> I eto malo organiziranja da se senegalski crnci ne napale.

tako sam zamislio u početku Decentralanda dok se sređivao discord ali nije održivo, ok ja pejstam u webhook poruku koju mi glavni ljudi tih država pošalju ali kako je to održivo ako će se nešto stalno menjati

npr neko promeni ime, ili roleplay, ili se države brišu pa imaju nove linkove, nove discorde, nukeovani

ja sam u početku imao plan da se svaki discord prebaci na moj alt nalog kako nebi imali efekat da bilo koja budala može da nukea taj server ali to je glupo i prosto pustimo igrače da rade i uređuju opise i sve kako žele i da ujedno šalju u promo

**Comment by Attack36** [comment]
> > stavi bataljug senegalskih crnaca i par britanaca u prostoriju i daj im svima po nož i eto ti pokolja.
> > jeste kasno pa se gubim, al evo jednog predloga kojeg sam ovako poetski usporedia gore.
> > Kanal za promoviranje drzava izgleda ko ratno bojiste drzava. Neko posalje promociju, iste sekunde neka druga drzava posalje tako da je njihova prva po redu. Pa nismo hotline za kurve, promovirate roleplay! Uglavnom, u vezi predloga.
> > Da se svaka drzava moze prikazat u obliku jednog webhooka. Webhook bi sadrzava: -ime drzave u prvom embedu kao title -ispod tog opis kakav je njihov roleplay, opis itd... -zastava države u obliku thumbnaila u prvom embedu -proizvoljna slika u image odjelu webhooka -link za discord države
> > Mogu prijavit državu za taj oglas i izmjenjivat ga otvaranjem ticketa u UN ili HogMaps. Sve što je potrebno je da se dželatima da webhook URL za stvaranje poruke. U slučaju incidenata samo se promeni URL.
> > I eto malo organiziranja da se senegalski crnci ne napale.
> 
> tako sam zamislio u početku Decentralanda dok se sređivao discord ali nije održivo, ok ja pejstam u webhook poruku koju mi glavni ljudi tih država pošalju ali kako je to održivo ako će se nešto stalno menjati
> 
> npr neko promeni ime, ili roleplay, ili se države brišu pa imaju nove linkove, nove discorde, nukeovani
> 
> ja sam u početku imao plan da se svaki discord prebaci na moj alt nalog kako nebi imali efekat da bilo koja budala može da nukea taj server ali to je glupo i prosto pustimo igrače da rade i uređuju opise i sve kako žele i da ujedno šalju u promo

Te promijene se isto mogu riješiti tako što samo daš dželatu da vodi računa o izmjenama i to. Ili naći alternativu koja omogučuje lako mijenjanje. Ugl može se lako riješiti. Ja prvi nudim da o tome vodim računa i da rješavam tikete za to.

**Comment by PiweeX** [comment]
o ovome sam pisao više puta zašto je loše, sve se jako brzo menja a mi ne želimo da napravimo da igrači izrobljuju DAO ili support, jer razumete jako je teško održavati sve to kad bi bilo jer ipak sve se brzo menja, opisi, imena država, slike itd a mi želimo skroz decentralizovan server i sam sistem da igrači mogu da rade sve
