### ISSUE TITLE
Brewing Stand

### ISSUE THREAD

**Issue by Siu804** [PiweeX/PiweeX#207]
Px mislim da bi bilo vreme da se ubace blaze rpd-ovi i ostali sastojci za potione zato sto Brewing stand se dobija na kraju playtime ali nema trenutno korist pa kosta manje ako bi moglo da se ubaci na spawn bilo bi super...To mogu potvrditi i oni sa Brewing stand-ovima.Ako se slazete napisite

**Comment by Attack36** [comment]
Problem je sto je dobar dio ovih potiona dosta OP, ja dajem preporuku da se mozda daju ograniceno kao nagrada u UHCu. Stime da se slazem da se dragons breath treba dodati.

**Comment by Siu804** [comment]
Pa ako je OP ima dosta njih sa tim potionima nema smisla Brewing standa ako nema potione :/
