### ISSUE TITLE
Problemi sa Uhc-om

### ISSUE THREAD

**Issue by Viktor023023** [PiweeX/PiweeX#208]
Vec duze vreme uhc baguje zbog 1.8.9 verzije. Gameplay je zbagan, rude nestaju itd, nagrade gube smisao. Predlazem da se vrati na 1.7.10 verziju i da ako mogu da se osmisle nove nagrade ili da se daju stare. uvek je duo ili solo, pre je vise ljudi igralo i bilo je vise zabavnije

**Comment by PiweeX** [comment]
pokušavamo da rešimo problem sa rudama sa Activatedom, neće biti vraćanja na 1.7.10 jer ste tražili 1.8 nedeljama i tu nema izmene, samo ćemo pokušait da rešimo problem

**Comment by PiweeX** [comment]
RESENO!

server je odrađen od 0 i vraćen je na 1.7.10
