### ISSUE TITLE
Igraci koji vise ne igraju

### ISSUE THREAD

**Issue by yamizvaniuchicha** [PiweeX/PiweeX#210]
Peticija da se stvari od igraca koji su otisli sa servera oduzmu i razdele po serveru, unormalizovala bi se ekonomija servera!

**Comment by Attack36** [comment]
Brate jel znaš ti za inflaciju? To ništa ne riješava ako ne i pogoršava

**Comment by JedemJaja** [comment]
Bilo bi bolje da se spale nego da se podijele

**Comment by JedemJaja** [comment]
> Brate jer znaš ti za inflaciju? To ništa ne riješava ako ne i pogoršava

Jel si glup?
Jer si glup.
Nauči razliku

**Comment by Attack36** [comment]
> > Brate jer znaš ti za inflaciju? To ništa ne riješava ako ne i pogoršava
> 
> Jel si glup? Jer si glup. Nauči razliku

🤓

**Comment by RatkoSef** [comment]
Pa u svakom trenutku je moguce da se ti igraci vrate i sta cemo onda? kako im objasniti da im je udjeno na nalog i pokradeno sve sto imaju? Unistili bi reputaciju servera , Ne bi prijalo ekonomiji etc

**Comment by galileoba** [comment]
> Peticija da se stvari od igraca koji su otisli sa servera oduzmu i razdele po serveru, unormalizovala bi se ekonomija servera!

Ma bas hahahahha

**Comment by PiweeX** [comment]
Zatvoriću issue pošto ste rekli šta mislite
