### ISSUE TITLE
Pušenje, opijanje i balkansko ponašanje!

### ISSUE THREAD

**Issue by Attack36** [PiweeX/PiweeX#213]
Znači, kao narod balkanski kakvi svi jesmo uživamo u nekim stvarima. Volimo žene, pušenje i opijanje. Najbolji primjer toga je moj prijatelj, i bivši Englez na Hogu **Brza Kifla**. Jednog dana kada sam njega vidio sinulo mi je da stvari u kojima on uživa van Hoga se treba staviti na hog, osim npc žena jer brat nije pičke video osim pri rođenju. 

***1. Brewery plugin 1.18.2*** - https://dev.bukkit.org/projects/brewery/files/3867134

***2. Smoking pipes 1.17.2*** (Ali testirano radi na 1.18.2 bez problema) - https://www.spigotmc.org/resources/smoking-pipes.8326/

Ti plugini su već testirani od mene i **rade na 1.18.2** bez problema te su laki za korištenje. **Naučio sam ih editirati** u konfig fajlu i **dodavati nove stvari** (ili micati jer kod brewery plugina ima dosta i previše tih pa neke ću skloniti najvjv.) za igrače te **podešavati stvari** oko plugina za ekonomiju ako je nešto pre slabo ili pre OP, te kada mi krenu praznici za par tjedana moći ću ih sve **prevesti s engleskog**. 

Da ne govorim da će potaknuti i **ekonomiju**, jer će ljudi prodavati rakiju koje ima **različite kvalitete** (a pušenje različite efekte) i sve će htjeti i **natjecat**i se kako napraviti najbolju rakiju i vino i pivo i pokušavati otkrivati recepte jer su donekle random i nisam našao tutorijale online još (stime da sam davno gledao nez za sad baš) za koje točno **uvijete** trebaš imati. Ljudi će se zajebavati jer se možeš napiti i ima i **nivoi pijanosti** te neki ti daju čak i **boostove u ratu** stime da ima **posljedice**. Lule i to će dodavati **roleplay** Mongolima i plemenskim državama ali i ostalim jer sve kulture vole da puše. Ja mogu dodavati razne trave kao i poznati **Denzelov Albanski hašiš**. 

Za smoking pipes plugin dolaze crafting recepti i kako sušiti u peći trave, a za brewery praviš bačve sa stairs i ogradama te završiš sa znakom.

Uglavnom, sve se može, imaš voljne pomoćnike, ne znam zašto ne bih htio px!

**Comment by vukstrale** [comment]
već imamo marihuano bebo meni dosta

**Comment by Attack36** [comment]
> već imamo marihuano bebo meni dosta

Mislim biti će zanimljivo pogotovo jer je za dosta igrača hog malo dosadan trenutno bez neke nove promjene a ta marihuana može biti puštena da idalje postoji ovo njoj ne škodi jer ove trave nisu nužno weed.

**Comment by kifla-hub** [comment]
podrzavam max ocu da budem proizvodjac zajecarskog

**Comment by ConeBe** [comment]
Ja sam zainteresovan da prodajem cigare i da ih pravim za sve

**Comment by TheFrontView** [comment]
Bilo bi zanimljivo da se doda. Ja bih pušio tompus svaki dan 😍

**Comment by konfix** [comment]
> već imamo marihuano bebo meni dosta

ima al ne radi vec pola godine ahhaha

**Comment by vukstrale** [comment]
> > već imamo marihuano bebo meni dosta
> 
> ima al ne radi vec pola godine ahhaha

ko priča o majnkraftu?

**Comment by JedemJaja** [comment]
> Znači, kao narod balkanski kakvi svi jesmo uživamo u nekim stvarima. Volimo žene, pušenje i opijanje. Najbolji primjer toga je moj prijatelj, i bivši Englez na Hogu **Brza Kifla**. Jednog dana kada sam njega vidio sinulo mi je da stvari u kojima on uživa van Hoga se treba staviti na hog, osim npc žena jer brat nije pičke video osim pri rođenju.
> 
> _**1. Brewery plugin 1.18.2**_ - https://dev.bukkit.org/projects/brewery/files/3867134
> 
> _**2. Smoking pipes 1.17.2**_ (Ali testirano radi na 1.18.2 bez problema) - https://www.spigotmc.org/resources/smoking-pipes.8326/
> 
> Ti plugini su već testirani od mene i **rade na 1.18.2** bez problema te su laki za korištenje. **Naučio sam ih editirati** u konfig fajlu i **dodavati nove stvari** (ili micati jer kod brewery plugina ima dosta i previše tih pa neke ću skloniti najvjv.) za igrače te **podešavati stvari** oko plugina za ekonomiju ako je nešto pre slabo ili pre OP, te kada mi krenu praznici za par tjedana moći ću ih sve **prevesti s engleskog**.
> 
> Da ne govorim da će potaknuti i **ekonomiju**, jer će ljudi prodavati rakiju koje ima **različite kvalitete** (a pušenje različite efekte) i sve će htjeti i **natjecat**i se kako napraviti najbolju rakiju i vino i pivo i pokušavati otkrivati recepte jer su donekle random i nisam našao tutorijale online još (stime da sam davno gledao nez za sad baš) za koje točno **uvijete** trebaš imati. Ljudi će se zajebavati jer se možeš napiti i ima i **nivoi pijanosti** te neki ti daju čak i **boostove u ratu** stime da ima **posljedice**. Lule i to će dodavati **roleplay** Mongolima i plemenskim državama ali i ostalim jer sve kulture vole da puše. Ja mogu dodavati razne trave kao i poznati **Denzelov Albanski hašiš**.
> 
> Za smoking pipes plugin dolaze crafting recepti i kako sušiti u peći trave, a za brewery praviš bačve sa stairs i ogradama te završiš sa znakom.
> 
> Uglavnom, sve se može, imaš voljne pomoćnike, ne znam zašto ne bih htio px!

Jel i to u ssru izglasano?

**Comment by Attack36** [comment]
> > Znači, kao narod balkanski kakvi svi jesmo uživamo u nekim stvarima. Volimo žene, pušenje i opijanje. Najbolji primjer toga je moj prijatelj, i bivši Englez na Hogu **Brza Kifla**. Jednog dana kada sam njega vidio sinulo mi je da stvari u kojima on uživa van Hoga se treba staviti na hog, osim npc žena jer brat nije pičke video osim pri rođenju.
> > _**1. Brewery plugin 1.18.2**_ - https://dev.bukkit.org/projects/brewery/files/3867134
> > _**2. Smoking pipes 1.17.2**_ (Ali testirano radi na 1.18.2 bez problema) - https://www.spigotmc.org/resources/smoking-pipes.8326/
> > Ti plugini su već testirani od mene i **rade na 1.18.2** bez problema te su laki za korištenje. **Naučio sam ih editirati** u konfig fajlu i **dodavati nove stvari** (ili micati jer kod brewery plugina ima dosta i previše tih pa neke ću skloniti najvjv.) za igrače te **podešavati stvari** oko plugina za ekonomiju ako je nešto pre slabo ili pre OP, te kada mi krenu praznici za par tjedana moći ću ih sve **prevesti s engleskog**.
> > Da ne govorim da će potaknuti i **ekonomiju**, jer će ljudi prodavati rakiju koje ima **različite kvalitete** (a pušenje različite efekte) i sve će htjeti i **natjecat**i se kako napraviti najbolju rakiju i vino i pivo i pokušavati otkrivati recepte jer su donekle random i nisam našao tutorijale online još (stime da sam davno gledao nez za sad baš) za koje točno **uvijete** trebaš imati. Ljudi će se zajebavati jer se možeš napiti i ima i **nivoi pijanosti** te neki ti daju čak i **boostove u ratu** stime da ima **posljedice**. Lule i to će dodavati **roleplay** Mongolima i plemenskim državama ali i ostalim jer sve kulture vole da puše. Ja mogu dodavati razne trave kao i poznati **Denzelov Albanski hašiš**.
> > Za smoking pipes plugin dolaze crafting recepti i kako sušiti u peći trave, a za brewery praviš bačve sa stairs i ogradama te završiš sa znakom.
> > Uglavnom, sve se može, imaš voljne pomoćnike, ne znam zašto ne bih htio px!
> 
> Jel i to u ssru izglasano?

1. Kakve to ima veze? ili si samo tu da budeš toksičan prema meni
2. Nije, ja sam to sa kiflom napisao.

**Comment by marepleb** [comment]
> već imamo marihuano bebo meni dosta

imamo koju ne radi

**Comment by marepleb** [comment]
> Bilo bi zanimljivo da se doda. Ja bih pušio tompus svaki dan 😍

pusis ti meni nesto drugo

**Comment by marepleb** [comment]
> Znači, kao narod balkanski kakvi svi jesmo uživamo u nekim stvarima. Volimo žene, pušenje i opijanje. Najbolji primjer toga je moj prijatelj, i bivši Englez na Hogu **Brza Kifla**. Jednog dana kada sam njega vidio sinulo mi je da stvari u kojima on uživa van Hoga se treba staviti na hog, osim npc žena jer brat nije pičke video osim pri rođenju.
> 
> _**1. Brewery plugin 1.18.2**_ - https://dev.bukkit.org/projects/brewery/files/3867134
> 
> _**2. Smoking pipes 1.17.2**_ (Ali testirano radi na 1.18.2 bez problema) - https://www.spigotmc.org/resources/smoking-pipes.8326/
> 
> Ti plugini su već testirani od mene i **rade na 1.18.2** bez problema te su laki za korištenje. **Naučio sam ih editirati** u konfig fajlu i **dodavati nove stvari** (ili micati jer kod brewery plugina ima dosta i previše tih pa neke ću skloniti najvjv.) za igrače te **podešavati stvari** oko plugina za ekonomiju ako je nešto pre slabo ili pre OP, te kada mi krenu praznici za par tjedana moći ću ih sve **prevesti s engleskog**.
> 
> Da ne govorim da će potaknuti i **ekonomiju**, jer će ljudi prodavati rakiju koje ima **različite kvalitete** (a pušenje različite efekte) i sve će htjeti i **natjecat**i se kako napraviti najbolju rakiju i vino i pivo i pokušavati otkrivati recepte jer su donekle random i nisam našao tutorijale online još (stime da sam davno gledao nez za sad baš) za koje točno **uvijete** trebaš imati. Ljudi će se zajebavati jer se možeš napiti i ima i **nivoi pijanosti** te neki ti daju čak i **boostove u ratu** stime da ima **posljedice**. Lule i to će dodavati **roleplay** Mongolima i plemenskim državama ali i ostalim jer sve kulture vole da puše. Ja mogu dodavati razne trave kao i poznati **Denzelov Albanski hašiš**.
> 
> Za smoking pipes plugin dolaze crafting recepti i kako sušiti u peći trave, a za brewery praviš bačve sa stairs i ogradama te završiš sa znakom.
> 
> Uglavnom, sve se može, imaš voljne pomoćnike, ne znam zašto ne bih htio px!

ako se ovo doda a da radi ne kao gandza i grozdje onda se vrcam na hog

**Comment by Attack36** [comment]
> > Znači, kao narod balkanski kakvi svi jesmo uživamo u nekim stvarima. Volimo žene, pušenje i opijanje. Najbolji primjer toga je moj prijatelj, i bivši Englez na Hogu **Brza Kifla**. Jednog dana kada sam njega vidio sinulo mi je da stvari u kojima on uživa van Hoga se treba staviti na hog, osim npc žena jer brat nije pičke video osim pri rođenju.
> > _**1. Brewery plugin 1.18.2**_ - https://dev.bukkit.org/projects/brewery/files/3867134
> > _**2. Smoking pipes 1.17.2**_ (Ali testirano radi na 1.18.2 bez problema) - https://www.spigotmc.org/resources/smoking-pipes.8326/
> > Ti plugini su već testirani od mene i **rade na 1.18.2** bez problema te su laki za korištenje. **Naučio sam ih editirati** u konfig fajlu i **dodavati nove stvari** (ili micati jer kod brewery plugina ima dosta i previše tih pa neke ću skloniti najvjv.) za igrače te **podešavati stvari** oko plugina za ekonomiju ako je nešto pre slabo ili pre OP, te kada mi krenu praznici za par tjedana moći ću ih sve **prevesti s engleskog**.
> > Da ne govorim da će potaknuti i **ekonomiju**, jer će ljudi prodavati rakiju koje ima **različite kvalitete** (a pušenje različite efekte) i sve će htjeti i **natjecat**i se kako napraviti najbolju rakiju i vino i pivo i pokušavati otkrivati recepte jer su donekle random i nisam našao tutorijale online još (stime da sam davno gledao nez za sad baš) za koje točno **uvijete** trebaš imati. Ljudi će se zajebavati jer se možeš napiti i ima i **nivoi pijanosti** te neki ti daju čak i **boostove u ratu** stime da ima **posljedice**. Lule i to će dodavati **roleplay** Mongolima i plemenskim državama ali i ostalim jer sve kulture vole da puše. Ja mogu dodavati razne trave kao i poznati **Denzelov Albanski hašiš**.
> > Za smoking pipes plugin dolaze crafting recepti i kako sušiti u peći trave, a za brewery praviš bačve sa stairs i ogradama te završiš sa znakom.
> > Uglavnom, sve se može, imaš voljne pomoćnike, ne znam zašto ne bih htio px!
> 
> ako se ovo doda a da radi ne kao gandza i grozdje onda se vrcam na hog

Doslovno ne može biti sjebano poput marihuane i grozđa jer su to biljke preko oraksena ovo je zaseban plugin tako da radit će. Uz to moram da pitam, koje alkoholno piće/duhan očeš da bude dodan ako prođe prijedlog?

**Comment by yamizvaniuchicha** [comment]
hašiš

**Comment by yamizvaniuchicha** [comment]
> > > Znači, kao narod balkanski kakvi svi jesmo uživamo u nekim stvarima. Volimo žene, pušenje i opijanje. Najbolji primjer toga je moj prijatelj, i bivši Englez na Hogu **Brza Kifla**. Jednog dana kada sam njega vidio sinulo mi je da stvari u kojima on uživa van Hoga se treba staviti na hog, osim npc žena jer brat nije pičke video osim pri rođenju.
> > > _**1. Brewery plugin 1.18.2**_ - https://dev.bukkit.org/projects/brewery/files/3867134
> > > _**2. Smoking pipes 1.17.2**_ (Ali testirano radi na 1.18.2 bez problema) - https://www.spigotmc.org/resources/smoking-pipes.8326/
> > > Ti plugini su već testirani od mene i **rade na 1.18.2** bez problema te su laki za korištenje. **Naučio sam ih editirati** u konfig fajlu i **dodavati nove stvari** (ili micati jer kod brewery plugina ima dosta i previše tih pa neke ću skloniti najvjv.) za igrače te **podešavati stvari** oko plugina za ekonomiju ako je nešto pre slabo ili pre OP, te kada mi krenu praznici za par tjedana moći ću ih sve **prevesti s engleskog**.
> > > Da ne govorim da će potaknuti i **ekonomiju**, jer će ljudi prodavati rakiju koje ima **različite kvalitete** (a pušenje različite efekte) i sve će htjeti i **natjecat**i se kako napraviti najbolju rakiju i vino i pivo i pokušavati otkrivati recepte jer su donekle random i nisam našao tutorijale online još (stime da sam davno gledao nez za sad baš) za koje točno **uvijete** trebaš imati. Ljudi će se zajebavati jer se možeš napiti i ima i **nivoi pijanosti** te neki ti daju čak i **boostove u ratu** stime da ima **posljedice**. Lule i to će dodavati **roleplay** Mongolima i plemenskim državama ali i ostalim jer sve kulture vole da puše. Ja mogu dodavati razne trave kao i poznati **Denzelov Albanski hašiš**.
> > > Za smoking pipes plugin dolaze crafting recepti i kako sušiti u peći trave, a za brewery praviš bačve sa stairs i ogradama te završiš sa znakom.
> > > Uglavnom, sve se može, imaš voljne pomoćnike, ne znam zašto ne bih htio px!
> > 
> > 
> > ako se ovo doda a da radi ne kao gandza i grozdje onda se vrcam na hog
> 
> Doslovno ne može biti sjebano poput marihuane i grozđa jer su to biljke preko oraksena ovo je zaseban plugin tako da radit će. Uz to moram da pitam, koje alkoholno piće/duhan očeš da bude dodan ako prođe prijedlog?

dodajte hašiš

**Comment by Attack36** [comment]
> > > > Znači, kao narod balkanski kakvi svi jesmo uživamo u nekim stvarima. Volimo žene, pušenje i opijanje. Najbolji primjer toga je moj prijatelj, i bivši Englez na Hogu **Brza Kifla**. Jednog dana kada sam njega vidio sinulo mi je da stvari u kojima on uživa van Hoga se treba staviti na hog, osim npc žena jer brat nije pičke video osim pri rođenju.
> > > > _**1. Brewery plugin 1.18.2**_ - https://dev.bukkit.org/projects/brewery/files/3867134
> > > > _**2. Smoking pipes 1.17.2**_ (Ali testirano radi na 1.18.2 bez problema) - https://www.spigotmc.org/resources/smoking-pipes.8326/
> > > > Ti plugini su već testirani od mene i **rade na 1.18.2** bez problema te su laki za korištenje. **Naučio sam ih editirati** u konfig fajlu i **dodavati nove stvari** (ili micati jer kod brewery plugina ima dosta i previše tih pa neke ću skloniti najvjv.) za igrače te **podešavati stvari** oko plugina za ekonomiju ako je nešto pre slabo ili pre OP, te kada mi krenu praznici za par tjedana moći ću ih sve **prevesti s engleskog**.
> > > > Da ne govorim da će potaknuti i **ekonomiju**, jer će ljudi prodavati rakiju koje ima **različite kvalitete** (a pušenje različite efekte) i sve će htjeti i **natjecat**i se kako napraviti najbolju rakiju i vino i pivo i pokušavati otkrivati recepte jer su donekle random i nisam našao tutorijale online još (stime da sam davno gledao nez za sad baš) za koje točno **uvijete** trebaš imati. Ljudi će se zajebavati jer se možeš napiti i ima i **nivoi pijanosti** te neki ti daju čak i **boostove u ratu** stime da ima **posljedice**. Lule i to će dodavati **roleplay** Mongolima i plemenskim državama ali i ostalim jer sve kulture vole da puše. Ja mogu dodavati razne trave kao i poznati **Denzelov Albanski hašiš**.
> > > > Za smoking pipes plugin dolaze crafting recepti i kako sušiti u peći trave, a za brewery praviš bačve sa stairs i ogradama te završiš sa znakom.
> > > > Uglavnom, sve se može, imaš voljne pomoćnike, ne znam zašto ne bih htio px!
> > > 
> > > 
> > > ako se ovo doda a da radi ne kao gandza i grozdje onda se vrcam na hog
> > 
> > 
> > Doslovno ne može biti sjebano poput marihuane i grozđa jer su to biljke preko oraksena ovo je zaseban plugin tako da radit će. Uz to moram da pitam, koje alkoholno piće/duhan očeš da bude dodan ako prođe prijedlog?
> 
> dodajte hašiš

Denzelov ili običan?

**Comment by yamizvaniuchicha** [comment]
> 

denzin naravno

**Comment by marepleb** [comment]
> > > Znači, kao narod balkanski kakvi svi jesmo uživamo u nekim stvarima. Volimo žene, pušenje i opijanje. Najbolji primjer toga je moj prijatelj, i bivši Englez na Hogu **Brza Kifla**. Jednog dana kada sam njega vidio sinulo mi je da stvari u kojima on uživa van Hoga se treba staviti na hog, osim npc žena jer brat nije pičke video osim pri rođenju.
> > > _**1. Brewery plugin 1.18.2**_ - https://dev.bukkit.org/projects/brewery/files/3867134
> > > _**2. Smoking pipes 1.17.2**_ (Ali testirano radi na 1.18.2 bez problema) - https://www.spigotmc.org/resources/smoking-pipes.8326/
> > > Ti plugini su već testirani od mene i **rade na 1.18.2** bez problema te su laki za korištenje. **Naučio sam ih editirati** u konfig fajlu i **dodavati nove stvari** (ili micati jer kod brewery plugina ima dosta i previše tih pa neke ću skloniti najvjv.) za igrače te **podešavati stvari** oko plugina za ekonomiju ako je nešto pre slabo ili pre OP, te kada mi krenu praznici za par tjedana moći ću ih sve **prevesti s engleskog**.
> > > Da ne govorim da će potaknuti i **ekonomiju**, jer će ljudi prodavati rakiju koje ima **različite kvalitete** (a pušenje različite efekte) i sve će htjeti i **natjecat**i se kako napraviti najbolju rakiju i vino i pivo i pokušavati otkrivati recepte jer su donekle random i nisam našao tutorijale online još (stime da sam davno gledao nez za sad baš) za koje točno **uvijete** trebaš imati. Ljudi će se zajebavati jer se možeš napiti i ima i **nivoi pijanosti** te neki ti daju čak i **boostove u ratu** stime da ima **posljedice**. Lule i to će dodavati **roleplay** Mongolima i plemenskim državama ali i ostalim jer sve kulture vole da puše. Ja mogu dodavati razne trave kao i poznati **Denzelov Albanski hašiš**.
> > > Za smoking pipes plugin dolaze crafting recepti i kako sušiti u peći trave, a za brewery praviš bačve sa stairs i ogradama te završiš sa znakom.
> > > Uglavnom, sve se može, imaš voljne pomoćnike, ne znam zašto ne bih htio px!
> > 
> > 
> > ako se ovo doda a da radi ne kao gandza i grozdje onda se vrcam na hog
> 
> Doslovno ne može biti sjebano poput marihuane i grozđa jer su to biljke preko oraksena ovo je zaseban plugin tako da radit će. Uz to moram da pitam, koje alkoholno piće/duhan očeš da bude dodan ako prođe prijedlog?

hasis,tompus,vodka,zajecarsko

**Comment by Attack36** [comment]
![image](https://user-images.githubusercontent.com/107584200/195654184-8cb8181c-612e-426f-92f7-2fe1046ac6d9.png)

**Comment by marepleb** [comment]
> ![image](https://user-images.githubusercontent.com/107584200/195654184-8cb8181c-612e-426f-92f7-2fe1046ac6d9.png)

![image](https://user-images.githubusercontent.com/107114906/195656150-96750986-2e10-4a86-ba89-1764aad15a16.png)

**Comment by Attack36** [comment]
> > ![image](https://user-images.githubusercontent.com/107584200/195654184-8cb8181c-612e-426f-92f7-2fe1046ac6d9.png)
> 
> ![image](https://user-images.githubusercontent.com/107114906/195656150-96750986-2e10-4a86-ba89-1764aad15a16.png)

Već je podešen konifg fajl za pušenje tj. verzija 1.0 koja će biti prva puštena kada se memorija popravi. Nakon nje stiže verzija 1.1 da popravimo bugove i podesimo šta ako bude trebalo i kasnije 2.0 sa custom lulama koji će se dodati na custom hašiše u 1.0 verziji te kad se to stabilizira par dana nakon dolazi brewery plugin te u roku maksimum mjesec dana bi trebalo sve raditi kako se spada.

**Comment by Attack36** [comment]
![image](https://user-images.githubusercontent.com/107584200/195783011-2c871510-3fb9-47fc-ba7c-8a9224a24877.png)

ovo imam za sad za 1.0 od hašiša, ako ima koja još preporuka neka mi javite ovde

**Comment by marepleb** [comment]
> > > ![image](https://user-images.githubusercontent.com/107584200/195654184-8cb8181c-612e-426f-92f7-2fe1046ac6d9.png)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/107114906/195656150-96750986-2e10-4a86-ba89-1764aad15a16.png)
> 
> Već je podešen konifg fajl za pušenje tj. verzija 1.0 koja će biti prva puštena kada se memorija popravi. Nakon nje stiže verzija 1.1 da popravimo bugove i podesimo šta ako bude trebalo i kasnije 2.0 sa custom lulama koji će se dodati na custom hašiše u 1.0 verziji te kad se to stabilizira par dana nakon dolazi brewery plugin te u roku maksimum mjesec dana bi trebalo sve raditi kako se spada.

znaci sledece godine stize?

**Comment by PiweeX** [comment]
Issue ću zatvoriti jer ovo nećemo dodavati na Decentraland ali na SkyBlock 80% da
