### ISSUE TITLE
Lidl

### ISSUE THREAD

**Issue by TheFrontView** [PiweeX/PiweeX#214]
Ne znam da li je svakog briga za lidl na Hogo, ali one cene su neverovatno skupe. Planirao sam graditi kuću koja će krov imati od stepenica kvarca. Zaprepastio sam se kada sam pogledao cenu 200$ za 16 kvarca?

Bilo bi okej da je to kvarc blok mada i to bi bilo skupo, ali ono je klasičan kvarc. Ima još stvari za koje bi se mogla promeniti cena. Zamolio bih da se složi te jer ko zna kada će vam zatrebati.

https://prnt.sc/I93jLptmkeYX
https://prnt.sc/-DfO299goBCf
https://prnt.sc/wKY6fK8aiblW

**Comment by JedemJaja** [comment]
Idi kopaj

**Comment by marepleb** [comment]
> Ne znam da li je svakog briga za lidl na Hogo, ali one cene su neverovatno skupe. Planirao sam graditi kuću koja će krov imati od stepenica kvarca. Zaprepastio sam se kada sam pogledao cenu 200$ za 16 kvarca?
> 
> Bilo bi okej da je to kvarc blok mada i to bi bilo skupo, ali ono je klasičan kvarc. Ima još stvari za koje bi se mogla promeniti cena. Zamolio bih da se složi te jer ko zna kada će vam zatrebati.
> 
> https://prnt.sc/I93jLptmkeYX https://prnt.sc/-DfO299goBCf https://prnt.sc/wKY6fK8aiblW

zapravo je jeftino to je tvoj skill issue

**Comment by PiweeX** [comment]
Popravljeno je pojavom Black shopa (nadam se)
