### ISSUE TITLE
Vracanje Vip sobe

### ISSUE THREAD

**Issue by marepleb** [PiweeX/PiweeX#216]
Par osoba i ja bi voleli da nam se vrati Vip soba koja je samo za roleove @Respektivni Clan i @Media i vece od tih.Mislim da bi vracanje te sobe moglo dosta pomoci serveru na nacin u kom necu vise Piweexa smarati u dm za memoriju nego u #vip sobu

**Comment by yamizvaniuchicha** [comment]
u potpunosti se slazem

**Comment by TheFrontView** [comment]
Ne.

**Comment by marepleb** [comment]
> Ne.

sta bre ne picko smedervska

**Comment by vukstrale** [comment]
> > Ne.
> 
> sta bre ne picko smedervska

Uf vredjanje igrača saću te mutam

**Comment by benjamin858** [comment]
mareeee ljubavi

**Comment by marepleb** [comment]
> mareeee ljubavi

benjamin 💀

**Comment by benjamin858** [comment]
> > mareeee ljubavi
> 
> benjamin 💀
imas sto pritv imena aaa

**Comment by PiweeX** [comment]
Videćemo ako se uklopi negde, za sad nemam ideju gde bi moglo da bude ali razmišljao sam danas o novom yt programu koji ćemo razviti posle otvaranja SMP sezone za 2023. godinu
