### ISSUE TITLE
Px je jak decko 😬

### ISSUE THREAD

**Issue by Zav1637** [PiweeX/PiweeX#217]
![IMG_20221023_083305](https://user-images.githubusercontent.com/108089196/197377859-f696039c-5cdb-4a34-b98e-0e50dcb56489.jpg)

**Comment by JedemJaja** [comment]
Ok

**Comment by Attack36** [comment]
Iskreno platio bi velike novce da vidim kako PiweeeX izbija zube Zavu palicom.

**Comment by vukstrale** [comment]
Auuuu

**Comment by konfix** [comment]
al mora prvo da dodje u petra antonijevica 8 lazarevac da bi mu izbio zube

**Comment by vukstrale** [comment]
> al mora prvo da dodje u petra antonijevica 8 lazarevac da bi mu izbio zube

Px koliko je Šušnjar daleko od Lazarevca? Znam da je blizu ono, imam rodbine tamo

**Comment by marepleb** [comment]
> > al mora prvo da dodje u petra antonijevica 8 lazarevac da bi mu izbio zube
> 
> Px koliko je Šušnjar daleko od Lazarevca? Znam da je blizu ono, imam rodbine tamo

e brate od mene do pxa jedno 2km a ja u centru Lazarevca

**Comment by PiweeX** [comment]
Njega samo na prevaspitavanje, jer može samo preko neta da se kurči a nema ni 12 godina

**Comment by benjamin858** [comment]
zav kidaro idi ka mami i placi

**Comment by benjamin858** [comment]
ne dirajte mi px

**Comment by benjamin858** [comment]
ko to hoce da mi dira px nedo bog da ga vidim u rl
ubio bi ga sa kamenom

**Comment by benjamin858** [comment]
zg
