### ISSUE TITLE
Sugescija

### ISSUE THREAD

**Issue by onepotato69** [PiweeX/PiweeX#218]
Da svaki igrac dobije licne dokumente na kojima pise kada je usao ime i u koliko drzava ima drzavljanstvo (trust). To bi doprinelo war komandama i roleplay na ovaj nacin:
kada dve drzave odu u rat i sada jedna drzava posalje spiuna u drugu drzavu oni ga nece primiti jer mu na licnim dokmentima pise gde ima trust ali se moze dodati cuatom item Pasos i onda se moze craftati sa leatherom papirima i player headom. Kada se to uradi dobije se lazirani pasos u kom se mogu menjati licni podatci da bi se uslo u neku drzavu i bilo bi lakse ako se jos doda ako je neko banan iz neke drzave on moze da udje sa laziranim pasosom.

**Comment by JedemJaja** [comment]
Mislim da je na vlasnicima drzava da paze tko im ulazi u land

**Comment by Attack36** [comment]
Previše zajebancije oko nečega šta je jako teško održavati

**Comment by PiweeX** [comment]
ovo nažalost nije moguće izvesti, zatvoriću issue
