### ISSUE TITLE
Igra na hogu

### ISSUE THREAD

**Issue by Viktor023023** [PiweeX/PiweeX#220]
U zadnje vreme hog kao server je malo dosadio, ne mogu da kazem da nije. Ne desavaju se nikakvi eventovi, ratovi i slicno. Predlazem da se nekako to promeni, npr. mozemo organizovati rp ratove koji bi imali smisla i vratili onaj hype kakav je uvek bio. Ko se slaze da treba organizovati neke ratove nakon fixanja hoga neka raguje ili sl.

**Comment by benjamin858** [comment]
ne

**Comment by JedemJaja** [comment]
Ssr nek se cuva, to je sve sto cu da porucim

**Comment by Attack36** [comment]
> Ssr nek se cuva, to je sve sto cu da porucim

You and what army?

**Comment by Attack36** [comment]
Šta se tiće svega ovoga, ja osobno sa djovanijem i staffom rp lige radim na tome
Evo sad smo uveli demokraciju i očekujemo prijedloge da se stave tamo

**Comment by Viktor023023** [comment]
> ### **[benjamin858](/benjamin858) ** commented [18 minutes ago](#issuecomment-1289492324)

ako ti je zanimljivo da smrdis i afkas ceo dan i ne radis nista na serveru ona dobro...

**Comment by RatkoSef** [comment]
> > Ssr nek se cuva, to je sve sto cu da porucim
> 
> You and what army?

This Army.

**Comment by Attack36** [comment]
> > > Ssr nek se cuva, to je sve sto cu da porucim
> > 
> > 
> > You and what army?
> 
> This Army.

Nisi u RP ligi, žalim slučaj

**Comment by PiweeX** [comment]
Poenta je da ne bude eventova, sve je na igračima, vi stvarate svoj kontent ne ograničavamo nikoga i zato sa namerom ne radimo uga buga eventove već to mora da ima neku priču ako se već radi
