### ISSUE TITLE
Invite za državu

### ISSUE THREAD

**Issue by T1GAR** [PiweeX/PiweeX#221]
Bilo bi bolje da se invite za discord servere država moze poslati samo jednom u kanal, a ne kao sto je trenutno. Cim netko posalje invite doleti neki tamo peti pa posalje svoj i tako njegov invite ostaje vidljiv dok se za druge treba scrollat gore i gore da bi se pronasli. Bolje bi bilo da se inviteovi posalju samo jednom i da se na kraj chata stavi poruka npr: Iznad imate države na hogu, scrollajte dok ne pronađete neku koja vam se sviđa ili slicno.

**Comment by JedemJaja** [comment]
Bukv ne znam kako se nitko nije sjetio toga

**Comment by Attack36** [comment]
> Bilo bi bolje da se invite za discord servere država moze poslati samo jednom u kanal, a ne kao sto je trenutno. Cim netko posalje invite doleti neki tamo peti pa posalje svoj i tako njegov invite ostaje vidljiv dok se za druge treba scrollat gore i gore da bi se pronasli. Bolje bi bilo da se inviteovi posalju samo jednom i da se na kraj chata stavi poruka npr: Iznad imate države na hogu, scrollajte dok ne pronađete neku koja vam se sviđa ili slicno.

Već se više takvih issuea otvorili, px ne želi iako dosta ljudi su za

**Comment by PiweeX** [comment]
To nije dobro iz više razloga, to smo hteli na samom početku ali ne vredi kad će ljudi stalno tražiti izmene ako mi npr. ubacimo kroz webhook da se samo 1 pošalje ili ako vođa države dobije samo 1 put permisiju da pošalje želeće izmene, pored toga države se menjaju, uređenja imena ili opisi i bukvalno bi tražili izmene svako malo a nama je cilj automatizacija svega, inače ovako je bolje jer će igrači biti primorani da reklamiraju i da se cimnu 2put dnevno kako bi izreklamirali svoju državu osobama koje tek uđu i budu tagovane automatski od servera kroz welcome poruku
