### ISSUE TITLE
HW mapa za Evropu

### ISSUE THREAD

**Issue by JaSamIgor** [PiweeX/PiweeX#222]
Izgledalo bi puno bolje da se umjesto attack dizajna stavi hw dizajn za Evropu. Trenutno na karti Evrope ne postoji Engleski kanal, Irsko more, Finski zaliv, dio Baltičkog mora i Mramorno more
HW 
![MapaHW](https://user-images.githubusercontent.com/107154813/198876453-144f6895-e0d2-44c5-a6c4-3609b8b30bc1.png)
![AttackEuropa](https://user-images.githubusercontent.com/107154813/198876847-be76553e-1664-43d7-9351-42b1da9184ef.png)
Attack

**Comment by TheFrontView** [comment]
Okej postavio sam bio sinoć predlog Igore. I zaključili smo da nećemo to da radimo. Zbog čega?

Ovako mapa HogWorld i mapa Attack su različitih dimenzija, odnosno mi na trenutnoj mapi uzmemo samo WIN+SHIFT+S i slikamo, ovako bi trebali da ucrtavamo dodatno što može doći do problema na jednoj mapi npr. Engleska ima veću teritoriju, a na drugoj ima manju i onda će stalno dolaziti do pobuna što ne želi ni Attack, a pravo da ti kažem ni ja. Ostavićemo dizajn Attack jedino ako će te da menjate promenićemo sve.
