### ISSUE TITLE
Custom Itemi 

### ISSUE THREAD

**Issue by DzingisKan738** [PiweeX/PiweeX#225]
Kao osoba koja je sudjelovala u hrpi ratova, koja je posjedovala i koja nije imala custom iteme, najvise znam kako custom itemi utjecu na igru.

Najbolji ratovi koje pamtimo bili su ratovi sa Sovjetima, bio je rat s Japanom. Tada nismo imali Custom iteme, svi su imali jednaku opremu, i rat je odnia onaj ko je ima bolju strategiju i ko je ima uvjezbanije ljude.

Custom itemi nisu losa stvar, dokle god ne daju mogucnost igracu da bude iznad svojih mogucnosti. Kao sta su spamklik, ili krvarenje ili poison i slicni efekti. 

Imali smo ogroman problem s Katanom, i dalje imamo, isto tako i borbene sjekire itd...

Govori se o uvodjenju novih itema i jako dobro sam upoznat na princip njihove raspodjele, rada i nacin na koji ce ih se dobivat. 

Moramo zaustavit da ti itemi stignu na server. Jedna osoba biti ce dovoljna da obrise cijelu vojsku, i ta jedna osoba moze biti samo ona koja je na serveru od pocetka jer su ti itemi dostupni onima koji imaju najvise HTokena a to su svote koje uglavnom ljudi iz bete imaju. 

Uvedimo Custom iteme koji nece imat snagu vecu od enchantanog netherite maca, od enchantanog bowa, sjekire, stita... Nek ratovi budu ravnopravni po mogucnostima s opremom. Custom itemi nek sluze da civilizacije imaju nesto sto je vezano za njihov roleplay. 

Primjeri:
Katana - Koreja, Japan
Napadacki Luk - Mongoli, Osmanlije, Kolumbija
Borbene sjekrie - Rusi, Vikinzi, Bardonija
Zaobljeni macevi - Mongoli, Osmanlije, Arapi, Indijci
Longsword - Europske zemlje
Gladius - Grci i Rimljani

Uvedite takve iteme i ne uvodite da imaju ikakve posebne efekte, samo teksture.

**Comment by TheFrontView** [comment]
U istoriji main oružje samuraja bili su lukovi.

**Comment by DjuroGamer** [comment]
Podržavam predlog!

**Comment by NemanjaRusija** [comment]
Zdravo! Ovaj prijedlog je već stavio Attack36 i prihvaćen je. Svaka država će imati rp custom item. Kao katana al prebačen u rp format. Sad Attack36 radi na tome, pravi nove custom iteme koje će se slagati po rp ako se nevaram.

**Comment by DzingisKan738** [comment]
> Zdravo! Ovaj prijedlog je već stavio Attack36 i prihvaćen je. Svaka država će imati rp custom item. Kao katana al prebačen u rp format. Sad Attack36 radi na tome, pravi nove custom iteme koje će se slagati po rp ako se nevaram.

procitaj krviti prvo sta sam napisa, znamo svi da ce se dodat, al isto tako dodaje i krvave tierove i neki itemi ce imat efekte koji ce omogucit jednom liku doslovno da moze savladat petoricu

**Comment by NemanjaRusija** [comment]
Ne znam šta da vam radim nerfovali smo već custom iteme, ali opet ću se savjetovati sa djovanijem šta on misli.

**Comment by Attack36** [comment]
> > Zdravo! Ovaj prijedlog je već stavio Attack36 i prihvaćen je. Svaka država će imati rp custom item. Kao katana al prebačen u rp format. Sad Attack36 radi na tome, pravi nove custom iteme koje će se slagati po rp ako se nevaram.
> 
> procitaj krviti prvo sta sam napisa, znamo svi da ce se dodat, al isto tako dodaje i krvave tierove i neki itemi ce imat efekte koji ce omogucit jednom liku doslovno da moze savladat petoricu

Neće moći savladati petoricu - biti će manji damage ali 1.8 kako bi bio potreban skill u tom stilu inače će biti čak gori od netherite mača, ustvari itemi koji jesu op dan danas su zbog greške koju riješavam. 

Tierovi nisu dobro objašnjeni javnosti jer nisam viziju dovršio niti stavio prvih par itema.

**Comment by Attack36** [comment]
Glavni problem na serveru je to što ima abuse-a i dupliranja usprko stime šta px govori da nema. Mislim to svatko može reči. Kada bih svi itema bilo onoliko koliko treba biti po jačini onda ne bi bilo pola tih problema

**Comment by JaSamIgor** [comment]
Meni je očigledno da će igrači koji duže igraju imati bolju opremu od ostalih. Custom itemi, po meni trebaju imati nešto što ih čini unikatnim, neku sposobnost poput krvarenja, poisona. Ratovi ne mogu biti ravnopravni sa opremom, ti ćes da država koja postoji godinu dana u ratu protiv neke koja je tu par meseci zabraniti korištenje svih njihovih boljih itema kako bi ''bilo ravnopravno'' Ne bi me čudilo da napraviš i za netherite armor predlog da se ne dobija na rewardsu kako bi svi bili ''ravnopravni sa opremom'', ili za bilo šta drugo što ti nemaš. 

kao i inače u tvojim postovima ogromno preuveličavanje

**Comment by JedemJaja** [comment]
> Glavni problem na serveru je to što ima abuse-a i dupliranja usprkos tomu što px govori da nema. Mislim, to svatko može reči. Kada bi svi itema bilo onoliko koliko treba biti po jačini onda ne bi bilo pola tih problema. *

**Comment by JedemJaja** [comment]
I ti pišeš knjigu

**Comment by PiweeX** [comment]
rešeno
