### ISSUE TITLE
Jedan ozbiljan predlog

### ISSUE THREAD

**Issue by 1337macola** [PiweeX/PiweeX#227]
Imam predlog da mi dzelat tim proda jednu vlasku knjigu po ozbiljnoj ceni. Mislim da je to fer i korektno.

**Comment by 1337macola** [comment]
> Imam predlog da mi dzelat tim proda jednu vlasku knjigu po ozbiljnoj ceni. Mislim da je to fer i korektno.

Slazem se sa tvojim predlogom

**Comment by Siu804** [comment]
Ne

**Comment by MrKnedla** [comment]
podrzavam prijedlog (jako sam dobro placen za ovo)

**Comment by 1337macola** [comment]
> Ne

ne slazem se sa tobom

**Comment by 1337macola** [comment]
> podrzavam prijedlog (jako sam dobro placen za ovo)

slazem se sa tobom. Placam dosta.

**Comment by 1337macola** [comment]
> podrzavam prijedlog (jako sam dobro placen za ovo)
Ovaj covek MrKnedla vredi kao 10 ljudi tako da ja mislim da je ovaj predlog prihvacen

**Comment by yamizvaniuchicha** [comment]
slazem se ali jelena karleusa..

**Comment by vukstrale** [comment]
Glasam za!

**Comment by PiweeX** [comment]
Custom itemi se neće dobijati, isključivo preko ključeva će se dobijati jer ovako deluje dosta glupo
