### ISSUE TITLE
IvanBela (TheFrontView)

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#228]

**Comment by TheFrontView** [comment]
![2022-11-07_02 23 08](https://user-images.githubusercontent.com/71612070/200214037-60f8206a-b873-4aa6-ab7b-bb9e69ad998a.png)
![2022-11-07_02 22 58](https://user-images.githubusercontent.com/71612070/200214043-bebc8db8-618d-4434-9233-42853f4e994c.png)

Početak zamka.

**Comment by IvanBela** [comment]
👀👀

**Comment by PiweeX** [comment]
Spawn će biti gotov vrlo uskoro, imali smo više poteškoća kao i obično sve mora po zlu ali svakako spawn će biti isporučen

**Comment by TheFrontView** [comment]
![2022-11-17_21 44 53](https://user-images.githubusercontent.com/71612070/202556039-2cda029a-18ad-4ca8-937f-4e314e9581fc.png)
![2022-11-17_21 44 40](https://user-images.githubusercontent.com/71612070/202556054-11c6c33f-0eb8-40ea-8c07-87c819caf3d0.png)
![2022-11-17_21 44 44](https://user-images.githubusercontent.com/71612070/202556070-de6a886c-5b49-4e5e-95d4-00ab9f1741fd.png)

Polako, ali sugurno.

**Comment by PiweeX** [comment]
gotovo
