### ISSUE TITLE
Mystical mobs predlog

### ISSUE THREAD

**Issue by yamizvaniuchicha** [PiweeX/PiweeX#230]
Mislim da svi znamo da je mystical mobs plugin koji se koristi za nage, posto su pre nage bile drugacije i vise su izgledale na neke zmije, bilobi dobro da ostanu nage spellvačice ali da se vrate nage serpentke ako se slazu svi, i da se doda jos mobova posto je igrica mnogo zabavnija tako

**Comment by PiweeX** [comment]
Radimo na tome

**Comment by PiweeX** [comment]
trenutno radimo na pravljenju modela za neke YT shorts programe tako da možda to završi na Hogu

**Comment by PiweeX** [comment]
radimo
