### ISSUE TITLE
Rp liga

### ISSUE THREAD

**Issue by JedemJaja** [PiweeX/PiweeX#231]
Admini rp lige su neaktivni, attack radi modele cijeli dan, coplek igra samp sa helenom, a crossa nisam vidio ing kolko i oca u stanu. Tamo se odvija teza diskriminacija i potiskivanje te se pravila rade bez glasanja vecine. Sistem je lose osmisljen. O cemu govorim? Naime, svi znate kako "nesmijete ratovati" ako niste dio sekte sto znaci da drzava koja napada, iako postoje dobre motivacije za napad (sirenje teritorija, rp prica, odgovor na provokacije), ako nije clanica nesmije ratovati i napadnutu drzavu se potice na odbijanje rata. Kako da prosiris drzavu, okupis nove vojnike i stvaras roleplay? Ne znam, Bog ti pomogao. Isto tako imamo situaciju sa saudijskom arabijom i asirijom gdje asirija koja je clanica zeli objaviti rat saudijskoj arabiji jer su im usred teritorija btw, to ne moze uciniti jer ova ne zeli postati clanica jer shvaca koliko je slaba i izmice porazu. Nikakvi ratovi nisu organizirani kako je pricano da ce biti i sami discord je neaktivan, discord je ne promoviran po glavnom serveru i sve ide u krasni k. Popravite ligu pod hitno ili sa novim staffom ili sa novim pravilima jer ovako vise ne moze

**Comment by yamizvaniuchicha** [comment]
u potpunosti se slažem

**Comment by T1GAR** [comment]
hear me out. This guy do be spittin facts

**Comment by Siu804** [comment]
UGA BUGA

**Comment by JedemJaja** [comment]
> UGA BUGA

?

**Comment by benjamin858** [comment]
uga buga

**Comment by sartaq** [comment]
> 

Pozdrav kao jedan od clanova staff tima rp lige, trudim se da sto cesce gledam tikete, od mene se odgovor ne ceka puno, dok od ostalih pripovjedaca i mene smori cekanje odgovora, sto se tice predloga za izmjene zakona i svega vezanog za rp ligu, svako ima apsolutno pravo da mi se javi na discordu u dm FarisSpahic #3815, te ako se slazem iskoristiti svu moc da uduvoljim igracima, a ako se ne slazem potrudit cu se da dodjemo do kompromisa!

**Comment by sartaq** [comment]
> 

Svi tiketi su trenutnk pregledani od strane mene, cekamo ostale admine. A coplek vise nije admin!

**Comment by stipefire** [comment]
Kao dio staff-a roleplay lige pokusavam sto cesce gledati tikete ali molio bih da shvatite da smo i mi ljudi i da nemam jednostavno vremena gledati, a i vecina nerazumije proces kako attack i ja radimo sa tiketima posto nas je 3 kao pripovjedaci svako od nas procita i iznese svoje misljenje dali je odbijeno ili ne, posto attack i ja smo cesce zauzeti i nemamo vremena okupimo se jednom u tri dana da rijesimo sve tikete zajedno jer nam je tako lakse. Meni je zao na cekanju ali tako jednostavno radimo ponekad pogledamo ranije ukoliko smo u mogucnosti.  Sto se tice ratova ja bih licno forsirao te ratove ako je dovoljno dobar razlog kao sto je navedeno, ali morate shvatiti da na ovome serveru nije enforsiran roleplay pa se osoba jednostavno nemora pojaviti kada vi njemu objavite rat jer nije pristao na to, zato smo i napravili ligu da se medusobne clanice mogu ratovat sa dogovorom i pisati roleplay, to je tocno slucaj sa asirijom i saudiskom arabijom jao kao staff rp lige tu nemogu nista jer i da asirija nije u rp ligi nece moci ratovati sa njima jer se jednostavno nemoraju pojavit. Da bi se rijesio taj problem trebala bi se uvesti officialna server pravila da ako se ne pojavis dobijes neku kaznu, ali kao sto sam reko ovdje to nije enforsirano te mi ne mozemo nista oko toga. A i u ostalom glavna uloga lige je RP price gdje drzave mogu spajati zajednicki roleplay i pisati ga kao sto se iscekuje prica asirskog carstva i pcf diktata. A ratova nema jer ljudi nezele normalno sjesti i popricati o organizaciji tih ratova, da se iznesu zahtjevi obje strane i da se dode do nekog dogovora.

**Comment by ghost** [comment]
+rep

**Comment by Attack36** [comment]
> Admini rp lige su neaktivni, attack radi modele cijeli dan, coplek igra samp sa helenom, a crossa nisam vidio ing kolko i oca u stanu. Tamo se odvija teza diskriminacija i potiskivanje te se pravila rade bez glasanja vecine. Sistem je lose osmisljen. O cemu govorim? Naime, svi znate kako "nesmijete ratovati" ako niste dio sekte sto znaci da drzava koja napada, iako postoje dobre motivacije za napad (sirenje teritorija, rp prica, odgovor na provokacije), ako nije clanica nesmije ratovati i napadnutu drzavu se potice na odbijanje rata. Kako da prosiris drzavu, okupis nove vojnike i stvaras roleplay? Ne znam, Bog ti pomogao. Isto tako imamo situaciju sa saudijskom arabijom i asirijom gdje asirija koja je clanica zeli objaviti rat saudijskoj arabiji jer su im usred teritorija btw, to ne moze uciniti jer ova ne zeli postati clanica jer shvaca koliko je slaba i izmice porazu. Nikakvi ratovi nisu organizirani kako je pricano da ce biti i sami discord je neaktivan, discord je ne promoviran po glavnom serveru i sve ide u krasni k. Popravite ligu pod hitno ili sa novim staffom ili sa novim pravilima jer ovako vise ne moze

1. Nemaš pojma za aktivnost jer nemaš pogled nad tiketima, trenutačno ima razvijanja i rješavanja njih doslovce smo u prošlih 24 sata riješili nekoliko koja čini većinu trenutnih. Dalje, nema diskriminacije, ti si samo ljut što nisi adekvatan roleplay napisao. Glasanja kanal doslovce postoji i prebačeno je odavno na demokraciju. Svatko tko je član ima pravo dati prijedlog za glasanje piše ti tamo, nisi slijep valjda pogledaj kanale. 

2. Po pravilima RP-lige, države unutar ne smiju ratovati s državama izvan kako bi se omogućilo da je svaki rat po rp-u i da bi se svi mogli priključiti adekvatno u rp drugih te kao motivacija za ljude vani. Uz to po Hogovim pravilima općenito svatko ima pravo odbiti rat ovo nije pravilo za RP ligu samo, već hog. Mi bi htjeli ustvari da se može odrediti casus belli na države kao sistem samo što trenutačno nemamo ljudi koji mogu objektivno odlučiti što je dobar razlog za rat ili ne, jer zna biti komplicirano. Ako imaš ideju za sistem, potrudi se, uđi u ligu, pa daj ideju na glasanje.

3.  Asirija ionako i ovako ne bi mogla objaviti rat po pravilima Hoga i komandi /war, te uz to ono nije usred teritorija, taj dio nisu ni imali sve dok Saudi Arabija nije došla pa su shvatili da im prijeti gubljenje teritorija kojeg su jednog dana planirali uzeti.
Sami su si krivi.

4. Nema ratova jer nema na Hogu općenito kao što nije bilo prije rp lige niti poslije. Ja se trudim s Asircima organizirati ali 90% svih planiranih ratova na Hogu su propali uvijek nije sada zbog roleplay lige. RP liga ne tjera ljude da rade rp, već im daje okolinu kao Hogova institucija da to radi na dobar, kvalitetan način i ima vrlo malo granica te postoji demokracija. Jedna od najvećih granica su godine (12. do 17. max) koje je tu čisto da tehnološki ima sve smisla i tako da mi ne dođe netko u srednjem vijeku protiv nekoga u 21 stoljeću, ali i tu dajemo za dobar RP iznimku. 

5. Općenito RP liga smeta ljudima koji nemaju RP i ciljaju napasti ljude unutar jer ih ne vole zbog stvari na Hogu ne vezano za roleplay. Px je ovo odobrio i ne samo to, RP Liga je razlog zašto je px nabavio alat gdje ljudi mogu pisati knjige za novac koji je sam najavio, te ja planiram postaviti knjigu Raskol tamo. Staff kad je neaktivan u najgorem slučaju kao i za UN jer jebiga radi se. Isto tako jedini koji mogu gledati tiket su pripovjedači te Čoplek nije više jedan od njih. 

Jedina obrana koja ti može biti na sve ovo su pravopisne pogreške koje je napravila osoba koja ne živi u hrvatskoj nekoliko godina i koja uglavnom priča na engleskom u životu van Hoga. Bez uvrede al ne gubi se.

![image](https://user-images.githubusercontent.com/107584200/201542537-058fb289-e0cb-49ec-a183-7b567bcca9e6.png)
![image](https://user-images.githubusercontent.com/107584200/201542568-53b0404b-dd8c-4408-a4e1-8a7ac60cf79a.png)

**Comment by Attack36** [comment]
> Admini rp lige su neaktivni, attack radi modele cijeli dan, coplek igra samp sa helenom, a crossa nisam vidio ing kolko i oca u stanu. Tamo se odvija teza diskriminacija i potiskivanje te se pravila rade bez glasanja vecine. Sistem je lose osmisljen. O cemu govorim? Naime, svi znate kako "nesmijete ratovati" ako niste dio sekte sto znaci da drzava koja napada, iako postoje dobre motivacije za napad (sirenje teritorija, rp prica, odgovor na provokacije), ako nije clanica nesmije ratovati i napadnutu drzavu se potice na odbijanje rata. Kako da prosiris drzavu, okupis nove vojnike i stvaras roleplay? Ne znam, Bog ti pomogao. Isto tako imamo situaciju sa saudijskom arabijom i asirijom gdje asirija koja je clanica zeli objaviti rat saudijskoj arabiji jer su im usred teritorija btw, to ne moze uciniti jer ova ne zeli postati clanica jer shvaca koliko je slaba i izmice porazu. Nikakvi ratovi nisu organizirani kako je pricano da ce biti i sami discord je neaktivan, discord je ne promoviran po glavnom serveru i sve ide u krasni k. Popravite ligu pod hitno ili sa novim staffom ili sa novim pravilima jer ovako vise ne moze

Btw, trenutačno svi tiketi u RP ligi su sređeni 😘

Zamisli zoveš nas sekta a ti si Mr. Knedla. (Šalim se naravno)

_"Čekamo odgovor!"_ - **Staff Roleplay Lige**

**Comment by marepleb** [comment]
> Admini rp lige su neaktivni, attack radi modele cijeli dan, coplek igra samp sa helenom, a crossa nisam vidio ing kolko i oca u stanu. Tamo se odvija teza diskriminacija i potiskivanje te se pravila rade bez glasanja vecine. Sistem je lose osmisljen. O cemu govorim? Naime, svi znate kako "nesmijete ratovati" ako niste dio sekte sto znaci da drzava koja napada, iako postoje dobre motivacije za napad (sirenje teritorija, rp prica, odgovor na provokacije), ako nije clanica nesmije ratovati i napadnutu drzavu se potice na odbijanje rata. Kako da prosiris drzavu, okupis nove vojnike i stvaras roleplay? Ne znam, Bog ti pomogao. Isto tako imamo situaciju sa saudijskom arabijom i asirijom gdje asirija koja je clanica zeli objaviti rat saudijskoj arabiji jer su im usred teritorija btw, to ne moze uciniti jer ova ne zeli postati clanica jer shvaca koliko je slaba i izmice porazu. Nikakvi ratovi nisu organizirani kako je pricano da ce biti i sami discord je neaktivan, discord je ne promoviran po glavnom serveru i sve ide u krasni k. Popravite ligu pod hitno ili sa novim staffom ili sa novim pravilima jer ovako vise ne moze

@coplek mogu sa vama?

**Comment by vukstrale** [comment]
Brate zaposlite InspektoraGavrana

**Comment by MrKnedla** [comment]
> Brate zaposlite InspektoraGavrana

cuj to zaposlite

**Comment by vukstrale** [comment]
> > Brate zaposlite InspektoraGavrana
> 
> cuj to zaposlite

Lik radi besplatno ali vole da zove sve poslom

**Comment by BalkanBlade** [comment]
Losa stvar sto nemozes da menjas imena na akauntu i onda udjes u server

**Comment by vukstrale** [comment]
Da to ne radi (NijeVukTheGreat gejming)

**Comment by PiweeX** [comment]
razumem ovo, Cone je od nedavno postao support i on je veoma aktivan, pored toga danas sam smanjio tim i od osoba što su radili manje uslužne poslove za naš Marketplace sam uklonio sem osoba koje su legalno zaposlene u firmi a od DAO igrača je ostala većina i dželat je trenutno samo Attack koji je neaktivan zbog privatnih obaveza ali će biti
