### ISSUE TITLE
Auto ALT Ban - Plugin

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#233]
Plugin koji će automatski banovati osobe koje naprave alt nalog i ujedno slati kroz webhook obavest na discord

**Comment by ghost** [comment]
Ovo je losa ideja,
Balkanci nemaju statican IP... nama se svaki restart cycle rutera promijeni IP adresa sta znaci da postoji mogucnost da neki igrac dobije istu IP adresu na kojoj je prije igrac igrao... to jest neduzan igrac bi dobio ban jer authme detektira alt-account.

Webhook moze ali treba biti u ovakvom formatu da se ne banaju neduzni igraci:
Spojeni accovi:
Zadnje vrijeme koristenja IP adrese: 
(bez direktnog spominjanja IP adrese jer ono...)

**Comment by DzingisKan** [comment]
> Ovo je losa ideja, Balkanci nemaju statican IP... nama se svaki restart cycle rutera promijeni IP adresa sta znaci da postoji mogucnost da neki igrac dobije istu IP adresu na kojoj je prije igrac igrao... to jest neduzan igrac bi dobio ban jer authme detektira alt-account.
> 
> Webhook moze ali treba biti u ovakvom formatu da se ne banaju neduzni igraci: Spojeni accovi: Zadnje vrijeme koristenja IP adrese: (bez direktnog spominjanja IP adrese jer ono...)

Ip nisu tri znamenke. Šanse da se dogodi isti ip su 0.000001. A i ako se desi onda moze restartat ruter i uc.

**Comment by ghost** [comment]
> > Ovo je losa ideja, Balkanci nemaju statican IP... nama se svaki restart cycle rutera promijeni IP adresa sta znaci da postoji mogucnost da neki igrac dobije istu IP adresu na kojoj je prije igrac igrao... to jest neduzan igrac bi dobio ban jer authme detektira alt-account.
> > Webhook moze ali treba biti u ovakvom formatu da se ne banaju neduzni igraci: Spojeni accovi: Zadnje vrijeme koristenja IP adrese: (bez direktnog spominjanja IP adrese jer ono...)
> 
> Ip nisu tri znamenke. Šanse da se dogodi isti ip su 0.000001. A i ako se desi onda moze restartat ruter i uc.

lol... vidi se da ne razumijes...ti ne kuzis da svaka drzava na svijetu ima ogranicen broj ip-eva koje moze da dodijeljuje korisnicima... 
da se tocnije izrazim ISP kupuje IP adrese od "IANA"-e a isti IP se puno vise zna dogoditi kod drzava kojima jedan ISP vrsi monopol nad ostalima... (npr u Hrvatskoj... Hrvatski Telekom koji ima podfirme npr Optima, BonBon itd) 
DAKLE... ako ISP kupi 10,000 IPeva onda je sansa da dobijes isti ip kao netko drugi koji je u proslosti imao taj IP i igrao na srw znatno veca i apsolutno moguca posto se IP mjenja svaki puta kada resetiras ruter... "A i ako se desi onda moze restartat ruter i uc." nije istina ako te automatski bana znaci bana ti i nick i ip...
zato je u Americi praksa da svaki ruter ima svoj neki staticni IP i ili se mjenja mjesecno ili se uopce ne mijenja sve do kad se ne nazove ISP i zahtijeva se promjena IP adrese. lp.

**Comment by PiweeX** [comment]
> > > Ovo je losa ideja, Balkanci nemaju statican IP... nama se svaki restart cycle rutera promijeni IP adresa sta znaci da postoji mogucnost da neki igrac dobije istu IP adresu na kojoj je prije igrac igrao... to jest neduzan igrac bi dobio ban jer authme detektira alt-account.
> > > Webhook moze ali treba biti u ovakvom formatu da se ne banaju neduzni igraci: Spojeni accovi: Zadnje vrijeme koristenja IP adrese: (bez direktnog spominjanja IP adrese jer ono...)
> > 
> > 
> > Ip nisu tri znamenke. Šanse da se dogodi isti ip su 0.000001. A i ako se desi onda moze restartat ruter i uc.
> 
> lol... vidi se da ne razumijes...ti ne kuzis da svaka drzava na svijetu ima ogranicen broj ip-eva koje moze da dodijeljuje korisnicima... da se tocnije izrazim ISP kupuje IP adrese od "IANA"-e a isti IP se puno vise zna dogoditi kod drzava kojima jedan ISP vrsi monopol nad ostalima... (npr u Hrvatskoj... Hrvatski Telekom koji ima podfirme npr Optima, BonBon itd) DAKLE... ako ISP kupi 10,000 IPeva onda je sansa da dobijes isti ip kao netko drugi koji je u proslosti imao taj IP i igrao na srw znatno veca i apsolutno moguca posto se IP mjenja svaki puta kada resetiras ruter... "A i ako se desi onda moze restartat ruter i uc." nije istina ako te automatski bana znaci bana ti i nick i ip... zato je u Americi praksa da svaki ruter ima svoj neki staticni IP i ili se mjenja mjesecno ili se uopce ne mijenja sve do kad se ne nazove ISP i zahtijeva se promjena IP adrese. lp.

Slažem se međutim svakako ćemo napraviti taj plugin a možda bude korišćen na Hogu testno

**Comment by PiweeX** [comment]
Ovaj plugin će biti gotov početkom Februara
