### ISSUE TITLE
Fixanje

### ISSUE THREAD

**Issue by yamizvaniuchicha** [PiweeX/PiweeX#234]
Marihuana i grozdje da se popravi, i svi ostali bagovi. Čekamo mesecima za marihuanu i groždje i nikako da se popravi.

**Comment by PiweeX** [comment]
Marihuana i grožđe će ukoliko ne bude fixano sad kad popravimo teksture nakon totalnog prebacivanja na 1.19.2 biti skroz uklonjeni sa Hog Decentraland podservera dok ne dodamo svoja semena
