### ISSUE TITLE
Rudolfa ostavila devojka

### ISSUE THREAD

**Issue by yamizvaniuchicha** [PiweeX/PiweeX#236]
Rukija je ostavila cura i sad mu je mala kura, nego px mu je oduzeo 850k a rudolf je crncuga nedelju dana ih je skupljao. PETICIJA DA SE VRATE STVARI
(svi glasajte za da)

**Comment by marepleb** [comment]
da

**Comment by JedemJaja** [comment]
Nista od toga, jedina solucija je da postaje gej #IStandWithRudolf🏳️‍🌈

**Comment by Steva120** [comment]
> 

Da

**Comment by PiweeX** [comment]
Rešićemo, prvo da rešimo probleme zbog kojih ulaze, juče su streserom 10k puta pokušali i par puta uspeli
