### ISSUE TITLE
Dodati nove stvari u shop

### ISSUE THREAD

**Issue by Steva120** [PiweeX/PiweeX#237]
Treba da se dodaju potioni ili stvari sa kojima se potioni mogu napraviti. Blaze rodove, fermented spider eye, rabit's foot, magma cream, ghast tear, spider eye. Isto tako mogli bi da dodate stvari koje je Major trazio jos pre nego sto je quitovo. A to su nether itemi, drveca iz nethera, nether brickovi, netherack i jos stvari. Dodati jos nekog custom moba poput Nage,ali da se ne spawna tako puno i da dropa dobar loot. Nage su se previse spawnale i svi sad imaju mnogo koplja. Popraviti bug sa grozdjem i marihuanom koji je tu vec dugo i nije fixan.

**Comment by TheFrontView** [comment]
👎

**Comment by benjamin858** [comment]
👎
