### ISSUE TITLE
Dodati nove stvari u Shop

### ISSUE THREAD

**Issue by Brankeza** [PiweeX/PiweeX#238]
Dodati med na prodaju sace na prodaju i kosnice na prodaju i da na tezgi bude Pcelar NPC #237

**Comment by Siu804** [comment]
👎

**Comment by TheFrontView** [comment]
👎

**Comment by PiweeX** [comment]
med deluje kao dobra ideja možda

**Comment by PiweeX** [comment]
MED DODAT! Cene su smanjene za većinu stvari poput rude bakra koja bi potencijalne hakere obogatila brzo a med je trenutno sa najvećom vrednošću i to je super potez, hvala Brankezi za predlog 👍🏻👍🏻👍🏻👍🏻👍🏻👍🏻
