### ISSUE TITLE
Neke osobe mogu biti trustane samo u 1 land

### ISSUE THREAD

**Issue by T1GAR** [PiweeX/PiweeX#239]
Ovo se događa vec duže vrijeme i stvarno zakomplicira stvari kada nekom novom igracu pokazujete gradove gdje da radi i slicno a kao i ostalim igracima koji su vec igrali. pls fix

**Comment by Siu804** [comment]
Valjda treba samo duze da igra kako bi mogao uci u vise landova

**Comment by PiweeX** [comment]
Ovo je verovatno jer je starim igračima sačuvalo srarije permisije, potrudiću se da fixam čim se setim i stignem

**Comment by marepleb** [comment]
skill issue

**Comment by PiweeX** [comment]
Rešio sam problem sa permisijama sinoć tako da je i predpostavljam rešeno,  

glavni problem koji sam primetio jeste da su igrači mogli da prave više landova tako da imamo npr Djonmla1 Djonmla2 Djonmla3 Nederite2 Nederite15 itd landova što je haos na mapi ali je to rešeno sad ovim podešavanjima
