### ISSUE TITLE
Dželati i problemi

### ISSUE THREAD

**Issue by yamizvaniuchicha** [PiweeX/PiweeX#241]
Svi znamo da je server trenutno u jako lošem stanju zbog upada na naloge i ddosanja itd.
Da se doda jos minimum 2 dželata koji će da pomognu igračima dok developeri popravljaju server, nadam se da će se i ostali složiti…

**Comment by PiweeX** [comment]
odgovorio sam o ovome u nekom od predhodnih issuea po sličnoj temi, uglavnom zatvoriću ovaj sad
