### ISSUE TITLE
ChatItem Plugin

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#243]
Plugin koji će omogućavati igračima da pokažu svoju stvar u ruci celom serveru u četu

**Comment by PiweeX** [comment]
moj prvi kod lol

import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.plugin.java.JavaPlugin;

public class ItemShowPlugin extends JavaPlugin {

  @Override
  public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
    if (command.getName().equalsIgnoreCase("item")) {
      if (sender instanceof Player) {
        Player player = (Player) sender;
        ItemStack item = player.getInventory().getItemInMainHand();
        ItemMeta meta = item.getItemMeta();
        String itemName = ChatColor.BLUE + meta.getDisplayName();
        String itemLore = ChatColor.GRAY + meta.getLore().toString();
        player.sendMessage(itemName + ": " + itemLore);
        return true;
      }
    }
    return false;
  }

}

**Comment by PiweeX** [comment]
posle par sati gotovo valjda, bar nema errora

package testt.testt;

import org.bukkit.ChatColor;
import org.bukkit.command.Command;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.ItemMeta;
import org.bukkit.plugin.java.JavaPlugin;

public class ItemShowPlugin extends JavaPlugin implements CommandExecutor {
    @Override
    public boolean onCommand(CommandSender sender, Command command, String label, String[] args) {
        if (command.getName().equalsIgnoreCase("item")) {
            if (sender instanceof Player) {
                Player player = (Player) sender;
                ItemStack item = player.getInventory().getItemInMainHand();
                ItemMeta meta = item.getItemMeta();
                String itemName = ChatColor.BLUE + meta.getDisplayName();
                String itemLore = ChatColor.GRAY + meta.getLore().toString();
                player.sendMessage(itemName + ": " + itemLore);
                return true;
            }
        }
        return false;
    }

    @Override
    public void onEnable() {
        getCommand("item").setExecutor(this);
    }
}

**Comment by Master0fFate** [comment]
Sve je to super ali zasto govoris da je to "tvoj kod" ako je ocito generiran od strane ChatGPT-a...
Ukucao sam ovo "Can you write me a Java code for Minecraft Bukkit 1.19.3 that will allow players to show their item in hand to the entire server in the chat"

i dobio sam van apsolutno isti kod...
i ne nije "slucajnost" jer se kod mogao 

1. drugacije formatirati
2. itemName, itemLore drugacije formatirati
3. player.sendMessage promijeniti

a ne ovo je 1/1 copy paste iz ChatGPT

**Comment by vukstrale** [comment]
> Sve je to super ali zasto govoris da je to "tvoj kod" ako je ocito generiran od strane ChatGPT-a... Ukucao sam ovo "Can you write me a Java code for Minecraft Bukkit 1.19.3 that will allow players to show their item in hand to the entire server in the chat"
> 
> i dobio sam van apsolutno isti kod... i ne nije "slucajnost" jer se kod mogao
> 
> 1. drugacije formatirati
> 2. itemName, itemLore drugacije formatirati
> 3. player.sendMessage promijeniti
> 
> a ne ovo je 1/1 copy paste iz ChatGPT

lol gle stvarno (ja totalno ne koristim ChatGPT da mi radi domaći iz programiranja)

**Comment by PiweeX** [comment]
Premesteno u poseban issue za sve plugine
