### ISSUE TITLE
StevChat

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#249]
Obzirom da smo se prebacili na 1.19.2 a uskoro i na 1.19.3 pošto je u međuvremenu izašao a DeluxeChat ne radi update već 2 godine moramo napraviti neku zamenu

**Comment by PiweeX** [comment]
Na seqrveqru sam, plugin za cet za 1.19.3 ne radi ni kad se doda Essentials Chat.. pravimo plugin nas a ime ce biti StevChat (igrqac\i izglasali)

**Comment by Steva189** [comment]
> Na seqrveqru sam, plugin za cet za 1.19.3 ne radi ni kad se doda Essentials Chat.. pravimo plugin nas a ime ce biti StevChat (igrqac\i izglasali)

LMG

**Comment by PiweeX** [comment]
Premesteno u poseban issue za sve plugine
