### ISSUE TITLE
Tekstura Servera

### ISSUE THREAD

**Issue by TheFrontView** [PiweeX/PiweeX#250]
Teksturu koju smo koristili do skorijeg vremena bila je zanimljiva po prilično. No teksturu koju bih ja stavio jeste

Faithfull 64x. Tekstura se drži default Minecraft stila no samo lepše ko je upoznat s teksturama definitvno zna teksturu.

![2022-12-12_12 27 22](https://user-images.githubusercontent.com/71612070/207034089-d31f2434-0a6b-415b-8ec5-06abba3ef9a5.png)

Jedino što bih popravio je dodao s trenutne teksture lišće i pšenicu.

**Comment by Lava1-7** [comment]
Slazem se iskreno, tekstura je jako lepo definisana svojom 64x64 rezolucijom i iskreno ne bih drugu 64x64 teksturu preporucio.

**Comment by marepleb** [comment]
crko bi mi pc da to ubacim

**Comment by PiweeX** [comment]
Obaveštavam i ovde da je problem sa teksturom za 1.19.3 rešen i da napokon imamo teksturu na Decentralandu ali i na SkyBlocku koji uskoro izbacuje betu
