### ISSUE TITLE
BiomeEdit

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#254]
Plugin koji čekamo već mesecima da izađe za 1.18.2 prvo.. napokon ćemo ga mi napraviti, nećemo čekati update. Ko se seća igre u beti laputa i njeno nebo je imalo svoju posebnu boju, uz to trava i lišće, bili su u hex codeovima i bilo je neverovatno dobro

**Comment by marepleb** [comment]
jase secam

**Comment by PiweeX** [comment]
Premesteno u poseban issue
