### ISSUE TITLE
Black Market/ predlog

### ISSUE THREAD

**Issue by Brankeza** [PiweeX/PiweeX#256]
Dodati beehive/bee nest u black market sa 2 do 3 pcele u njoj
Jer neki igraci ne znaju kako naci/dobiti pcele jer se na decentralandu u prirodi veoma tesko nalaze 

Medjutim postoji metoda kako ih dobiti ali za to nam treba 1x sapling 1x cvet(mora biti cvet visine 1 bloka) i bone meal stavite cvet pored saplinga (birch ili oak sapling nikako ostali) i bone meal-ate sapling sve dok ne dobijete kosnicu na drvetu, medjutim za to postoji samo 2% i treba strpljenja i vremena za to

**Comment by PiweeX** [comment]
videćemo za to, nema nekog smisla da se pčele kupuju u black shopu, možda kroz vote ili slično

**Comment by PiweeX** [comment]
black market je srušen, svi znaju kad su osobe sa Atlasa upale i srušile laputu i to, laputu smo uspeli da vratimo kroz par sekundi ali black market je otišao, žao mi je zbog toga ali neće biti vraćan jer ćemo napraviti baš kao što smo hteli i kroz beta fazu, to da na random mestima na laputi bude lepo raspoređeno svako mesto za prodaju. Možda je i tako bolje, mislim da čak zapravo i jeste, žao mi je samo djomle i djovanija koji su gradili taj shop danima a žao mi je i osoba sa atlasa, samo nek oni rade svoj posao a mi ćemo svoj
