### ISSUE TITLE
predlazem uvodjenje marihuane na blackshop

### ISSUE THREAD

**Issue by muvstpondrugz** [PiweeX/PiweeX#260]
uvesti npca blackshop koj bi prodavao marihuanu cena: po steku:5k+ takodje preporucujem da se npc zove narkoman ili mister droga

**Comment by Brankeza** [comment]
> 

Recimo da stoji uza nekog coska i diluje

**Comment by muvstpondrugz** [comment]
dobra ideja

**Comment by HoseArmando** [comment]
Maybe yes maybe no

**Comment by marepleb** [comment]
5k je malo marihuana je op

**Comment by PiweeX** [comment]
marihuana se neće vraćati na server u funkcionalno stanje jer jako laguje server
