### ISSUE TITLE
/hat Komanda na Decentralandu

### ISSUE THREAD

**Issue by TheFrontView** [PiweeX/PiweeX#264]
/hat komanda se trenutno jedino može koristiti ako se kupi rank, /hat komanda može pomoći oko roleplaya i zato moje mišljenje je da treba da se stavi da može svako da je koristi, ili da se dobija na satima igre npr. 7 dana igranja da se dobija.

**Comment by Siu804** [comment]
Slazem se

**Comment by PiweeX** [comment]
meni se sviđa predlog, izglasajte samo i dodajemo, možda neće biti na 7 dana igre ali tipa na 20 hoće

**Comment by Lava1-7** [comment]
Slazem se, mogao bih da stavim nesto da izgleda ko **dildo** na glavi.

**Comment by mqqtko** [comment]
Najjbolje ceo king free

**Comment by PiweeX** [comment]
Uskoro dodajemo hat komandu na rewards jer se rewards proširuje na drugu stranu pošto su mnogi stari igrači stigli do podmornice i otključali sve, podmornica je uklonjena kao i dobijanje svetlo plave boje ali uskoro stiže 8 novih setova armora.

Od boljih:

Amethyst Armor
Ruby Armor
Onyx Armor
Orax Armor

Od lošijih ali boljih za RP tačnije armori koje će imati igrači koji su noviji:

Tunic armori

**Comment by Stamenko85** [comment]
uz to imam pitanje,da li ces dodati neke custom oruzija koja ce moci da se kraftaju?

**Comment by PiweeX** [comment]
> uz to imam pitanje,da li ces dodati neke custom oruzija koja ce moci da se kraftaju?

Da
