### ISSUE TITLE
Px debilcino

### ISSUE THREAD

**Issue by Zav1637** [PiweeX/PiweeX#265]
Kad sam ti reko d ace atlas biti popularniji od tvog usranog hoga reko si mi da ne jedem govna e sada vidis da je pre 2 dana na atlasu bilo 130 igraca ....
Danas je hogu dnevni nivo 4 igraca cestitam na uspehu i tvoji spijuni na atlasu takodje .

**Comment by Relja123Ez** [comment]
jedi govna

**Comment by Zav1637** [comment]
> 

Jbg nisam ja px pa da ih gutam

**Comment by PiweeX** [comment]
Jebiga ja nisam dovoljna mentalna gromada kao Fropik pa da se uvlačim osobi koja mi ddosuje server kako bih bio bolji od Hoga.. :D

![download](https://user-images.githubusercontent.com/33425430/214336017-7c9866cd-1768-47b2-9f52-b6f305b32d54.png)

**Comment by marepleb** [comment]
> Kad sam ti reko d ace atlas biti popularniji od tvog usranog hoga reko si mi da ne jedem govna e sada vidis da je pre 2 dana na atlasu bilo 130 igraca .... Danas je hogu dnevni nivo 4 igraca cestitam na uspehu i tvoji spijuni na atlasu takodje .

bezi bre jebem li ti boga

**Comment by PiweeX** [comment]
Ne psuj Boga
