### ISSUE TITLE
Poboljsanje servera (ignorisite svi sem px-a)

### ISSUE THREAD

**Issue by yamizvaniuchicha** [PiweeX/PiweeX#266]
Stvari koje bih ja uradi:
1. Popravio spawn- Laputa je super i zanimljivo je sem sto bi mogla da se obnovi posto je pola spawna sruseno, da spawn ostane na laputi ali da se premesti na drugo mesto takodje da se sve iznad lapute ono random srusi i da se ne moze vise postavljati.
2. Da se poprave svi plugini-
Dosta plugina je out-dateovano i da se nameste svi na 1.19.3 verziju i oraxen plugin da se popravi takodje posto imaju bagovi sa texturama.
3. Da se poprave texture-
Runic itemi nemaju texturu takodje i naga koplje i jos par stvari i itemi iz oraxena su pokvareni imaju drugacije texture.
4. Da se dodaju mobovi-
Mythic mobs plugin je kvalitetan i ima raznih mobova koji mogu da se dodaju da bi dodali zabavu u igru
5. Da se namesti TAB-
posto se rankovi ne prikazuju lepo da se namesti to i tipa da se dodaju neki detalji da se ulepsa i sa tipa na playtimeu 50 dana igraci dobijaju ljubicasto ime na tabu i rank aktivan il tako nesto
6. Texture promena-
da se ulepsaju texture da ostanu lake al da se dodaju detalji i da se urade druge teksture za ostale armore ne samo netherite
7. Jos modova-
rl craft da se vrati i jos nesto kvalitetno da se doda
8. Jos custom itema-
novi custom itemi koji se prave po packovima
9. Recepti-
da se dodaju recepti za neke custom iteme i za enchanted golden applove
10. Nether-
poboljsao bi igru u vise smisla 
11. Shop da se vrati-
mnogi bi mislili da je shop p2w ali ako je legalan bilo bi skroz uredu da se vrati shop

**Comment by marepleb** [comment]
ne seri

**Comment by Relja123Ez** [comment]
> 

**slazem se sa par stvari ali ono spawn i shop su prosto glupe ideje**

**Comment by Master0fFate** [comment]
> ne seri

+
