### ISSUE TITLE
Klijent predlog

### ISSUE THREAD

**Issue by TheFrontView** [PiweeX/PiweeX#267]
Da PiweeeX udruži bandu i da se napravi Hogo Client na foru kao lunar, samo što je Hogov i uvek pokazuje hogrealms server. Reklamiramo ga i postanemo milionera. Slava Rusiji.

**Comment by PiweeX** [comment]
Slava Rusiji

**Comment by PiweeX** [comment]
xd

**Comment by PiweeX** [comment]
objavio sam vest pre par meseci da radimo na launčeru, ali on ima za svrhu da mac banujemo igrače da ne mogu da prave altove

**Comment by marepleb** [comment]
> Da PiweeeX udruži bandu i da se napravi Hogo Client na foru kao lunar, samo što je Hogov i uvek pokazuje hogrealms server. Reklamiramo ga i postanemo milionera. Slava Rusiji.

inace ja sam vec krenuo to da radim

**Comment by konfix** [comment]
> objavio sam vest pre par meseci da radimo na launčeru, ali on ima za svrhu da mac banujemo igrače da ne mogu da prave altove

kopiras Mystic launčer gde ti je dostojanstvo

**Comment by TheFrontView** [comment]
> > objavio sam vest pre par meseci da radimo na launčeru, ali on ima za svrhu da mac banujemo igrače da ne mogu da prave altove
> 
> kopiras Mystic launčer gde ti je dostojanstvo

Što nam nisi palamudio pre 6 meseci da kopiramo, a ne sada?

**Comment by konfix** [comment]
> > > objavio sam vest pre par meseci da radimo na launčeru, ali on ima za svrhu da mac banujemo igrače da ne mogu da prave altove
> > 
> > 
> > kopiras Mystic launčer gde ti je dostojanstvo
> 
> Što nam nisi palamudio pre 6 meseci da kopiramo, a ne sada?

mystic launcer je sprdnja jer me je px zajebavao za to, sad vi isto pravite i boli me kurac iskreno ne znam zasto se ti javljas uopste

**Comment by NemanjaRusija** [comment]
> > > > objavio sam vest pre par meseci da radimo na launčeru, ali on ima za svrhu da mac banujemo igrače da ne mogu da prave altove
> > > 
> > > 
> > > kopiras Mystic launčer gde ti je dostojanstvo
> > 
> > 
> > Što nam nisi palamudio pre 6 meseci da kopiramo, a ne sada?
> 
> mystic launcer je sprdnja jer me je px zajebavao za to, sad vi isto pravite i boli me kurac iskreno ne znam zasto se ti javljas uopste

evo ja se javljam

**Comment by PiweeX** [comment]
> > > > objavio sam vest pre par meseci da radimo na launčeru, ali on ima za svrhu da mac banujemo igrače da ne mogu da prave altove
> > > 
> > > 
> > > kopiras Mystic launčer gde ti je dostojanstvo
> > 
> > 
> > Što nam nisi palamudio pre 6 meseci da kopiramo, a ne sada?
> 
> mystic launcer je sprdnja jer me je px zajebavao za to, sad vi isto pravite i boli me kurac iskreno ne znam zasto se ti javljas uopste

Mi smo launčer najavili još na leto jer nam je bitan zbog mac bana.. nikog nismo iskopirali
