### ISSUE TITLE
Px debilcino 2 jebo sam te

### ISSUE THREAD

**Issue by Zav1637** [PiweeX/PiweeX#268]
PX DEBILCINO I HOG SU TI GRIFOVALI ODE SVE U PICKU MATERINU KAD SMO TI SVI PRICALI TI SLUSO NISI SAD SMRDLJAS U KUCI U LAZAREVCU I CEKAS DA TI UDJE 2 IGRAC NA SERVER SAMO ATLAS SPIJUNIRAS CEO DAN PAMETNIJA POSLA NEMAS NEMAS JEBEM LI TE GROMADO STO BI REKO !!!  

POZDRAVLJA TE TVOJ DRUGAR ZAV!!!

**Comment by marepleb** [comment]
> PX DEBILCINO I HOG SU TI GRIFOVALI ODE SVE U PICKU MATERINU KAD SMO TI SVI PRICALI TI SLUSO NISI SAD SMRDLJAS U KUCI U LAZAREVCU I CEKAS DA TI UDJE 2 IGRAC NA SERVER !!!!
> 
> POZDRAVLJA TE TVOJ DRUGAR ZAV!!!

bezi jebem ti 9 majki

**Comment by konfix** [comment]
mašala

**Comment by Zav1637** [comment]
Evo javlja se 1 od 4 igraca na hogu

**Comment by frop1k** [comment]
alhamdullilah

**Comment by Zav1637** [comment]
Fropik owner hoga je debil ili ti "gromada" sto bi on reko

**Comment by marepleb** [comment]
> mašala

sto si me ban brt

**Comment by Zav1637** [comment]
Nek je

**Comment by frop1k** [comment]
> Fropik owner hoga je debil ili ti "gromada" sto bi on reko
težak milione

**Comment by Zav1637** [comment]
Istina..

**Comment by konfix** [comment]
> > mašala
> 
> sto si me ban brt

dosmanlije su nisam ja

**Comment by PiweeX** [comment]
Pozdrav za dosovce!

Vidimo se kad mainnet krene 👍🏻

**Comment by Zav1637** [comment]
Sta kad krene?

**Comment by Zav1637** [comment]
I to ce ti sruse najavljujes to vec 2 god aj idi otusiraj se nekad u smrdljari u lazarevcu trovu

**Comment by konfix** [comment]
vidimo se na mystic launčer

**Comment by Zav1637** [comment]
Mystic launcer !!! 

Px duvaj

**Comment by marepleb** [comment]
> I to ce ti sruse najavljujes to vec 2 god aj idi otusiraj se nekad u smrdljari u lazarevcu trovu

mali jebo sam ti majku

**Comment by frop1k** [comment]
UDBA napala hogov sistem, država protiv jednog čoveka!! Zola sam protiv svih

**Comment by PiweeX** [comment]
svi napadi koji se vrše protiv mene i moje porodice su samo ogledalo vas a i mene. Bolje je da me prozivate nego da me takvi poput vas hvale.

Samo vi radite svoj posao
