### ISSUE TITLE
Mapa

### ISSUE THREAD

**Issue by TheFrontView** [PiweeX/PiweeX#270]
Da se ubaci nov dizajn za mapu. 
![MapatestEuropa](https://user-images.githubusercontent.com/71612070/215622812-6027849c-f2d0-4f5f-985a-a9cdeb4062ef.png)
![Mapatest](https://user-images.githubusercontent.com/71612070/215622816-5bdc1c4c-0493-42e8-8f30-29532b0a7636.png)

Ako vam se svidja glasaj te 👍, ako ne onda 👎

**Comment by PiweeX** [comment]
Meni se sviđa

**Comment by yamizvaniuchicha** [comment]
da

**Comment by Skeledzija** [comment]
ne bruh meni se ne svidja

**Comment by NemanjaRusija** [comment]
meni se sviđa

**Comment by TheFrontView** [comment]
> ne bruh meni se ne svidja

Da li imaš neku prepuruku šta da se popravi?

**Comment by PiweeX** [comment]
Kako bi izgledalo kada bi se dodala neka država na tu kartu? Mislim kakav izgled

**Comment by PiweeX** [comment]
implementirano je, video sam primer karte sa državama na njoj juče i sviđaju mi se boje, puno je lepša od predhodne
