### ISSUE TITLE
Mapa za hog v2

### ISSUE THREAD

**Issue by yamizvaniuchicha** [PiweeX/PiweeX#272]
![mapatemplate](https://user-images.githubusercontent.com/114116218/217096993-a1e1be36-c3aa-4e89-8d11-1d766ed641e6.jpg)
Predlog za template mape (rezolucija je inace mnogo veca sem sto je file 16mb pa git hub ne dozvoljava da postavim)
Ko se slaze nek odgovori

**Comment by Relja123Ez** [comment]
Ova mapa je iskreno najjaca, ko se slaze on je bog.

**Comment by yamizvaniuchicha** [comment]
> Ova mapa je iskreno najjaca, ko se slaze on je bog.

Rispekt

**Comment by Stamenko85** [comment]
Voda  mi se nesvidja ostalo je top

**Comment by TheFrontView** [comment]
A ono nije loš dizajn prednost je što ti imaš antartik ja na svojoj nemam

Voda izgleda kao:

Ocean texture Ultra HD resolution download

I možda da popraviš senke da bolje izgledaju.

**Comment by Master0fFate** [comment]
Mapa je apsolutno smece, ne samo da si skinuo mapu s neta i samo stavio Clipping mask na vodu i na zemlju i to slike zali boze, nego si jos stavio mapu koja je apsolutno smece za mappanje... a.k.a. svaki moguci otok ima cak i neki nebitan koji ne postoji u minecraftu zbog same velicine koja kad se translatira u minecraft je jednaka NULI.
Ocjena -10/10 brisi ovo, sramotno je iskreno a i sramotno je koliko ljudi kaze da je "top" itd, pa ajde neka oni onda ucrtavaju na tu mapu teritorije pa da vidimo koliko dugo ce im biti "top"

**Comment by yamizvaniuchicha** [comment]
> Mapa je apsolutno smece, ne samo da si skinuo mapu s neta i samo stavio Clipping mask na vodu i na zemlju i to slike zali boze, nego si jos stavio mapu koja je apsolutno smece za mappanje... a.k.a. svaki moguci otok ima cak i neki nebitan koji ne postoji u minecraftu zbog same velicine koja kad se translatira u minecraft je jednaka NULI.
> Ocjena -10/10 brisi ovo, sramotno je iskreno a i sramotno je koliko ljudi kaze da je "top" itd, pa ajde neka oni onda ucrtavaju na tu mapu teritorije pa da vidimo koliko dugo ce im biti "top"

Misljenje neko osobe toliko glupo kao sto si ti mi uopste ne treba, onaj ko treba taj zna kako se treba raditi sa mapom i sa razlogom su napravljeni otoci, izmene su se vec izvele a ne kenjaj previse jer mapa s neta nije okean jeste al jok odakle da uzmem, da odem i da slikam? Promenjen je i on al svejedno izpalamudio si se samo ko retard najgori

**Comment by yamizvaniuchicha** [comment]
![predlog3](https://user-images.githubusercontent.com/114116218/217378634-82cc862a-d2e7-4105-9879-857d7e1b31f4.jpg)
Up date-Poboljsan okean i dodat saturation na kopno

**Comment by T1GAR** [comment]
> 

Wdym? Lik je iznio facts ovdje a i opcenito ih iznosi. Realno je rekao probleme sa kojim se i slažem. I nemoj brinut on je jedan od onih "ko treba taj zna kako se treba raditi sa mapom"...

**Comment by yamizvaniuchicha** [comment]
> Wdym? Lik je iznio facts ovdje a i opcenito ih iznosi. Realno je rekao probleme sa kojim se i slažem. I nemoj brinut on je jedan od onih "ko treba taj zna kako se treba raditi sa mapom"...

Takodje postoji drugi nacin da to kaze, ne brinem veruj mi i sta mene boli kita da li on to radi ili ne, trenutna mapa ne izgleda ni nasta i bio bi red da se promeni, i da zna sta treba da se radi takodje bi znao da otoke mozes obojiti bez da urnises mapu, cenim kritike ali ponasanje ne tolerisem

**Comment by PiweeX** [comment]
prihvatili smo Frontov predlog, zatvoriću issue
