### ISSUE TITLE
Viking Spawn for MCVIKINGAI.LT (Front) 

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#273]
![2023-02-09_02 40 57](https://user-images.githubusercontent.com/33425430/217867447-5958eb58-2be8-41a6-a82c-a3aabb96035c.png)
![2023-02-09_02 48 12](https://user-images.githubusercontent.com/33425430/217867504-92701c25-933c-4944-bbdb-e5b28e302168.png)
![2023-02-09_10 59 59](https://user-images.githubusercontent.com/33425430/217867553-e5e90e93-2964-403c-8913-8f365b5d674a.png)
![2023-02-09_11 22 17](https://user-images.githubusercontent.com/33425430/217867589-09b58fdc-cbc1-47f4-9a23-e9e2ed213276.png)
![2023-02-09_01 46 12](https://user-images.githubusercontent.com/33425430/217867635-2034efdb-de7e-4ff4-993b-fb071ce2d461.png)

**Comment by PiweeX** [comment]
Ostalo je još putevi kula selo i sve one stvari, i brodovi da se ulepšaju kako Front kaže

**Comment by PiweeX** [comment]
Realno vrhunski izgleda. Inače ovo je 700x700 a ne 150x150 spawn kakav je trebao da bude tako da eto

**Comment by PiweeX** [comment]
![Uploading 2023-02-11_13.37.08.png…]()

Dvorac je gotov još selo

**Comment by PiweeX** [comment]
![2023-02-11_13 37 08](https://user-images.githubusercontent.com/33425430/218258609-f8aa084f-7b6f-4c6b-9070-0811a61472c2.png)

**Comment by TheFrontView** [comment]
![2023-02-11_13 46 47](https://user-images.githubusercontent.com/71612070/218262507-66630912-0540-47fb-adba-700a92e80aa2.png)

Polako završavamo build sa selom.

**Comment by PiweeX** [comment]
![Screenshot_2023-02-12-20-56-48-925_com discord](https://user-images.githubusercontent.com/33425430/218335345-6b8ddc4b-d9b6-457c-b753-3499402329bc.jpg)
![Screenshot_2023-02-12-20-56-46-036_com discord](https://user-images.githubusercontent.com/33425430/218335347-bb414a42-089b-4852-8d42-2b651b6e58d0.jpg)
![Screenshot_2023-02-12-20-56-43-144_com discord](https://user-images.githubusercontent.com/33425430/218335349-5f9b6161-cd8e-4f16-9c8b-cd385386e0b2.jpg)

**Comment by PiweeX** [comment]
Ende

**Comment by PiweeX** [comment]
Gotovo*
