### ISSUE TITLE
Da se vrati stari plugin za cepanje drva

### ISSUE THREAD

**Issue by Stamenko85** [PiweeX/PiweeX#276]
razlozi:
1. nedobija se skill sumarstvo
2. lisce ostaje u nebu
3. lisce nece da opadne
4. nekad se zabaguje i nece celo drvo da se srusi
5. dobija se manje drveta nego sto treba
6. jako malo se dobija seplinga i mnogo se dobija lisca

**Comment by PiweeX** [comment]
To se sjebalo zbog 1.19.3 ali vratićemo obavezno

**Comment by PiweeX** [comment]
vraćeno!
