### ISSUE TITLE
TOYS BOX for Cash & Nico youtubers (Front)

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#278]
so the next project is a toy store, idk if you have seen toy story but it's kinda like this. I wanna make it so that we start off in a toy box and we have to escape it, then we have to do different challenges to escape the toy store.

https://youtu.be/SNPgDWiMIqI?t=89

**Comment by PiweeX** [comment]
instrukcije
[Minecraft_But_Were_Trapped_Inside_a_Toy_Store_build.docx](https://github.com/PiweeX/HogRealms/files/10711002/Minecraft_But_Were_Trapped_Inside_a_Toy_Store_build.docx)


hey btw for the toy store build, this is the look I'm kinda looking for
https://youtu.be/kHq2OzdEBdU

**Comment by TheFrontView** [comment]
![2023-02-12_21 46 07](https://user-images.githubusercontent.com/71612070/218336134-77bda2da-9257-493b-990a-5383c76975a8.png)
![2023-02-12_21 35 41](https://user-images.githubusercontent.com/71612070/218336136-da52ca5d-eb30-4d99-8d50-04f3aa8efc50.png)
![2023-02-12_21 43 53](https://user-images.githubusercontent.com/71612070/218336137-9894b492-bd63-4cc9-b9a5-6c6556d45fc2.png)

Starting shelf design.

**Comment by TheFrontView** [comment]
![2023-02-12_21 52 40](https://user-images.githubusercontent.com/71612070/218336507-8144e2c5-858f-4338-b8f8-1f0e64b20d18.png)

**Comment by TheFrontView** [comment]
![2023-02-13_19 15 20](https://user-images.githubusercontent.com/71612070/218539757-5916786e-7103-4347-a418-b3368997642a.png)
![2023-02-13_17 42 47](https://user-images.githubusercontent.com/71612070/218539774-36c80fe1-3958-47d7-95d7-4c6c25cde3da.png)
![2023-02-13_17 57 09](https://user-images.githubusercontent.com/71612070/218539790-cd23f4c0-3f8d-485e-8462-dc8d915a1aca.png)
![2023-02-13_19 01 30](https://user-images.githubusercontent.com/71612070/218539799-efd250fb-76cd-4bd1-baf9-96a23da994e5.png)

Started from looking horible to actualy cute thing 😂

**Comment by PiweeX** [comment]
gotovo pa ću zatvoriti
