### ISSUE TITLE
Trapped in a Haunted House in Minecraft for Water#7074 (Fqzon)

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#279]
Trapped in a Haunted House in Minecraft!  - and then just more challenge rooms inside like usual

**Comment by jaydubdev** [comment]
instructions
[Trapped in a Haunted House in Minecraft! build.docx](https://github.com/PiweeX/HogRealms/files/10715833/Trapped.in.a.Haunted.House.in.Minecraft.build.docx)

**Comment by Fqzoon** [comment]
![2023-02-13_15 08 22](https://user-images.githubusercontent.com/113377506/218480580-beb5155b-4f8c-49ad-a4c2-2560b33bbf61.png)
![2023-02-13_15 08 35](https://user-images.githubusercontent.com/113377506/218480593-680a275c-6a46-477a-959d-858d721c3672.p
![2023-02-13_15 08 08](https://user-images.githubusercontent.com/113377506/218480608-5799fd5e-d3d4-4158-ba8f-879565103b3c.png)
ng)

**Comment by jaydubdev** [comment]
looks good! If you can make sure that there is no water nearby and it's just the woods around the house,

**Comment by Fqzoon** [comment]
Sure

**Comment by PiweeX** [comment]
[Haunted House Instructions.docx](https://github.com/PiweeX/HogRealms/files/10727202/Haunted.House.Instructions.docx)

Projekat gotov i uspešno završen
