### ISSUE TITLE
next couple hours - title - Finding The Lost City in Minecraft! -

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#287]
https://docs.google.com/document/d/1GMW02kg9ezjfEi255DUGEM8NnXy2ndgmtHm01nfk9zU/edit?usp=sharing

**Comment by TheFrontView** [comment]
The Lost City will be played with game modifications. ( Use optifine )

- Brightness: Moody
- Dynamic Lights: Fancy

**Comment by TheFrontView** [comment]
![2023-03-12_20 51 18](https://user-images.githubusercontent.com/71612070/224569834-e14f4347-4325-4c8f-ac3e-27c38e6fe5bc.png)
![2023-03-12_20 51 29](https://user-images.githubusercontent.com/71612070/224569836-e0902b11-ed34-4d3c-a5b6-e8a97ee152c6.png)
![2023-03-12_20 51 36](https://user-images.githubusercontent.com/71612070/224569839-9299e72f-3213-4239-a8df-ee7abd35946c.png)
![2023-03-12_20 51 54](https://user-images.githubusercontent.com/71612070/224569840-d39f6070-489c-46f9-9abc-f2918ef6a238.png)
![2023-03-12_20 51 58](https://user-images.githubusercontent.com/71612070/224569841-2b684668-9c5f-4a85-96ef-fcd9648cd4ae.png)
![2023-03-12_20 52 04](https://user-images.githubusercontent.com/71612070/224569842-834c8ac4-365c-4e05-af10-b82f53ec8afc.png)
![2023-03-12_20 52 11](https://user-images.githubusercontent.com/71612070/224569844-276b34c8-7234-4028-a343-cf7c0400394d.png)
![2023-03-12_20 52 15](https://user-images.githubusercontent.com/71612070/224569845-5d477f0e-7151-4340-a278-d5f4363534e1.png)
![2023-03-12_20 52 21](https://user-images.githubusercontent.com/71612070/224569848-58867bbf-a665-49a4-8aac-50771fbebe65.png)
![2023-03-12_20 53 06](https://user-images.githubusercontent.com/71612070/224569849-3a07e1c1-b93c-41b4-9b49-fbd43ec89cf9.png)
![2023-03-12_20 53 10](https://user-images.githubusercontent.com/71612070/224569851-4c7a9bbf-657a-4d49-9543-6c0798ca7ef6.png)
![2023-03-12_20 53 23](https://user-images.githubusercontent.com/71612070/224569852-39396da8-8782-4a36-986d-78c6b4b71460.png)

Sorry, I forgot to post the process.

**Comment by PiweeX** [comment]
odlicno
