### ISSUE TITLE
Cena Dark Prismarina

### ISSUE THREAD

**Issue by TheFrontView** [PiweeX/PiweeX#288]
Trenutna cena Dark Prismarina iznosi 1000$ po 2 bloka.

U Japanskom stilu treba 200 Blokova Prizmarina za MALU kuću. Odnosno mi sa tim novcem možemo uzeti 1 Triden koj košta 200000$, zbog toga sam mislio da se cena stavi na neku pristupačnu cenu.

Odlično bi bilo 200$ po 32 Komada Dark Prismarin Blokova, jer opet trebalo bi da se ulaže, ali 10 puta manje nego sada.

Sve ovo dovodi do zaključka da ako cena Prismarina ostane ovolika Japanski budžet smanjiće se za 92%, i onda kada ratujemo protiv npr. Grka mi nikako nećemo imati novac za defence, a nije ni plan da spucamo ceo budžet ni u arhitekturu.

Hvala na čitanju, srdačan pozdrav!

**Comment by PiweeX** [comment]
ako se izglasa usvojićemo i biće promenjena cena!

**Comment by PiweeX** [comment]
smanjena cena prismarine sharda sa 980$ za 18 na 511 za 32

nije se izglasalo ovde ali je puno igraca trazilo i najrealnije je da bude ta neka cena
