### ISSUE TITLE
First Model for Water #7074 (Front)

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#289]
Message:

also couple more things - I get payed today or tomorrow so I will be able to pay upfront for the build and what I'm asking you now!

I think I found out how you guys can make the mobs, all you have to do is pick a mob in blockbentch, it doesn't matter which one we won't be using the ability's of the mod. Then just make the mob like you guys normally do, then you just make a resource pack. Then I use optifine run the pack and that's it!

Here's a video showing you how to make the resource pack

https://youtu.be/fdo_E61vVlw?t=557

**Comment by PiweeX** [comment]
PROGRES


![image](https://user-images.githubusercontent.com/33425430/223544832-0a195eed-2e85-4453-962c-3194e4475ae2.png)

**Comment by PiweeX** [comment]
![image](https://user-images.githubusercontent.com/33425430/223545551-f2f7b576-4020-47ca-8ec1-b621c8059eae.png)

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/223546943-da16ccdb-11bd-4c48-8186-0d7eeaf972eb.png)

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/223546985-a00e6dad-ec01-474b-9c43-341c99ee5859.png)

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/223549006-0e8d761c-5da6-4047-8126-2a02395ce7d0.png)

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/223549616-f49eeb34-f7cd-4474-be7c-68c2329ab8ba.png)

**Comment by PiweeX** [comment]
nice

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/223549806-1560eadb-5f6b-4255-8f47-5c2b7371331b.png)

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/223550212-787f256c-d8a5-4f68-8b98-5f656c1faf3f.png)

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/224426417-9e9a8ba0-31a4-4af1-a0bc-436ba1665926.png)

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/224428078-d2176e69-7d03-44ff-aab3-b3c8f7557a3f.png)

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/224428519-4be17d65-9bd3-4776-8eee-0f9f9897ed93.png)

**Comment by TheFrontView** [comment]
Build **next couple hours hours - title - Finding The Lost City in Minecraft! - #287** will be finished on Sunday.

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/224430649-3b13edc2-1d09-4ffe-bd08-9980a99d749b.png)

The model is finished. This is the last version of this guy, only a resource pack left to do.

**Comment by PiweeX** [comment]
Model je urađen ali ponovo jer nije podržavao ovaj format, morao je da bude 2x2 dakle u nivou zombija kako bi funkcionisao, u buduće ćemo se pozabaviti rešavanju ovog problema
