### ISSUE TITLE
Second Model for Water #7074 (Front)

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#290]
Drugi model patuljka za YT Kids sadržaj, u slici ispod je primer

**Comment by PiweeX** [comment]
Primer drugog patuljka


![imgbin-snow-white-seven-dwarfs-sneezy-grumpy-dwarf-7rpyuCgEv9P8gbCvHGpF1SBG8](https://user-images.githubusercontent.com/33425430/223565084-163fa699-ec02-4bb3-9cfb-2f4b6bcc14ec.png)

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/225425933-0faa9a9d-2a7c-472b-accf-f434660c7cc6.png)

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/225426412-07122388-d601-4db6-8ea0-0c9f49557ecd.png)

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/225427141-e2b3b802-0b0c-4ade-b545-f3dba0f4c007.png)

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/225427161-5ba9c720-ed95-4ed9-9d30-2c557f99bd99.png)

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/225430329-a7fd4fc9-8dbc-4370-b861-6e8427f01e64.png)

**Comment by TheFrontView** [comment]
![image](https://user-images.githubusercontent.com/71612070/225432244-32a46621-c0ae-45f3-80e1-aebd5d51175f.png)

**Comment by PiweeX** [comment]
Model je urađen ali ponovo jer nije podržavao ovaj format, morao je da bude 2x2 dakle u nivou zombija kako bi funkcionisao, u buduće ćemo se pozabaviti rešavanju ovog problema

isto važi i za prvi model koji je predhodni issue
