### ISSUE TITLE
Map Changelog

### ISSUE THREAD

**Issue by TheFrontView** [PiweeX/PiweeX#291]
Trenutan izgled mape.

![image](https://user-images.githubusercontent.com/71612070/224023860-f13388ab-1ef6-4c06-9909-9b566297d63f.png)

Zamolio bih države koje idalje igraju na serveru da se prijave, kako bih sklonili neaktivne i dopustili nove prostore za gradnju država.

**Comment by TheFrontView** [comment]
Svaki problem isključivo prijavite u tiketu na Roleplay lizi.

**Comment by PiweeX** [comment]
molim da se ovo prebaci u issue za roleplay ligu jer već imamo isti issue ispod
