### ISSUE TITLE
Obrisati thunderove klejmove za debris |

### ISSUE THREAD

**Issue by muvstp37** [PiweeX/PiweeX#293]

**Comment by muvstp37** [comment]
ovo treba uraditi jer postoji preko 100 debrisa u njegovom klejmu (ugl mnogo ima) i mnogo je teze pronaci debris sto nekako smanjuje rp u nekim drzavama kao sto je aljaska ili tako nes(nez u kojim drzavama se mnogo kopa)jeste da je u africi al nea veze svj mora se obrisat ili ce muv bit ljut

**Comment by PiweeX** [comment]
molim Coneta da obriše te claimove

**Comment by AcaaVucko** [comment]
Hm ako mislite na te za debris samo napišite kako se zovu, a neke sam juče prebacio Yamiju jer je tako rekao, mislim da je Moskva,Luhanks, Donetski i Petersburg

**Comment by PiweeX** [comment]
ovo ću zatvoriti jer više ne postoje takvi claimovi.
