### ISSUE TITLE
Sezone

### ISSUE THREAD

**Issue by TheFrontView** [PiweeX/PiweeX#303]
Da se dodaju sezone na sever učinile bi igru zabavanijim.

Leto, zima, jesen, proleće. Npr. u nekim saharama ako nema vode, a vrućina je umireš kao u betu što je bilo.

**Comment by PiweeX** [comment]
Bio je predlog za nešto slično ranije čak je i još otvoren issue još uvek, ako tako nešto bude moguće ubacićemo

trenutno planiramo da vratimo vreme, ako se neko seća igre u beta verziji postojalo je ono da kad je npr hladno moraš se obući ili se smrzavaš i umireš, i tako neke stvari recimo kad je vruće ne možeš ići čamcem ali na to su se ljudi najviše žalili i onda nit da se doda nit da se ukloni

**Comment by TheFrontView** [comment]
Kada bi se to vratilo učinilo bi igru realističnijom.

**Comment by PiweeX** [comment]
Ovaj issue stoji jako dugo, nije bio zatvaran upravo jer smo čekali dobar momenat

najavljujem vraćanje ovoga ali u drugom obliku nego kakvo je bilo pre 2 godine u beti

u ovaj issue ću napisati kad bude dodato i gotovo

**Comment by PiweeX** [comment]
Zatvaram zbog huda koji će biti dodat uskoro kao i onaj prvi
