### ISSUE TITLE
Custom stvari

### ISSUE THREAD

**Issue by bulke504** [PiweeX/PiweeX#312]
Posto znam da tekstura ne radi bilo bi dobro da posle popravke da se dodaju custom boutovi i ostale stvari . Veci boutovi bi se vise uklopili u medival sil servera i inzvazije na moru bi bile mnogo vise efikasne i epic

**Comment by PiweeX** [comment]
otvoreno glasanje!

**Comment by PiweeX** [comment]
![vU-BM1IWS-uwJXEO9xQ9tg](https://github.com/PiweeX/HogRealms/assets/33425430/b9cb9abd-70aa-4595-9fe7-14ec7488e085)


zahtev prihvaćen, ovo su nova vozila koja stižu na Hog uskoro, otvoren je issue za njih

ovaj issue je završen, stoga zatvoriću ga


hvala na predlogu, inače stara vozila su uklonjena i dodaju se ova koja su više prilagođena stilu i vremenu servera.
