### ISSUE TITLE
Fixovi pre mainneta

### ISSUE THREAD

**Issue by Viktor023023** [PiweeX/PiweeX#315]
Posto je Px zatrazio da se napravi issue za stvari koje se trebaju fixati, ja cu ovde napisati neke, ostali igraci mogu takodje.
-teksture i za oraxen i za runic
-da se taxe ogranice na mesec dana
-ukoliko je moguce da proradi mapa
-uhc da se vrati ako je moguce
-izgled chata gde je pre moglo da se vidi ko je iz koje drzave

**Comment by JaSamIgor** [comment]
ne zaboraviti porez koji ne radi godinu dana (izgubio sam preko 2 miliona)

**Comment by PiweeX** [comment]
Hvala!

**Comment by PiweeX** [comment]
> ne zaboraviti porez koji ne radi godinu dana (izgubio sam preko 2 miliona)

Rešeno za porez kroz drugi issue, isključili smo dok ne sredimo da se obračunava na duži period ✅

**Comment by PiweeX** [comment]
-teksture i za oraxen i za runic

Rešeno upravo posle jutarnjeg restarta ✅

-da se taxe ogranice na mesec dana
Takse su ukinute za sad a kad ih vratimo obračunavaće se mesečno ✅

-ukoliko je moguce da proradi mapa
Rešeno napokon nedavno, mapa se oporavlja ✅


Šta još nismo uradili sa liste:

-uhc da se vrati ako je moguce

-izgled chata gde je pre moglo da se vidi ko je iz koje drzave

**Comment by PiweeX** [comment]
Šta još nismo uradili sa liste:


-izgled chata gde je pre moglo da se vidi ko je iz koje drzave

Radimo na tome, nedavno je izbačen predhodni plugin koji je kolko tolko držao čet da bilo kakav bude a sad je default dok ne uradimo čet sa placeholderima i ostalim kao što je predhodni bio na staroj verziji 

-uhc da se vrati ako je moguce

Vratili bi isti dan ali nažalost na lobby se nije moglo ući ako ste sa starije verzije od 1.16.2 zbog nove generacije bedrocka.. Drowned je nedavno uradio update Lobby-a pa je možda sad to popravljeno ali treba da se ispita još uvek na koji način možemo to da rešimo, ako ništa uradićemo rekonstrukciju lobby-a dakle izgradiće se isti opet jer nam je ovaj odličan
