### ISSUE TITLE
Register Problem

### ISSUE THREAD

**Issue by Aleksa5826** [PiweeX/PiweeX#327]
Igrao sam na hogu pre godinu dana i bio sam registrovan pod imenom alexadjordjic... Sad nakon 1 godine dosao sam sa drugom da igramo ponovo i usao na isti nalog trazilo mi je da se registrujem, predpostavio sam da je obrisan nalog i krenuo da se registrujem ali je vec pisalo da sam registrovan pod drugim imenom i pisalo je ime "SoulVexx" nikad u zivotu nisam koristio to ime... Rekli su mi da ugasim ruter malo sacekam i da probam da udjem opet, uradio sam sve to i sad se promenilo ime naloga na koji sam "registrovan" (zaboravio sam ime)... Sve u svemu opet sam restartovao i odradio sve od navedenog ali se ovaj put ni ime nije promenilo... Da sumiramo sve, ne mogu da se registrujem i da igram vec 6h..

**Comment by PiweeX** [comment]
> 

 to je bag za da ti prikaze da imas acc koji nemas, desava se cesto ali ne pravi problem ako resetujes ruter, nisam siguran kako mozes resiti taj problem najbolje bi bilo kad bi probao sa vpn-om nekim a kad bi ti radilo jer ocigledno ti je IP na ruteru staticki pa onda se ne menja kad resetue

**Comment by Aleksa5826** [comment]
Probao sam sa vpn-om izadje mi ekranu VPN/PROXY je strogo zabranjen na Hogu!

**Comment by PiweeX** [comment]
> Probao sam sa vpn-om izadje mi ekranu VPN/PROXY je strogo zabranjen na Hogu!

Kako ti ide nick?

**Comment by PiweeX** [comment]
otvori tiket
