### ISSUE TITLE
ukradeni itemi a nece vrati

### ISSUE THREAD

**Issue by mikitriske** [PiweeX/PiweeX#354]
ovako..... ovo je otislo predaleko a dzelat me ignorise tkd mora ovde. Radi se o tome da me je uchiha yami izbacio iz drzave i ukrao 2 netherite seta koja nece da vrati i vadi sa na ustav, mi smo imali dogovor da nema nista od tog ustava i imam svedoka za to, yami ne zeli da vrati armore i cak mu je cone (dzelat) rekao da vrati. Ja zelim te iteme nazad jer nije fer

**Comment by vukstrale** [comment]
Skill isusse, rare Yami W

**Comment by NemanjaRusija** [comment]
> ovako..... ovo je otislo predaleko a dzelat me ignorise tkd mora ovde. Radi se o tome da me je uchiha yami izbacio iz drzave i ukrao 2 netherite seta koja nece da vrati i vadi sa na ustav, mi smo imali dogovor da nema nista od tog ustava i imam svedoka za to, yami ne zeli da vrati armore i cak mu je cone (dzelat) rekao da vrati. Ja zelim te iteme nazad jer nije fer

poz brate ovdje se stavljaju tehničke stvari i bitne, a na gluposti poput ovog

**Comment by NemanjaRusija** [comment]
ODMAH ZATVARAJ

**Comment by PiweeX** [comment]
za ovakve probleme možete pisati u tiket, ovde su samo tehnički problemi i predlozi
