### ISSUE TITLE
Traktor sadi cutom biljke

### ISSUE THREAD

**Issue by bulke504** [PiweeX/PiweeX#356]
Posto postoje neke farme marihuane na serveru koje su ogromne treba dodati traktoru funkciju da sadi i razbija marihuanu. Pre toga se sama marihuana mora popraviti posto je skroz zeznuta i ne radi dobro posto cim pridjes polju marihuane igra je neigriva koliko baga server. Hvala

**Comment by PiweeX** [comment]
Marihuana je skroz isključena i tako će i ostati, onemogućićemo je totalno jer stvara ogroman lag uključujući i grožđe
