### ISSUE TITLE
Dodavanje rankova na Hogu(NPC tags, Rankovi)

### ISSUE THREAD

**Issue by NemanjaRusija** [PiweeX/PiweeX#357]
Pozdrav, svima nama  je poznato da je ukinut shop za rankove. Djovani koji pokrenuo incijativu za dodavanje rankova je bilo zaboravljena. Ti rankovi su sa oraxenovog plugina koji bi se slagao. Primjer: Member, OG(stari memberi), Support, Dželat, Owner(nisam siguran da li se imena mogu mjenjat). Uz rankove igrača dolazimo to NPC tags, bilo bi korisno za blackshop. Kada bi mainet bio bi rank Voter, kao najaktivniji voter mjeseca na situ, gdje se votaju MC server. MOŽDA da se uvede Item rarity, to bi više bilo kao test faza, kad dođu novi CUSTOM ITEMI. Ovo su slike par primjera kako bi to izlgedalo.
![94e2d8d1f6f25fdf6ade019da41ce021e95b28cb](https://user-images.githubusercontent.com/107151423/232525329-44f37921-6728-4075-bcec-9589393ac795.png)
![3d58a480bab77086c026c66fcef5240ce52948bd](https://user-images.githubusercontent.com/107151423/232525351-9a356451-886b-48ee-ac32-aae2f51e1563.png)
![78d174e9df511cbe057f739909b849e564620a4f](https://user-images.githubusercontent.com/107151423/232525357-36ff25d2-36e0-4c35-bba3-fe97157b65d1.png)
![8397550e07af0895ad22c70c27ea7c3fde09eb3b](https://user-images.githubusercontent.com/107151423/232525372-53f1eb92-9851-4e1f-ae7f-5432febed000.png)

**Comment by PiweeX** [comment]
sviđa mi se ideja, samo problem je što smo želeli da svi imaju default rank u smislu da svi budu jednaki zbog čega smo i ukinuli shop ali i jer želimo da fokus bude ne na tome koji ti server rank da po zasluzi ili nečemu već ustvari da ti uređuješ svoju igru i kreiraš je, da ako smisliš roleplay mongola budeš to a ne da juriš za time šta će ti server dodeliti i na šta ćeš se opredeliti, nego baš sistem da igrači kreiraju sav scenario svoje igre

tako da bi oko ovoga mogao da se smisli neki koncept a da ne ometa ovo što sam gore izneo


danas mi je Djovani sa SkyBlocka poslao primer kakav će oni imati na SkyBlocku, ovo je samo primer

 
![image](https://user-images.githubusercontent.com/33425430/232631863-425011ef-0e4e-44ba-ba4b-00699df14adc.png)


![image](https://user-images.githubusercontent.com/33425430/232632185-fc30ac4f-95ad-42ef-b81d-f0f3ba1fc92a.png)

**Comment by onepotato69** [comment]
Slažem se sa Piweeex-om, mislim da bi trebalo da se dodaju rankovi i tako te stvari ali da glavni fokus bude na kreiranje sobstvene priče npr: ako sam ja u Engleskoj Earl onda da me ljudi znaju po tome a ne po tome što imam neki rank.

**Comment by PiweeX** [comment]
Predlog je usvojen za SkyBlock

razvojni tim SB podservera radi sa tim pluginom što je Nemanja poslao, zatvoriću issue jer smo to rešili
