### ISSUE TITLE
Da se ukine efekat krvarenja.

### ISSUE THREAD

**Issue by Stamenko85** [PiweeX/PiweeX#358]
Razlozi:
1.previse je op
2 borba sa tim efektom je previše brza
3.cim dobijes efekat moras odma da se hilaš
4.iako si ti full neth protivnik moze iz par udaraca kamenim mačem da te ubije zbog krvarenja.

**Comment by G4uts** [comment]
Takodje slazem se s ovim jer je krvarenje pre op i time ne pokazujes svoj skill. Smatram da bi ovim izbacivanjem svi clanovi vise trudili da nauce pvp i da bi drzave vise pokrecale evente u smislu treninga i drugih stvari. A takodje smatram da ovim igraci bi vise gledali da skupljaju play time i dobiju jace stvari kako bi jacali.

**Comment by yamizvaniuchicha** [comment]
Slažem se, eventualno da ostane ali ono baš jako da se nerfa i da samo neki itemi mogu dati bleeding, npr katana, vlaska (magija samo) dagger i tjt

**Comment by onepotato69** [comment]
Slažem se, još pogotovo ako neprijatelj ima katanu.Čak i ako si full Maxan Netherite Armor kada kreneš da krvariš i dok te neko tuče katanom odma umireš prebzo. To se jedino može izbeći ako imaš nekoga sa sobom da ti pomogne ili da ime Entchaned Golden Apple.

**Comment by XDrock** [comment]
Slazem se. Previse je op

**Comment by vukstrale** [comment]
Slažem se, previše je op + drastično smanjuje FPS igračima sa slabijim mašinama

**Comment by bulke504** [comment]
Ja mislim da je krvarenje op efekat ali da ga ne treba sklanjati ida ga ne treba nerfovati posto je relistican efekat koji ide dobro uz roleplay igru i sam kontekst hoga.

**Comment by Mega-Gamer007** [comment]
Slazem se i mislim da se sa krvarenjem u igri ne pokazuje kolko si dobar u igri i da bi trebalo da se ukine , smanji ili stavi na custom iteme

**Comment by PiweeX** [comment]
izglasano, prebacen je u noviji issue od Vuka
