### ISSUE TITLE
Ako se budu dodavali rankovi na hog da ne budu dodati kitovi

### ISSUE THREAD

**Issue by onepotato69** [PiweeX/PiweeX#360]
Ako rankovi budu stigli na hog nemojte dodavati kitove jer će bitj abjusano za beskonačno netherine setova. Na primer ja sada imam King rank koji daje odlične stvari,  ja mogu uraditi /kit King i dobiću vrh stvari; e sada problem je kada prodje cooldown od 2-3 sata taj neko sa Kit king će to opet uraditi i ima 2 netherite seta  sve sa oružujem i golden applovima. Jednostavno bilo bi pre op i ne realno.

**Comment by PiweeX** [comment]
Bez brige, brinemo o tome

**Comment by PiweeX** [comment]
Zatvoriću issue
