### ISSUE TITLE
Isključiti održavanje landa

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#362]

**Comment by bulke504** [comment]
Treba iskljuciti ali ako se ljudi ne sloze to je tako . Posto vladar neke drzave moze biti aktivan ali da igraci ne budu i tako automatski on nece imati izvor para i drzva ce propasti i bankroptirati.

**Comment by PiweeX** [comment]
> Treba iskljuciti ali ako se ljudi ne sloze to je tako . Posto vladar neke drzave moze biti aktivan ali da igraci ne budu i tako automatski on nece imati izvor para i drzva ce propasti i bankroptirati.

Vratićemo kad uspemo da namestimo da se obračunava na 50 dana a ne na 2 dana, to je sad samo teralo igrače i opterećivalo ih
