### ISSUE TITLE
Predlozi za poboljšanje  Ekonomiju na serveru

### ISSUE THREAD

**Issue by Stamenko85** [PiweeX/PiweeX#370]
1.svakog dana posle restarta u 7 da se menja cena   žita izmedju 15 i 40,a subotom da bude event od jedan sat gde će žito biti 70 80 $
2.da se pored žita doda zlato i neka vrstu drveta
3.pod hitno da se vrati black shop 
4.da se smanji cena upecanih  riba

**Comment by vukstrale** [comment]
Slažem se sa Stamenkom

**Comment by onepotato69** [comment]
Ne slažem se, Ovo nije atlas ili angor. Hog ima roleplay i ovi evetnovi nebi dobro uticali na njega.

**Comment by PiweeX** [comment]
mozda usvojimo nešto kad krenemo da menjamo ekonomiju za koji dan


što se tiče zlato ono nikad nece biti dodato objasnio sam u nekom issueu pre koji dan, a što se tiče black shopa on će biti u formi da je svud po laputi a onako više nikad, a to za ribe mozda, moramo razmotriti koja je sad cena
