### ISSUE TITLE
Predlog za ekonomiju

### ISSUE THREAD

**Issue by Mladen0005** [PiweeX/PiweeX#371]
Cena wheata treba da se malo poveca otprilike na 30 na 16 komada,kada se ponovo otvori black market
Cene po steku:
Gold-700 
Iron 1000
Diamond-1100
Lapis 400
Redstone-450
Ove cene bi bile jednake vremenski tako bi igraci radili posao koji zele za gotovo slicnu sumu novca,pored toga ovim cenama nece biti lako zaraditi veliku sumu novca u kratkom vremenskom periodu sto znaci da ce i ekonomija da bude uravnotezena na neki vremenski period sto ce dovesti da cene na laputi ne skoce mnogo cak se i zadrze na neki period.ovo je moje mišljenje o cenama.

**Comment by Mladen0005** [comment]
Naravno nisam dodao resurse kao sto je hrana i drva posto one su neizbežne u razvijanju te im cena ne traba biti veca od 100 dolara po steku,naravno u uporedjivanju retkosti i vrednosti tih resursa

**Comment by Viktor023023** [comment]
Realne cene, mozda kada bi se iron malo smanjio jer ga ima svuda, ostalo podrzavam👍, najbolje bi bilo da se vrati blackshop ili da se prebaci na laputu sve

**Comment by vukstrale** [comment]
Previše, dovešće do inflacije. I gold je jeftiniji od irona? Smanji cenu irona i sve cene podeli sa dva, onda možemo da pričamo

**Comment by Viktor023023** [comment]
Mozda bi i bila inflacija, zavisi kolko su ljudi uštekali, postoje sanse da bude broken kao kad je bakar dosao u blackshop

**Comment by Mladen0005** [comment]
Gold nema toliku primenu koju ima iron prakticki sve manje drzave zavise od irona,gold se ne koristi ni za armore te ga ima malo vise nego irona tako da cena irona je velika bas iz razloga jer je najpotrebniji a cena zlata je niza zbog slabog koriscenja i nema veliku primenu na serveru,takodje cene su stavljenje realno da su nize trebalo ni vise od 10 dana da se skupi neki dostojan novac za razvijanje drzave

**Comment by miki-00** [comment]
Ja se slazem sa Mladenom, takodje mislim da je on najvise upucen jer su na serveru najaktivniji njegova drzava Yakuza i SHS.
Upucen je sa situacijom Hoga i zna kako da je resi Stamenkov predlog se svidja novajlijama koje su dosle sa angora ili atlasa gde to ima pa im je to "cool"
Ovaj server ima neki rp ne prave se eventi vikendom za vecu cenu💀
Ja podrzavam Mladenovu ideju i predlazem da se uvazi, steta je da su skupljanje psenice i prodavanie vrednih stvari na la jedino kako da se skupe pare.
#MladenZaDzelata

**Comment by onepotato69** [comment]
Realne cene.👍

Pročitao sam par komentara i vidim da neki ne razumeju da se iron više koristi od golda samim tim mora biti i skuplji. Više od 60% stvari na serveru su od irona, ne vidim zašto bi gold bio skuplji.

#MladenZaDzelata

**Comment by DaniloU0** [comment]
Potpuno se slažem sa Mladenom i njegovim pogledom na server, nema dosije, ima iskustva sa staff komandama, zna matematiku i realno gleda na sve. Ne poredi ljude iz drugih država kao dobre i loše te bi za svakog imao razumevanje. Dobar je sa svima i nadam se da će on postati dželat jer znam da bi bio uspešan u ovom poslu.
#372

**Comment by vukstrale** [comment]
> Gold nema toliku primenu koju ima iron prakticki sve manje drzave zavise od irona,gold se ne koristi ni za armore te ga ima malo vise nego irona tako da cena irona je velika bas iz razloga jer je najpotrebniji a cena zlata je niza zbog slabog koriscenja i nema veliku primenu na serveru,takodje cene su stavljenje realno da su nize trebalo ni vise od 10 dana da se skupi neki dostojan novac za razvijanje drzave

Gold treba da vredi više od irona zbog istog razloga kao u RL. Redji je od irona, redji = skuplji. Nije isto trampiti se i prodavati laputi. Ako budeš stavio cenu irona na 1100 po steku, ja imam tri dupla česta blokova irona, i još šest duplih čestova od R1derPNa. Jedan dupli čest ima 54 slota. To je 4 374 steka običnog irona, po ceni od 1100 po steku: 4 811 400$. Dovoljno da jednoručno postanem najbogatiji igrač na serveru. Zlata sa druge strane imam daleko manje.

**Comment by Mladen0005** [comment]
Po mojim pregledima zlata ima vise jer ljudi cuvaju za bm ali naravno ovo nisu konacne cene i treba jos raditi ali je prosek prosecne zarade da ne bude ni previse ni premalo, naravno inflacija ce malo porasti kad se otvori bm ali to je očekivano jer su ljudi cuvali po toj logici onda ne treba prodavati nista sem ribe i psenice da bi ekomija ostala ista ako budem izabran gledacu da inflacija bude sto manja a cene ato bolje i za nove i za stare igrace kako ne bi se server vratio sa cenama koje su bile u decembru.

**Comment by onepotato69** [comment]
> > Gold nema toliku primenu koju ima iron prakticki sve manje drzave zavise od irona,gold se ne koristi ni za armore te ga ima malo vise nego irona tako da cena irona je velika bas iz razloga jer je najpotrebniji a cena zlata je niza zbog slabog koriscenja i nema veliku primenu na serveru,takodje cene su stavljenje realno da su nize trebalo ni vise od 10 dana da se skupi neki dostojan novac za razvijanje drzave
> 
>> Gold treba da vredi više od irona zbog istog razloga kao u RL. Redji je od irona, redji = skuplji. Nije isto trampiti se i prodavati laputi. Ako budeš stavio cenu irona na 1100 po steku, ja imam tri dupla česta blokova irona, i još šest duplih čestova od R1derPNa. Jedan dupli čest ima 54 slota. To je 4 374 steka običnog irona, po ceni od 1100 po steku: 4 811 400$. Dovoljno da jednoručno postanem najbogatiji igrač na serveru. Zlata sa druge strane imam daleko manje.

>
Zlato nema toliku primenu kao iron da li ćeš u ratu koristiti zlatan armor ili iron armor?

Zlato i ako je redje ne služi  na hogu.
Iron sa druge strane ima mnogo veću ulogu nego zlato na hogu i sasvim je uredu da gold ne bude skuplji od irona.

**Comment by PiweeX** [comment]
kad smo imali prodavanje svih ruda na serveru jedno kratko vreme bilo je kao što sam i mislio, igra se svodila samo na kopanje i prodavanje ruda, to je jako loša ekonomija a i plus to što je drugačija generacija sveta pa na 1 mestu se moze naci ceo chunk pun zlata itd što je jako loše za ekonomiju

**Comment by Mladen0005** [comment]
> 

U tom slucaju moja razmisljanje za sad bi bilo da pecanje ostane isto,pesnica da se malo poveca na neko krace vreme,kada bi bio zaposljen vodio bi racuna o razvijanju ekonomije i odrzavanje inflacije i naravno da svi igraci budu zadovoljni, naravno da ne bude previse lako skupiti novac,trenutno sa psenicom ne moze da se skupi dovoljno za razvoj drzave,nedeljno bi ostavio svoje misljenje i statistiku i proxenu inflacije

**Comment by vukstrale** [comment]
> kad smo imali prodavanje svih ruda na serveru jedno kratko vreme bilo je kao što sam i mislio, igra se svodila samo na kopanje i prodavanje ruda, to je jako loša ekonomija a i plus to što je drugačija generacija sveta pa na 1 mestu se moze naci ceo chunk pun zlata itd što je jako loše za ekonomiju

Slažem se, i verujem da ima način da ispravimo taj sistem a da i dalje postoji prodaja ruda:

**Prodaja Emeralda.**

Emerald je koliko toliko jednako rasporedjen po svetu i trenutno nema nikakvu svrhu na Decentralendu. Njegovo prodavanje za 2000$ po steku doprinelo bi ekonomiji servera bez preteranog okretanja beskonačnom kopanju.

**Comment by NemanjaRusija** [comment]
Ekonomija na hogu je jako sjebana, a sjebana je zbog abjuza. Npr. netherite je prije bio oko 45000 po komadu i više, a sad je 5000. Kod irona treba da budu iste cijene, možda ne iste al približno a emerald je rijedak npr. i on može da bude skup. Kao što sam rekao netherite se sjebao skroz i treba se radit ne rješavanju tog problema. Što se tiče wheat-a i na tom treba radit da se stabilizuje cijena. Kod riba da cijene ostanu iste jer teško je dobiti legy ribu tek tako. Serveru treba ne prebogati ljudi niti siromašni ljudi, jer je ovo rp server i treba da bude HARD. Tabela bi npr. išla ovako;


**RUDE:**

IRON: 180 dolara po 32 komada 
GOLD: 290 dolara po 32 komada
EMERALD: 450 dolara po 32 komada
DIAMOND: 330 dolara po 32 komada
NETHERITE: 4200 dolara po komadu
REDSTONE: 190 dolara po 32
LAPIS: 100 dolara po 32

**POLJOPRIVREDA**

WHEAT: 50 dolara po 64 komada
CARROTS: 20 dolara po 64 komada
POTATO: 20 dolara po 64 komada

OVO JE ZNATNO SMANJENO DA BI BILO BOLJE ZA RP I DA SE SERVER NE SVODI SAMO NA NAJJBOGATIJE IGRAČE, JER AKO BUDE POVEĆANO DOĆIĆE DO VELIKE INFLUACIJE!!!!!

**OBJAŠNJENJE:**

Svi mi znamo da postoji neki chunk pun golda i da se tako bogati neko od nas.
Sve ove cijene su znatno spuštane zbog RP-a jer traba biti hard a ne easy mode.

Toliko od mene!!!!

**Comment by Mladen0005** [comment]
Slazem se sa vecinom, ali novi igraci ne zele da se cimaju toliko ja sam u svom predlogu izneo i sa te strane naravno serveru je potrebno pracenje ekonomije i potrosnje koja bi najmanje treba da bude 2 nedelje kako bi se ocenile dobre cene bez inflacije,da napomene da sam pricao sa pajashinom koji ide u ekonomsku i imamo slicno misljenje da ako ni gledali da privucemo nove igrace inflacije mora da poraste 5 do 10% pa tek onda postepeno da se smanjuje,a po hard da se inflacija odma smanji na vise od 10% ali naravno da ne preteramo

**Comment by NemanjaRusija** [comment]
> 

Al igrači novi imaju mugućnost da uđu negdje u državu da bi skupili dovoljno vještina i novca, a ne odmah države praviti to je po meni shit.

**Comment by Mladen0005** [comment]
Pa vecina i ne pravi drzavu vec bildaju sebe kupuju oruzje i to,zbog povecanja inflacije lako je zaraditi novac tim trikom se sluze i ostali serveri da ih ne spominjem

**Comment by NemanjaRusija** [comment]
> Pa vecina i ne pravi drzavu vec bildaju sebe kupuju oruzje i to,zbog povecanja inflacije lako je zaraditi novac tim trikom se sluze i ostali serveri da ih ne spominjem

Jer su cijene povećane, ovako su trostruko smanjene, jer asirci imaju milione a to je nepotrebno serveru

**Comment by Mladen0005** [comment]
Zato i kazem izneo sam svoje misljenje ako idemo na hard infalcija treba da se samanji jos do sada npr tvoj primer je dobar ali psenica u ovom slucaju se debelo ne isplati tkd ne verujem da ce je ljudi raditi npr trenutno vrednost je 88 dolara po steku cinimi se,kad bi smanjivali inflaciju morali bi da stavimo na 20 po 16 kom sto se bas i je isplati za razliku koju dajes i vremensko ulaganje u poljoprivredu

**Comment by NemanjaRusija** [comment]
> Zato i kazem izneo sam svoje misljenje ako idemo na hard infalcija treba da se samanji jos do sada npr tvoj primer je dobar ali psenica u ovom slucaju se debelo ne isplati tkd ne verujem da ce je ljudi raditi npr trenutno vrednost je 88 dolara po steku cinimi se,kad bi smanjivali inflaciju morali bi da stavimo na 20 po 16 kom sto se bas i je isplati za razliku koju dajes i vremensko ulaganje u poljoprivredu

trenutno je pšenica na 22 dolara po 16 komada, sad provjerio

**Comment by Mladen0005** [comment]
Pogodio sam, trenutno sta bi ja uradio je ostavio 22 dolara jos neko vreme da vidim kako bi se vrtela ekonomija u serveru a potom smanjio ili poveco cenu

**Comment by NemanjaRusija** [comment]
> Pogodio sam, trenutno sta bi ja uradio je ostavio 22 dolara jos neko vreme da vidim kako bi se vrtela ekonomija u serveru a potom smanjio ili poveco cenu

Za wheat neka ostane, a po mom neka bude sve, jer serveru treba hard jer ima RP i time bi osvajanje lapute bi bio teži i teži

**Comment by Mladen0005** [comment]
Naravno,nisam imao oslonac sta planirate pa sam gledao po svom kako dovesti nove igrace a da inflacija ne predje 20% pa je potom smanjivati

**Comment by NemanjaRusija** [comment]
što se tiče mene ja sam rekao svoje pa neka px odluči

**Comment by Mladen0005** [comment]
Meni se svidja trenutna ideja i ako zelite fa napravite tvrd i tezak rp za sve drzave,cene su dosta niske te inflacija se nece povecati ni 5% na samom pocetlu

**Comment by NemanjaRusija** [comment]
Piwi šta je sa ovim?

**Comment by PiweeX** [comment]
Mladen je postao kartografer na Ligi naroda, postaće DAO po predlozima igrača ako se dobro pokaže i moćiće da poradi na ekonomiji.
