### ISSUE TITLE
Mladen za Dzelata

### ISSUE THREAD

**Issue by miki-00** [PiweeX/PiweeX#372]
Igrac Mladen05 aka Mladen_19 je jedan od najstarijih i najaktivnijih igraca HogRealmsa. Nije imao nikakav dosije cak niti ikakav mute. Upoznat je sa cenama odlicno decko je mnogo dobro vaspitan ucen i zna sta radi na Hogu. Zna sva pravila ne krsi ih i postuje ih konstantno
Pomaze novim igracima Hoga predlaze za drzave objasnava im kako na Hogu stvari rade. Svaka tema na git hubu mu je bila uspesna i imao je najbolje argumente
Nikad nisam video da se sa nekim svadja ili nekoga da vredja sto je plus jer nije problematican a to treba dzelatu
Zna sve cene zna dobro oko discorda i minecraft komande iskusan je staff zna dosta o igracima kakvi su da li mogu nesto da urade i da li im je takva priroda sto mu pomaze da samim tim resava slucajeve bez problema
Nema problema sa sadasnjim staff timom sto je odlicno jer nece biti problema u saradnji sa njima
Najbolja preporuka serveru je da Mladen dobije dzelata
Svako ko se slaze nek napise:
#MladenZaDzelata

**Comment by AcaaVucko** [comment]
#AcaEkonomista

**Comment by miki-00** [comment]
Molim za ozbiljnost

**Comment by AcaaVucko** [comment]
Ako mi ovo piše miki trska dve hiljade i  deseto onda stvarno mislim da je vreme za ozbiljnost.
Mislim da dželat ne može postati neko preko ovoga nekakvog "teksta" jednostavno Piwex sam vidi kako je ko najaktivniji i ko se dosta razume u Hog, iskreno poštujem Mladena, dečko je dobar znači stariji i verovatno iskusniji od mene.
Ako gledamo njegovu aktivnost nije igrao prošlih meseci, igra sad aktivno verovatno je bio neaktivan zbog škole što poštujem, ako gledamo cene što je napisao mogu reći da sam skoro pa i zadovaljan, ne u svemu ali dobro je uradio.
Pri biranju novog dželata ja imam par njih koje bih mogao da iznesem koji su stariji članovi Hoga, samim tim igraju od bete do dan danas, igraju na dnevnom nivou i idalje su dosta aktivni tako da.. Srećno Mladene ako postaneš Ekonomist. :)

**Comment by Mladen0005** [comment]
Hvala,naravno postepeno i trenutno se nadam da cu biti zaposljen naravno svi bi voleli da budu dzelati ali trenunto je to teško prosli mesec nisam bio aktivan jer sam imao dosta posla skola,Isao sam na takmicenje iz programiranje te sam morao da se spremam a i imam jake treninge jer treba da potpišem novi ugovor,te od sada cu biti dosta akitavan ako i pre i provodicu dosta vremena naravno sto se tice moje ideje zasniva se na vise nivoa pa sam stavio središnju cenu jer ekonomiju ne mogu da gledam sada za sada jer moramo pratiti kako se krece rast novca i prodaje.hvala cone na komentaru

**Comment by AcaaVucko** [comment]
Nema na čemu, pre svega da ti čestitam na tvom takmičenju iz programiranja, nadam si da si osvojio nešto ili slično.
Današnje vreme je teško za igranje samim tim što većine igrača je đak srednje škole i zajebano je odvojiti vreme za učenje i za Hog, poštujem i tvoje dosadašnje igranje i tvoju aktivnost na Hogu, stariji si imaš 19 godina koliko već, to su velike već godine.
Vidim da se trudiš da popraviš cenu Hoga, mi to poštujemo i treba nam svako ko ima dobre namere, naravno ovde je bitna i kritika u nekoj ruci tako da, želim sreću.

**Comment by Mladen0005** [comment]
Naravno nisam ja ni og igram nekih godinu ali sam dosta zainteresovan jer volim Politiku i jako mi se svideo server kao ideja zato se i trudim, naravno da je malo teze odvojiti vreme ali se trudim da to bude sto vece,pogotovo sada se uporedno spremam jer sam proso na republičko ali sam se dobro organizovao te sada nece biti problema server trenutno ima velike probleme sa ekonomijom a ja mislim da to mogu da resim makar u nekoj meri da ne bude velika stopa inflacije kao sto je naprimer bila u decembru i sada ralizka u cenama je oko 220% u padu i treba po mom misljenju da padne za jos 5 do 6% i da pokusamo da odrzimo rast ekonomije sa istim cenama

**Comment by NemanjaRusija** [comment]
> Ako mi ovo piše miki trska dve hiljade i deseto onda stvarno mislim da je vreme za ozbiljnost. Mislim da dželat ne može postati neko preko ovoga nekakvog "teksta" jednostavno Piwex sam vidi kako je ko najaktivniji i ko se dosta razume u Hog, iskreno poštujem Mladena, dečko je dobar znači stariji i verovatno iskusniji od mene. Ako gledamo njegovu aktivnost nije igrao prošlih meseci, igra sad aktivno verovatno je bio neaktivan zbog škole što poštujem, ako gledamo cene što je napisao mogu reći da sam skoro pa i zadovaljan, ne u svemu ali dobro je uradio. Pri biranju novog dželata ja imam par njih koje bih mogao da iznesem koji su stariji članovi Hoga, samim tim igraju od bete do dan danas, igraju na dnevnom nivou i idalje su dosta aktivni tako da.. Srećno Mladene ako postaneš Ekonomist. :)

slažem se

**Comment by NemanjaRusija** [comment]
al miki trska je kriminal

**Comment by NemanjaRusija** [comment]
Ovo se treba zatvorit, jer nama treba ekonomist, ne dželat

**Comment by vukstrale** [comment]
> Ovo se treba zatvorit, jer nama treba ekonomist, ne dželat

Jel neko rekao ekonomista koji se razume u sisteme servera, ekonomiju, abjuz, bugove, OP stvari, majmunisanje, staff tim i zove se Vuk Obrisati?

**Comment by PiweeX** [comment]
predlog je prošao, čestitam Mladenu

proćiće veću proveru pre nego što postane DAO.
