### ISSUE TITLE
Rp Liga

### ISSUE THREAD

**Issue by FarisSpaha** [PiweeX/PiweeX#379]
[Izvorna poruka obrisana, pisac ispao glup].

**Comment by HoseArmando** [comment]
Dovelo bi do situacije koja je bila i pre RP lige, a posle nekog izvesnog vremena došli bi isti ti ljudi i stvorili rp ligu jer zašto da ne, ne možemo lepo igrati bez rp lige.
RP liga ne tone, već vi ne radite tiketi, kako je rp liga lepo funkcionisala dok su bili Attack i Stipe dnevno aktivni, svašta su odgovarali i primali samo određene države, a ne neke tamo Republiku Krompir.
Isto kao kad bih ja otvorio issue da zatvorimo LN i da ne bude više LN, jer ono šta će nam.
Ako ne radite posao dobro, predajte ga drugima koji možda imaju viziju kako bi rp liga mogla biti popravljena. Nema na čemu unapred

**Comment by HoseArmando** [comment]
"svako može da rp-a šta želi" daj druže jel si realan?
Pa doći će ono vreme kada su u Africi pravljena sela iz Bosne, kada je Brčko bio u Južnoj Americi, doveli bi do toga da bi najmoćnije sile sada promenile svoje ime u Bakugan i Naruto Clan nešto lupam.
Zašta su se Englezi, Asirci sada Vizantijci, Japanci i ostali borili svo vreme, pa da bi ostavili najbolji rp što je Hog ikad video.

**Comment by PiweeX** [comment]
evo moje poruke od danas da ne pišem opet, iz priv četa


**e što se tiče ovih predloga za ekonomiju, ekonomičar će biti Mladen ali nema smisla da bude samo to već bi bilo dobro da postane DAO a da se kao DAO bavi i ekonomijom i granicama na RP ligi tj. tiketima tu jer eto sad imamo odličan support na Ligi naroda za opšti support a na rp ligi je support uzas, ima tona tiketa**

**Comment by HoseArmando** [comment]
Da, Mladen zaslužuje da bude to što treba biti.
Ali što se tiče RP lige neće nestati, ako farise nisi sposoban predat ćeš ulogu nekoj osobi koja se javi da održava, naprimer Viktor vidim da je dosta aktivan i da je neki stuff na rp lizi nisam tačno siguran. Ako on želi može da postane i možda promeni rp ligu, ili bilo ko drugi.

**Comment by PiweeX** [comment]
a što se tiče ovoga ja sam od početka pisao da se ne pravi poseban discord server za Roleplay jer smo u Ligi naroda tj tad se zvao UN imali roleplay članove tj kako se zvalo ne sećam se ali u suštini hteli su da naprave poseban server i eto

pokazalo se jako dobro ali opet mnogo se gubi poverenje igrača kad se ne odgovori na tiket po 2 nedelje a mapa nacrta za mesec dana. 

Uglavnom mi smo i HogoMaps imali poseban jer su sve te ključne servere pravili igrači što je i ključ servera ali onda imamo problem da ako su ti serveri ključni a nemaju dobru organizaciju mnogo štete serveru i teraju igrače. Tako da ja predlazem da se na Ligi naroda prebace svi ključni kanali sa RP lige kao što smo i HogoMaps prebacili na RP ligu pre par meseci pa se pokazalo kao dobro

**Comment by FarisSpaha** [comment]
> "svako može da rp-a šta želi" daj druže jel si realan?
> 
> Pa doći će ono vreme kada su u Africi pravljena sela iz Bosne, kada je Brčko bio u Južnoj Americi, doveli bi do toga da bi najmoćnije sile sada promenile svoje ime u Bakugan i Naruto Clan nešto lupam.
> 
> Zašta su se Englezi, Asirci sada Vizantijci, Japanci i ostali borili svo vreme, pa da bi ostavili najbolji rp što je Hog ikad video.


Nismo atlas, to se podrazumeva da ne moze, dalje naveo sam da nema tih crtaca i gluposti. Za tikete, tiketa nema ili ljude otvore i drze praznim neka se ponudi neko ko zeli da vodi, propicat cu sa njim nije mi problem predati poziciju jer ne zelim da nanosim stetu drugima pozz

**Comment by FarisSpaha** [comment]
Pregledani svi tiketi za hog maps, mapa ce biti kada front bude dostupan prelazim na pregled rp tiketa. Molio bih px da ostavi ovo da mogu pisati sta se desava

**Comment by FarisSpaha** [comment]
> evo moje poruke od danas da ne pišem opet, iz priv četa
> 
> 
> 
> 
> 
> **e što se tiče ovih predloga za ekonomiju, ekonomičar će biti Mladen ali nema smisla da bude samo to već bi bilo dobro da postane DAO a da se kao DAO bavi i ekonomijom i granicama na RP ligi tj. tiketima tu jer eto sad imamo odličan support na Ligi naroda za opšti support a na rp ligi je support uzas, ima tona tiketa**
> 
> 


Da ga dodam u rp ligu u admine? Ne mogu sam pregledati tikete zao mi je, kada stignem pregledam, sad sam uhvatio vremena i pregledam

**Comment by HoseArmando** [comment]
Додај мене Фарисе, ја сам цоне па ћу ти помоћ

**Comment by NemanjaRusija** [comment]
> tiče ovoga ja sam od početka pisao da se ne pravi poseban discord server za Roleplay jer smo u Ligi naroda tj tad se zvao UN imali roleplay članove tj kako se zvalo ne sećam se ali u suštini hteli su da naprave pos

ne može se porediti RP liga, sa leggy UN-om

**Comment by FarisSpaha** [comment]
> Додај мене Фарисе, ја сам цоне па ћу ти помоћ
> 
> 

Vrlo rado, mislim da bi dosta pomogao i aktivirao sve, usput svi tiketi pregledani

**Comment by Mladen0005** [comment]
Farise dodaj me odgovaracu na tikete za sta ne budem znao odgovor tagacu tb ili coneta,trudicu se da pomognem na sto vise,da smanjimo broj malo

**Comment by PiweeX** [comment]
dogovoreno je da se RP liga prebacuje na Ligu naroda iliti nekadašnji UN


Kreiran je bot za support za graničnu policiju, već je u funkciji, sutra završavamo ostatak

**Comment by PiweeX** [comment]
završen je ostatak, ostalo je još da se bot malo uredi i da Spaho završi sa njihovim roleovima i kategorijom i to je to

a što se tiče RP liga discord servera svi su kikovani i to je to
