### ISSUE TITLE
Nations plugin i claimanje

### ISSUE THREAD

**Issue by FarisSpaha** [PiweeX/PiweeX#381]
Opet ja, bit cu kratak. Nisam siguran da li je ovo u okviru land plugina ali da se ospsobi. Kao sto znamo mnogi igraci claimaju samo ivice i onda se to na mapi popuni. To treba da se zabrani. Takodjer, kada se claimaju gradovi pravi se nacija, komandom /nations create ime. Karta je trenutno sva zelena, opcija ovog plugina jeste da se stavi boja, tako da bi mapa licila na nesto. Svi claimovi koji su ogromni i svima nama je jasno kako su nastali, neka se izbrise a novac vrati kreatorima istih. Mislim da bi ovo bilo dobro i za politcku kartu, jer kada neko od admina pogleda na kartu lakse ce biti ucrtati, sto znaci manje tiketa a cesca karta. Nadam se da je vecina za, havala unapred.

**Comment by PiweeX** [comment]
Stavljeno na glasanje

**Comment by FarisSpaha** [comment]
> Stavljeno na glasanje

do kad traje glasanje?

**Comment by vukstrale** [comment]
> Opet ja, bit cu kratak. Nisam siguran da li je ovo u okviru land plugina ali da se ospsobi. Kao sto znamo mnogi igraci claimaju samo ivice i onda se to na mapi popuni. To treba da se zabrani. Takodjer, kada se claimaju gradovi pravi se nacija, komandom /nations create ime. Karta je trenutno sva zelena, opcija ovog plugina jeste da se stavi boja, tako da bi mapa licila na nesto. Svi claimovi koji su ogromni i svima nama je jasno kako su nastali, neka se izbrise a novac vrati kreatorima istih. Mislim da bi ovo bilo dobro i za politcku kartu, jer kada neko od admina pogleda na kartu lakse ce biti ucrtati, sto znaci manje tiketa a cesca karta. Nadam se da je vecina za, havala unapred.

Hvala*

**Comment by marepleb** [comment]
GLASO SAM! Faris za nasu decu

**Comment by FarisSpaha** [comment]
> GLASO SAM! Faris za nasu decu

tako je Mare, mozda te pustim i rp ligu hahahaha

**Comment by FarisSpaha** [comment]
> > Opet ja, bit cu kratak. Nisam siguran da li je ovo u okviru land plugina ali da se ospsobi. Kao sto znamo mnogi igraci claimaju samo ivice i onda se to na mapi popuni. To treba da se zabrani. Takodjer, kada se claimaju gradovi pravi se nacija, komandom /nations create ime. Karta je trenutno sva zelena, opcija ovog plugina jeste da se stavi boja, tako da bi mapa licila na nesto. Svi claimovi koji su ogromni i svima nama je jasno kako su nastali, neka se izbrise a novac vrati kreatorima istih. Mislim da bi ovo bilo dobro i za politcku kartu, jer kada neko od admina pogleda na kartu lakse ce biti ucrtati, sto znaci manje tiketa a cesca karta. Nadam se da je vecina za, havala unapred.
> 
> 
> 
> Hvala*

hvala, lapsus je bio

**Comment by PiweeX** [comment]
PREDLOG PRIHVAĆEN


NACIJE OD UJUTRU PONOVO NA HOGU

**Comment by JaSamIgor** [comment]
Tooo piwexe
