### ISSUE TITLE
Dodavanje discord kanala za nove igrače.

### ISSUE THREAD

**Issue by NemanjaRusija** [PiweeX/PiweeX#382]
Pozdrav, pošto se Hog vraća polako, a nama u staffu sa sad testovi itd.. došao sam na ideju da se od discorda storyline napravi kanal za nove igrače. U tom kanalu da se doda ona moja pinovana poruka u četu (kako da krenu novi igrači i za podservere, tu poruku za podservere treba izmjeniti zbog dodavanja skyblovka i promjene kod BB-a.

**Comment by PiweeX** [comment]
Stavljeno na glasanje

**Comment by PiweeX** [comment]
dobro pošto je ovo već jako dugo predlagano od Nemanje i to bi mu olakšalo rad uvešćemo ovo ali pošto već duže vreme gledamo gde bi to moglo biti na Hog discordu zbog preglednosti to će biti na ligi naroda obzirom da tamo trenutno sprovodimo i nove zakone nakon što je rp liga uvedena

**Comment by PiweeX** [comment]
nisam napisao kad će biti

što pre, kad uvedemo zakone onda
