### ISSUE TITLE
Promjena granica za drzave

### ISSUE THREAD

**Issue by VukIcrnogorskii** [PiweeX/PiweeX#383]
Trebalo bi da se promijene granice postojanja drzava sa 7 vijeka do 17 vijeka mozda na 476 do savremenog doba, jer neke stvari bas nemaju smisla a i prave se nove drzave koju su poslije sedamnaestog vijeka. Sto se tice smisla  mi imamo podmornice avione busilice traktore itd itd a nismo izucili sta je americki kontinent. bas je malo besmisleno pa bi zato trebali da izmijenjamo te vremenske granice

**Comment by DaniloU0** [comment]
Potpuno se slažem jer ja rpam 20. vek sa SHSom i ide mi super i taj rp sam doktorirao, nema potrebe da se državama menjaju imena ako se da malo mašte i volje kao što je to Zlaja radio i uvek su mu klipovi ispadali super oko ratova na primer

**Comment by mikitriske** [comment]
slazem se sa Vukom a i on ima vise iskustva od sadasnjih "role play admina" koji nisu neki poznavaoci rpa i nisu bas dobri u tome ali Boze moj napisu tekst od 1000 reci sa vanzemaljcima pa prodju da znaju rp

**Comment by JaSamIgor** [comment]
Podmornice i bušilice retko ko ima, dok samo jedan avion postoji na hogu (a ono podmornice ni čemu ne služe). Međutim oklopi, mačevi, lukovi su prisutni kod skoro, ako ne svih igrača. Takođe preko storija je za mainnet najavljeno da će se dodati posebni srednjovjekovni itemi koji bi znatno poboljšali roleplay srednjeg vjeka i zato bi bilo ljepo da se prije toga odredi vremenski period Hoga koji bi bio iza modernog doba jer će te stvari (vjerovatno) služiti više nego ovo što si ti gore naveo. Osim ovoga bio bi veliki problem oko ratova

E sad zamisli ovo, neko napravi moderni SAD i sada on objavi rat na Kraljevinu Englesku. Amerikanci bi išli do Evrope sa običnim drvenim brodovima gdje bi pri dolaskom na neki pomorski grad Engleske iskrcali se i tukli mačevima....

**Comment by VukIcrnogorskii** [comment]
> Podmornice i bušilice retko ko ima, dok samo jedan avion postoji na hogu (a ono podmornice ni čemu ne služe). Međutim oklopi, mačevi, lukovi su prisutni kod skoro, ako ne svih igrača. Takođe preko storija je za mainnet najavljeno da će se dodati posebni srednjovjekovni itemi koji bi znatno poboljšali roleplay srednjeg vjeka i zato bi bilo ljepo da se prije toga odredi vremenski period Hoga koji bi bio iza modernog doba jer će te stvari (vjerovatno) služiti više nego ovo što si ti gore naveo. Osim ovoga bio bi veliki problem oko ratova
> 
> E sad zamisli ovo, neko napravi moderni SAD i sada on objavi rat na Kraljevinu Englesku. Amerikanci bi išli do Evrope sa običnim drvenim brodovima gdje bi pri dolaskom na neki pomorski grad Engleske iskrcali se i tukli mačevima....

Hog je rp server i nije sva sustina u u macevima nego je glavni aspekt na lore i pricu, malo je ljudi sa ovim vozilima jer su teska da se dobiju ali u svakom slucaju se prave duple arsine i nejasnoce, kao so je i miki rekao igrao sam na mnoge servere i nase i strane i znam kako ovo fukncionise. I najvise se na akcentu daje upravo na prici i roleplayu drzave, tako da smatram da bi trebalo ovo da promijenimo kako ne bi sputavali ljude koji imaju ideju sa nekim rpom koji nije samo evropa ili daleki istok. ovako dosta kaskamo i samo sputavamo sami sebe

**Comment by JaSamIgor** [comment]
> > Podmornice i bušilice retko ko ima, dok samo jedan avion postoji na hogu (a ono podmornice ni čemu ne služe). Međutim oklopi, mačevi, lukovi su prisutni kod skoro, ako ne svih igrača. Takođe preko storija je za mainnet najavljeno da će se dodati posebni srednjovjekovni itemi koji bi znatno poboljšali roleplay srednjeg vjeka i zato bi bilo ljepo da se prije toga odredi vremenski period Hoga koji bi bio iza modernog doba jer će te stvari (vjerovatno) služiti više nego ovo što si ti gore naveo. Osim ovoga bio bi veliki problem oko ratova
> > E sad zamisli ovo, neko napravi moderni SAD i sada on objavi rat na Kraljevinu Englesku. Amerikanci bi išli do Evrope sa običnim drvenim brodovima gdje bi pri dolaskom na neki pomorski grad Engleske iskrcali se i tukli mačevima....
> 
> Hog je rp server i nije sva sustina u u macevima nego je glavni aspekt na lore i pricu, malo je ljudi sa ovim vozilima jer su teska da se dobiju ali u svakom slucaju se prave duple arsine i nejasnoce, kao so je i miki rekao igrao sam na mnoge servere i nase i strane i znam kako ovo fukncionise. I najvise se na akcentu daje upravo na prici i roleplayu drzave, tako da smatram da bi trebalo ovo da promijenimo kako ne bi sputavali ljude koji imaju ideju sa nekim rpom koji nije samo evropa ili daleki istok. ovako dosta kaskamo i samo sputavamo sami sebe

Na serveru postoje custom države poput Pacifičkog Diktata koje prave same svoj roleplay ali imaju tehnologiju u skladu sa 17 vijekom. Prerano je premještati godine dok se ne dodaju posebni itemi

**Comment by Viktor023023** [comment]
Imam ja avion

**Comment by VukIcrnogorskii** [comment]
> > Podmornice i bušilice retko ko ima, dok samo jedan avion postoji na hogu (a ono podmornice ni čemu ne služe). Međutim oklopi, mačevi, lukovi su prisutni kod skoro, ako ne svih igrača. Takođe preko storija je za mainnet najavljeno da će se dodati posebni srednjovjekovni itemi koji bi znatno poboljšali roleplay srednjeg vjeka i zato bi bilo ljepo da se prije toga odredi vremenski period Hoga koji bi bio iza modernog doba jer će te stvari (vjerovatno) služiti više nego ovo što si ti gore naveo. Osim ovoga bio bi veliki problem oko ratova
> > E sad zamisli ovo, neko napravi moderni SAD i sada on objavi rat na Kraljevinu Englesku. Amerikanci bi išli do Evrope sa običnim drvenim brodovima gdje bi pri dolaskom na neki pomorski grad Engleske iskrcali se i tukli mačevima....
> 
> Hog je rp server i nije sva sustina u u macevima nego je glavni aspekt na lore i pricu, malo je ljudi sa ovim vozilima jer su teska da se dobiju ali u svakom slucaju se prave duple arsine i nejasnoce, kao so je i miki rekao igrao sam na mnoge servere i nase i strane i znam kako ovo fukncionise. I najvise se na akcentu daje upravo na prici i roleplayu drzave, tako da smatram da bi trebalo ovo da promijenimo kako ne bi sputavali ljude koji imaju ideju sa nekim rpom koji nije samo evropa ili daleki istok. ovako dosta kaskamo i samo sputavamo sami sebe

jeste al pacificki diktat ima smisla za postojanje al kako bi npr oni interagovali sa svijetom kad u to vrijeme mi nismo znali ni sta su havaji a ne ostrva po pacifiku

**Comment by VukIcrnogorskii** [comment]
> > > Podmornice i bušilice retko ko ima, dok samo jedan avion postoji na hogu (a ono podmornice ni čemu ne služe). Međutim oklopi, mačevi, lukovi su prisutni kod skoro, ako ne svih igrača. Takođe preko storija je za mainnet najavljeno da će se dodati posebni srednjovjekovni itemi koji bi znatno poboljšali roleplay srednjeg vjeka i zato bi bilo ljepo da se prije toga odredi vremenski period Hoga koji bi bio iza modernog doba jer će te stvari (vjerovatno) služiti više nego ovo što si ti gore naveo. Osim ovoga bio bi veliki problem oko ratova
> > > E sad zamisli ovo, neko napravi moderni SAD i sada on objavi rat na Kraljevinu Englesku. Amerikanci bi išli do Evrope sa običnim drvenim brodovima gdje bi pri dolaskom na neki pomorski grad Engleske iskrcali se i tukli mačevima....
> > 
> > 
> > Hog je rp server i nije sva sustina u u macevima nego je glavni aspekt na lore i pricu, malo je ljudi sa ovim vozilima jer su teska da se dobiju ali u svakom slucaju se prave duple arsine i nejasnoce, kao so je i miki rekao igrao sam na mnoge servere i nase i strane i znam kako ovo fukncionise. I najvise se na akcentu daje upravo na prici i roleplayu drzave, tako da smatram da bi trebalo ovo da promijenimo kako ne bi sputavali ljude koji imaju ideju sa nekim rpom koji nije samo evropa ili daleki istok. ovako dosta kaskamo i samo sputavamo sami sebe
> 
> jeste al pacificki diktat ima smisla za postojanje al kako bi npr oni interagovali sa svijetom kad u to vrijeme mi nismo znali ni sta su havaji a ne ostrva po pacifiku

A i drugo primjer pacifickog diktata diktati se javljaju tek tridesetih godina dvadesetog vijeka

**Comment by PiweeX** [comment]
Stavljeno je na glasanje

**Comment by JaSamIgor** [comment]
> > > Podmornice i bušilice retko ko ima, dok samo jedan avion postoji na hogu (a ono podmornice ni čemu ne služe). Međutim oklopi, mačevi, lukovi su prisutni kod skoro, ako ne svih igrača. Takođe preko storija je za mainnet najavljeno da će se dodati posebni srednjovjekovni itemi koji bi znatno poboljšali roleplay srednjeg vjeka i zato bi bilo ljepo da se prije toga odredi vremenski period Hoga koji bi bio iza modernog doba jer će te stvari (vjerovatno) služiti više nego ovo što si ti gore naveo. Osim ovoga bio bi veliki problem oko ratova
> > > E sad zamisli ovo, neko napravi moderni SAD i sada on objavi rat na Kraljevinu Englesku. Amerikanci bi išli do Evrope sa običnim drvenim brodovima gdje bi pri dolaskom na neki pomorski grad Engleske iskrcali se i tukli mačevima....
> > 
> > 
> > Hog je rp server i nije sva sustina u u macevima nego je glavni aspekt na lore i pricu, malo je ljudi sa ovim vozilima jer su teska da se dobiju ali u svakom slucaju se prave duple arsine i nejasnoce, kao so je i miki rekao igrao sam na mnoge servere i nase i strane i znam kako ovo fukncionise. I najvise se na akcentu daje upravo na prici i roleplayu drzave, tako da smatram da bi trebalo ovo da promijenimo kako ne bi sputavali ljude koji imaju ideju sa nekim rpom koji nije samo evropa ili daleki istok. ovako dosta kaskamo i samo sputavamo sami sebe
> 
> jeste al pacificki diktat ima smisla za postojanje al kako bi npr oni interagovali sa svijetom kad u to vrijeme mi nismo znali ni sta su havaji a ne ostrva po pacifiku

Već imaju neke dosta dobre priče za to u RP ligi, to će biti lakše povezati nego ovo ostalo. Bar meni nekako više ima smisla da bude prije modernog doba, kako zbog itema koji su najavljeni tako i zbog ratova.

**Comment by VukIcrnogorskii** [comment]
> > > > Podmornice i bušilice retko ko ima, dok samo jedan avion postoji na hogu (a ono podmornice ni čemu ne služe). Međutim oklopi, mačevi, lukovi su prisutni kod skoro, ako ne svih igrača. Takođe preko storija je za mainnet najavljeno da će se dodati posebni srednjovjekovni itemi koji bi znatno poboljšali roleplay srednjeg vjeka i zato bi bilo ljepo da se prije toga odredi vremenski period Hoga koji bi bio iza modernog doba jer će te stvari (vjerovatno) služiti više nego ovo što si ti gore naveo. Osim ovoga bio bi veliki problem oko ratova
> > > > E sad zamisli ovo, neko napravi moderni SAD i sada on objavi rat na Kraljevinu Englesku. Amerikanci bi išli do Evrope sa običnim drvenim brodovima gdje bi pri dolaskom na neki pomorski grad Engleske iskrcali se i tukli mačevima....
> > > 
> > > 
> > > Hog je rp server i nije sva sustina u u macevima nego je glavni aspekt na lore i pricu, malo je ljudi sa ovim vozilima jer su teska da se dobiju ali u svakom slucaju se prave duple arsine i nejasnoce, kao so je i miki rekao igrao sam na mnoge servere i nase i strane i znam kako ovo fukncionise. I najvise se na akcentu daje upravo na prici i roleplayu drzave, tako da smatram da bi trebalo ovo da promijenimo kako ne bi sputavali ljude koji imaju ideju sa nekim rpom koji nije samo evropa ili daleki istok. ovako dosta kaskamo i samo sputavamo sami sebe
> > 
> > 
> > jeste al pacificki diktat ima smisla za postojanje al kako bi npr oni interagovali sa svijetom kad u to vrijeme mi nismo znali ni sta su havaji a ne ostrva po pacifiku
> 
> Već imaju neke dosta dobre priče za to u RP ligi, to će biti lakše povezati nego ovo ostalo. Bar meni nekako više ima smisla da bude prije modernog doba, kako zbog itema koji su najavljeni tako i zbog ratova.

A dobro i ti ides sad iz coska u cosak ne nego nuklearno oruzje pojenta je da vecina drzava nije postojala do 20 vijeka ili 21 i da treba da se ta granica promijeni kako bi bilo mnogo vise rp opportunityija za ljude koji dodju na server

**Comment by FarisSpaha** [comment]
Obje strane imaju poentu i znaju sta pricaju, neka se stavi na glasanje jer mislim da ovom promjenom mozemo samo dobiti na rp-u, takodjer jednostavno nemam duse i zao mi je da kaznjavam drzave zbog vremena rp-a na zahtjev drugih igraca, moj je prijedlog od 476.-2023. neka rp a svako drzavu koju zeli u tom periodu, takodjer bih volio vidjeti vise custom drzava poput pcf diktata, ali ne mitove i to. Ne zelim da imam Minotaurovu republiku na hogu

**Comment by FarisSpaha** [comment]
i ja bih takodjer, Vuku dak priliku kao rp admin jer je igrao i na nasim i na stranim serverima, i vidim da zna sta prica ako se px slaze naravno. Dok Cone bi pomogao oko tiketa i uz pomoc vuka ne bih morao sve odluke ja da donosim

**Comment by VukIcrnogorskii** [comment]
> i ja bih takodjer, Vuku dak priliku kao rp admin jer je igrao i na nasim i na stranim serverima, i vidim da zna sta prica ako se px slaze naravno. Dok Cone bi pomogao oko tiketa i uz pomoc vuka ne bih morao sve odluke ja da donosim

I ja i ti znamo koliko god ti govorio istinu i koliko god bio upravo i koliko god to bilo dobro za server da se to nece desiti

**Comment by vukstrale** [comment]
Ja bi držao vuleta dalje od staff tima. no hejt vule voli tebe brat

**Comment by VukIcrnogorskii** [comment]
> Ja bi držao vuleta dalje od staff tima. no hejt vule voli tebe brat

A znam brate to bi lose bilo po tebe da sam ja u njega

**Comment by vukstrale** [comment]
> > Ja bi držao vuleta dalje od staff tima. no hejt vule voli tebe brat
> 
> A znam brate to bi lose bilo po tebe da sam ja u njega

Što? Jednako ignorišem roleplay i sa tobom i bez tebe fr

**Comment by VukIcrnogorskii** [comment]
Pa dobro mislim zavisi na kojoj poziciji bi bio ja koliko bi ti ignorisao rp

**Comment by vukstrale** [comment]
> Pa dobro mislim zavisi na kojoj poziciji bi bio ja koliko bi ti ignorisao rp

bmk da si owner servera ignorišem RP ali samim tim i ne učestvujem u RP dogadjajima

**Comment by VukIcrnogorskii** [comment]
Samo mi se nemoj nervirat. Nema potrebe za jednostranom tenziom... Mi ovdje sasvim civilizovano pricamo i dovodimo pojedine primjere u obzir ili opsticaj :)

**Comment by vukstrale** [comment]
just sain bro just sain

**Comment by VukIcrnogorskii** [comment]
You mean just saying bro?

**Comment by vukstrale** [comment]
> You mean just saying bro?

Nedostajao si mi Vule

**Comment by VukIcrnogorskii** [comment]
> > You mean just saying bro?
> 
> Nedostajao si mi Vule

E Vuki Vuki

**Comment by marepleb** [comment]
> Trebalo bi da se promijene granice postojanja drzava sa 7 vijeka do 17 vijeka mozda na 476 do savremenog doba, jer neke stvari bas nemaju smisla a i prave se nove drzave koju su poslije sedamnaestog vijeka. Sto se tice smisla mi imamo podmornice avione busilice traktore itd itd a nismo izucili sta je americki kontinent. bas je malo besmisleno pa bi zato trebali da izmijenjamo te vremenske granice

od 200 pne do 1600 isk

**Comment by marepleb** [comment]
> Obje strane imaju poentu i znaju sta pricaju, neka se stavi na glasanje jer mislim da ovom promjenom mozemo samo dobiti na rp-u, takodjer jednostavno nemam duse i zao mi je da kaznjavam drzave zbog vremena rp-a na zahtjev drugih igraca, moj je prijedlog od 476.-2023. neka rp a svako drzavu koju zeli u tom periodu, takodjer bih volio vidjeti vise custom drzava poput pcf diktata, ali ne mitove i to. Ne zelim da imam Minotaurovu republiku na hogu

iskreno bih te zamolio da ne jedes govna hvala!

**Comment by FarisSpaha** [comment]
> > Obje strane imaju poentu i znaju sta pricaju, neka se stavi na glasanje jer mislim da ovom promjenom mozemo samo dobiti na rp-u, takodjer jednostavno nemam duse i zao mi je da kaznjavam drzave zbog vremena rp-a na zahtjev drugih igraca, moj je prijedlog od 476.-2023. neka rp a svako drzavu koju zeli u tom periodu, takodjer bih volio vidjeti vise custom drzava poput pcf diktata, ali ne mitove i to. Ne zelim da imam Minotaurovu republiku na hogu
> 
> 
> 
> iskreno bih te zamolio da ne jedes govna hvala!



neces uci u rp ligu sa svojom kinom nemoj da pokusavas

**Comment by marepleb** [comment]
> > > Obje strane imaju poentu i znaju sta pricaju, neka se stavi na glasanje jer mislim da ovom promjenom mozemo samo dobiti na rp-u, takodjer jednostavno nemam duse i zao mi je da kaznjavam drzave zbog vremena rp-a na zahtjev drugih igraca, moj je prijedlog od 476.-2023. neka rp a svako drzavu koju zeli u tom periodu, takodjer bih volio vidjeti vise custom drzava poput pcf diktata, ali ne mitove i to. Ne zelim da imam Minotaurovu republiku na hogu
> > 
> > 
> > iskreno bih te zamolio da ne jedes govna hvala!
> 
> neces uci u rp ligu sa svojom kinom nemoj da pokusavas

zabolje me ceo kurac

**Comment by FarisSpaha** [comment]
Zasto ne bismo ukinuli uopste granicu za rp, jer imali smo spartu sad kaliforniju, ali da se rp bazira na srednji vijek. Mislim da je ovo najrealnije i stavaralo bi najmanje problema

**Comment by PiweeX** [comment]
nije izglasano u ovom issue-u
