### ISSUE TITLE
Shop

### ISSUE THREAD

**Issue by yamizvaniuchicha** [PiweeX/PiweeX#392]
Pre duze vreme ukinut je shop ja serveru, posto shop nije nista skodio serveru i ukinut je jer su igraci govorili da je server p2w za sta se vecina servera ne slaze posto je sad vec dosta njih kupilo rankove. Moj predlog jeste da se vrati oficionalni shop sa sajtom i da se doda jos stvari sem onih od pre

**Comment by PiweeX** [comment]
videcemo

**Comment by PiweeX** [comment]
shop se neće vraćati nikad, shop je izgubio support jer je MNB udruženje koje se finansira iz našeg fonda, znači nema shopa jer je ugašen support za njega ali se rankovi mogu kupovati dok svi ne isteknu (do 11. ili 12. meseca 2023.)
