### ISSUE TITLE
UHC POVRATAK NA HOG

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#404]
sve su straže sve su straže

ne sme da se kaže

![2023-04-30_19 33 08](https://user-images.githubusercontent.com/33425430/235368281-69baf603-7d1b-423d-a8a6-65962b40c42c.png)

**Comment by marepleb** [comment]
> sve su straže sve su straže
> 
> ne sme da se kaže
> 
> ![2023-04-30_19 33 08](https://user-images.githubusercontent.com/33425430/235368281-69baf603-7d1b-423d-a8a6-65962b40c42c.png)

maretov povratak soon?

**Comment by PiweeX** [comment]
objavljene su nagrade u art kutak

nagrade su za danasnji UHC

**Comment by PiweeX** [comment]
15h je, provešću do 18h uređivajući uhc podserver za večerašnji game

sve je najavljeno na LN i na hogrealms instagramu.

**Comment by PiweeX** [comment]
18 i 17h je, skoro sve je spremno

fajlovi će biti sređeni do kraja za nekih 20ak minuta,

pored toga testiran je i game na 5k borderu

isto tako i spawn je pri kraju, 40 minuta ranije nego što smo mislili

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/235725692-12243afe-5eba-4302-b916-8cbe924d6263.png)


slika spawna, od dole je puno bolje


hvala svima koji su pomogli u izgradnji!

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/235726207-e81fdb57-4b86-4de8-adf7-54abd09a4ba7.png)


hvala svima!

**Comment by PiweeX** [comment]
parkour testira red

**Comment by PiweeX** [comment]
bezbedonosne provere da se vidi da ne izadju negde xd, pusteno je jos par igraca na server tj. usli su

**Comment by PiweeX** [comment]
jos 1 probni game

**Comment by PiweeX** [comment]
Male izmene i dodat je link za LN discord direktno u Provere kanal u poruku koju svako ko bude zamrznut dobije pri proveri

**Comment by PiweeX** [comment]
treba srediti tab do 20h

**Comment by PiweeX** [comment]
anticheat je ubacen ali bice tek od narednog uhc-a

**Comment by PiweeX** [comment]
game je gotov, čestitam pobedniku

imali smo problema sa krešom, ja se nadam da se to neće ponoviti

![2023-05-02_20 21 47](https://user-images.githubusercontent.com/33425430/235799169-ed72d7d2-58a2-401c-ba2f-81ab41de1b98.png)
![2023-05-02_20 29 48](https://user-images.githubusercontent.com/33425430/235799222-f2c086a6-4623-4dfe-81b4-32ab86d2616d.png)
![2023-05-02_21 15 28](https://user-images.githubusercontent.com/33425430/235799227-0478f2dc-5204-4c39-b4a7-d8735c333fb5.png)

**Comment by PiweeX** [comment]
![2023-05-02_20 42 23](https://user-images.githubusercontent.com/33425430/235799327-4e4d95b1-a6c9-4087-b0cc-db8767c83fb2.png)
![2023-05-02_21 57 04](https://user-images.githubusercontent.com/33425430/235799335-4a3fe5bb-6c94-4849-b9bb-123294112b62.png)
![2023-05-02_20 32 01](https://user-images.githubusercontent.com/33425430/235799363-4ed7a303-f7ef-4041-87be-f9cf2b8ba2dd.png)
![2023-05-02_18 20 11](https://user-images.githubusercontent.com/33425430/235799381-40e18b3b-611c-47ce-b9a1-2e10a090b913.png)
![2023-05-02_20 23 08](https://user-images.githubusercontent.com/33425430/235799460-7b7bafcf-69ef-4b0e-b377-8ac7a10d4cc5.png)

**Comment by PiweeX** [comment]
oko 47 igrača je bilo na UHC-u, hvala svima koji su doprineli da se ovaj meč odigra kako treba

sledeći će biti još bolji, ovaj je bio samo testni za povratak i zato je i bio po prvi put u utorak
