### ISSUE TITLE
Izbacivanje Bleeding efekta

### ISSUE THREAD

**Issue by vukstrale** [PiweeX/PiweeX#405]
Ja sam već četvrti igrač koji otvara isusse u vezi ovoga. Bleeding efekat je previše OP i užasno smanjuje FPS igračima sa lošijim mašinama (90% hoga). Takodje možeš ga zaobići, tj. da načiniš sebe imunim što ti daje unfair advantage u odnosu na igrače koji nisu iskoristili taj bug.

Verujem da je najbolje da se u potpunosti izbaci. Neka bude glasanje pa kako većina kaže.

Vaš, 
Vuk_TheGreat, helper obrisati

**Comment by marepleb** [comment]
ne

**Comment by PiweeX** [comment]
bleeding efekat je isključen obzirom da je bilo nekoliko issueova za njega gde je izglasan

sve je podešeno u konfiguraciji tako da ovo će stupiti na snagu od sutrašnjeg dana nakon restarta.
