### ISSUE TITLE
VRACANJE STARE CENE RIBA 

### ISSUE THREAD

**Issue by Zav1637** [PiweeX/PiweeX#415]
GLASAJTE OVDE DA SE VRATI STARA CENA RIBA NA HOGU !
AKO SE SLAZETE PISITE DA 
AKO NE ONDA PISITE NE!

**Comment by DaniloPanter** [comment]
Slažem se u potpunosti

**Comment by vukstrale** [comment]
Ne slažem se ni najmanje. Ovo naš ekonomista Mladen nikad neće aminovati. Prošle cene riba su bolesne, ceo server samo peca

**Comment by PiweeX** [comment]
stavljeno na glasanje, dajte i svoja misljenja vi koji glasate inace se glas NE vazi
