### ISSUE TITLE
Popraviti čet

### ISSUE THREAD

**Issue by NemanjaRusija** [PiweeX/PiweeX#432]
Čet je užasan i trebalo bi da se fixa

**Comment by mqtko** [comment]
Realno

**Comment by PiweeX** [comment]
premestio sam donji issue u ovaj, radimo na tome problem je sto je kad smo zbog ddosa prebacili na najnoviju verziju a plugin koji ima placeholdere tj. hovere po cetu je zastareo pa moramo da napravimo svoj ili da integrisemo neki koji uspemo

**Comment by PiweeX** [comment]
juče smo uradili velik update plugina tako da je čet popravljen, to videh iz nekog SC-a od danas iz art kutka. Nije gotov kako bi trebalo i kako će biti kad se srede hoveri ali poslužiće
