### ISSUE TITLE
Premium Login

### ISSUE THREAD

**Issue by mqtko** [PiweeX/PiweeX#433]
Novi ip preko kojeg ce se moci uci sa premium accountom bez da trazi sifru. Naprimer premium.hogrealms.com, razlog je da bi lunar radio lepo da se prikazuju kozmetike skinovi i to, a i lakse je za ulazenje igracima sa premiumom. Takodje mozda ce se moci promeniti ime na premiumu zbog roleplaya naprimer a da stats ostane i tako.

**Comment by PiweeX** [comment]
vlasnik platformi se slozio

resicemo na neki nacin ovo, ostace issue pa cemo izvestavati

**Comment by PiweeX** [comment]
odraditi nabavku

https://www.spigotmc.org/resources/%E2%96%A0-jpremium-%E2%96%A0-authorization-plugin-%E2%96%A0-automatic-login-premium-%E2%96%A0.27766/

**Comment by mqtko** [comment]
kad ce to biti?
