### ISSUE TITLE
Prodaja preko signa

### ISSUE THREAD

**Issue by JaSamIgor** [PiweeX/PiweeX#434]
Treba da se vrati da igraci mogu da postavljaju sign gde kupuju ili prodaju iteme, dosta je poboljsalo trgovinu servera. Ne vidim dobar razlog zasto je izbaceno
![2023-05-04_17 54 42](https://github.com/PiweeX/HogRealms/assets/107154813/74d86f46-cafb-4651-bb41-7c8b9377e016)

**Comment by PiweeX** [comment]
stavljeno na glasanje

**Comment by PiweeX** [comment]
ova stvar je usvojena

obrisali smo je, tačnije sklonili dozvole jer se nije koristila jer nije bila toliko prikazana javnosti da postoji a i nismo hteli da komplikujemo

u svakom slučaju vraćeno je jer smatramo da bi dosta pomoglo roleplay-u i trgovini uopšte
