### ISSUE TITLE
Aplikacija

### ISSUE THREAD

**Issue by mqtko** [PiweeX/PiweeX#440]
Ukoliko je moguce lepo bi bilo dodati hog decentraland aplikaciju za mapu na microsoft store da se moze gledatu ujedno na pcu a i da ne bude otkriven link zbog ddosa i tog sranja

**Comment by PiweeX** [comment]
igrači sa PC-a skidaju aplikaciju u BlueStacks, tako da je taj problem rešen ali hvala na predlogu

uglavnom možete koristiti BlueStacks
