### ISSUE TITLE
UHC problemi - od Coneta

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#445]
UHC problemi (Rešiti do sledećeg)

-Pri kopanju ruda, trebalo bi odmah da se rude pretvore u ingote, mnogo je lakše za igranje i dalje napredovanje tokom UHC-a.

-Hrana je bila važan faktor tokom prošlog UHC-a jer je bilo teško naći ili napraviti, nije bilo životinja tako da se hrana nije mogla sakupiti( Jedino jabuke i supa od pečuraka)

-Problem sa nevidljivim mobovima, desilo se da su igrači ubijeni ili napadnuti od ovih mobova, to su uglavnom bili nevidljivi cave pauci.

@PiweeeX
I da se malo više posveti tom spectatu igrača tokom tog finalnog kruga jer smo imali da su se SkyBase-ali i onda svi se žale itd itd
-Better enchants : Kada napraviš iteme od bilo kog materijala da postanu enčentovani (eff3 i unb 2) bi dobro došao kao jedan standardni enchent i to je bilo na prošlom UHC ali fazon dva minuta pa se isključilo.
I za swordove sharpness 3 i unb

**Comment by Viktor023023** [comment]
Ovo za rude je scenario, to se lako stavi. A za mobove ne znam da li mozes u settings da ugasis, vrv moze

**Comment by PiweeX** [comment]
scoreboard popravljen, potrebne su još neke veće izmene na njemu


takođe danas opet kreš u finalu pa smo ponovili sa stvarima i istom mapom ali mora da se reši kako bi UHC bio spreman za masivnije mečeve.. odrađene su neke promene u konfiguracijama i Java verzija je prebačena sa 17 na 8 tako da bi trebalo da bude bez problema u buduće ali videćemo kako sve bude išlo tek posle par mečeva jer ne krešuje svaki meč već samo nekad i to poremeti svu igranost i sve..


što se tiče ovoga za rude, to je scenario i predhodnih nekoliko mečeva smo usvojili

hrana, popravljeno, posebno smo omogućili njih u konfiguraciji tačnije životinje neke

nevidljivi mobovi su rešeni, samo je pauk ostao ali mislim da je i on predhodni meč rešen takođe


što se tiče posvećivanju oko spectateanja, Nemanja je preuzeo tu ulogu jer ja neću biti tu dosta dugo




SVE SA LISTE REŠENO!

**Comment by PiweeX** [comment]
TerrainControl plugin neophodan za uhc :dap:  ubacen
