### ISSUE TITLE
Land Name

### ISSUE THREAD

**Issue by mqtko** [PiweeX/PiweeX#463]
Predlazem da se maksimalna duzina imena claimova poveca zato sto se od sada claimovi nazivaju imenima gradova a neki grqdovi imaju vise od 10 slova kao naprimer moj Banjarmasin. Hvala

**Comment by PiweeX** [comment]
Stavljeno na glasanje

glasanje traje 3 dana

**Comment by mqtko** [comment]
oce biti?

**Comment by mqtko** [comment]
Alo siso

**Comment by PiweeX** [comment]
popusi kurac

**Comment by PiweeX** [comment]
salim se, uveo sam upravo od 15 slova maksimalno a bilo je maksimalno 10 tako da posle restarta ujutru mocicete da promenite naziv landa
