### ISSUE TITLE
Lidl Update

### ISSUE THREAD

**Issue by Viktor023023** [PiweeX/PiweeX#465]
Verujem da mnogi igrači zele ovo a to je da se Lidl tj. Shop na laputi updatea sa novim stvarima kao sto su prodaja svih ruda ukljucujuci i zlato koje svi cekamo duze vreme, prodaja drveca, hrane, kamena itd. Takodje da se uvede kupovina novih itema kao sto su npr shulker, ender chest, blaze rodovi i slicno. Novi shop se najvljuje duze vreme a mislim da bi Px to uradio za pola sata max tako da ko se slaze nek komentarise

**Comment by PiweeX** [comment]
stavljeno na glasanje

glasanje traje 3 dana

**Comment by PiweeX** [comment]
updateovali smo lidl, cone je objavio vise o tome na forumu na discordu
