### ISSUE TITLE
Promena zakona o claimu tudjih teritorije 

### ISSUE THREAD

**Issue by Mladen0005** [PiweeX/PiweeX#467]
Mislim da bi trebali da promenimo pravilo za claim tudjih teritorija,dosta igraca koji su novi ni ne znaju cije je sta pa mislim da Hag nije rešenje,po meni je bolje da se haga sve dok ne obrise teritoriju i vrati sve sto je uzo.

**Comment by DaniloU08** [comment]
Slažem se u potpunosti, samo  bih uveo i za stare igrače jer neko claima i svakako gubi novac šta mu odma pada na kaznu. Što se tiče krađe ili dupliranja, treba da se jaila dok ne vrati, a ako laže ili neće da vrati da mu se da hag po propisanom u zakonu kako piše već.

**Comment by PiweeX** [comment]
Stavljeno na glasanje

**Comment by PiweeX** [comment]
nek se stavi na glasanje na ligi naroda u sklopu MNB discorda
