### ISSUE TITLE
vracanje cena wheata

### ISSUE THREAD

**Issue by muvara123** [PiweeX/PiweeX#476]
zelimo cene nazad (18 wheata 48 dolara) jer se ekonomija raspala ko ku- jer se pare ne mogu dobiti i ne isplativo je 16 whita 20 dolara mislim stek whita je 80 dolara a ovako oko 140 i jos to sto su klejmovi poskkupeli isk bi voleo to promeniti

**Comment by vukstrale** [comment]
lmao ne

**Comment by PiweeX** [comment]
stavljeno je na glasanje

**Comment by PiweeX** [comment]
prebačeno u noviji issue od matka
