### ISSUE TITLE
Vracanje stare cene riba na hogu!

### ISSUE THREAD

**Issue by Zav1637** [PiweeX/PiweeX#478]
Vratite staru cenu riba na hogu ekonomija i sve se raspada pre je bilo odlicno sad ne mozes da dodjes do 1k ceo dan da grindas...
VRATITE STARE CENE !!!

**Comment by vukstrale** [comment]
lmao ne

**Comment by PiweeX** [comment]
isti issue ti je bio već 3 puta na glasanju, stavio sam opet

**Comment by PiweeX** [comment]
nije prošlo
