### ISSUE TITLE
Lidl

### ISSUE THREAD

**Issue by mqtko** [PiweeX/PiweeX#479]
Predlazem da se smanji cena blaze rodova jer je cena previse visoka i svako ko nije lagao za teritoriju kao ja naprimer nema para da kupi takodje i da se dodaju mob dropovi i stvari koje se ne mogu dobiti a potrebni su za napitke.

**Comment by PiweeX** [comment]
poruka stavljena na glasanje

čekamo

**Comment by PiweeX** [comment]
danas je dodata torta za prodaju i takođe blokovi meda
