### ISSUE TITLE
6 godina Hoga PROSLAVA

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#486]
Nadovezujem se na issue https://github.com/PiweeX/HogRealms/issues/125

ove godine 7. Jula obeležićemo 6 godina Hoga

već par dana spremamo program

![image](https://github.com/PiweeX/HogRealms/assets/33425430/08d692fd-b2fd-491d-b91f-6cd135cfdd70)
![image](https://github.com/PiweeX/HogRealms/assets/33425430/d7001be8-10f8-4c9c-abad-22f677223cb5)

hoću da kažem da nam nije u planu da pravimo nešto spektakularno od ovogodišnje proslave ali svakako će biti obeleženo

**Comment by PiweeX** [comment]
novosti, napravljen je i podešen dev server za platforme, to nam je drugi dev server na MNB networku.

ovo znači da je Drowned pri kraju završetka beta faze BedWars-a koji je u sklopu platformi


takođe, sređene su određene stvari koje su bile do mene na Iznad Lapute serveru koji će takođe biti otvoren zvanično 7.7. na 6 godina Hoga, djovani i djonmla su dali gas i rade ga jako, biće gotovo nadam se do kraja do 7.7.

isto tako trebam napomenuti da smo napokon spremni za veće UHC igre, već nekoliko game-ova ne postoje krešovi jer smo rešili taj problem na teži način, tako da da 7.7. će se održati UHC kup za 2023. gde ćemo dobiti pobednika za 2023. godinu

**Comment by PiweeX** [comment]
takođe ogromne promene na Borbe za Laputu, dakle ovim smo pokrili bukvalno sve podservere, uz to je i BTE tačnije podserver naših partnera sa Build The Earth Balkan koji su takođe na MNB lobiju došli do kraja reformi, počeli su i da spremaju bota

![image-118](https://github.com/PiweeX/HogRealms/assets/33425430/b110d153-31e9-4c22-8657-84387f9854e4)

**Comment by PiweeX** [comment]
bedwars spreman za 7.7. dobio sam info od drowneda

**Comment by PiweeX** [comment]
iznad lapute se radi intezivno u poslednje vreme, dosta toga je sređeno a danas su se pridružili Vuk i Gavran da pomažu, sve će biti spremno za 7 dana.

**Comment by PiweeX** [comment]
oformljeno je 6 tiktokova od igrača, igrači sami kreću u reklamiranje jer studio kasni

**Comment by PiweeX** [comment]
puno tehničkih problema na Borbe za Laputu rešeno ili se rešava u ovom momentu

**Comment by PiweeX** [comment]
radi se na popravljanju radio bota, uskoro na svakom hogovom discordu kao nekad!!!!

**Comment by PiweeX** [comment]
lobby još preuređen, sad ima i boje po nebu, dosta toga na lobby-u je sređeno obzirom da je to ključni server, totalno je spreman za 7.7. i za dalji rad

**Comment by PiweeX** [comment]
Pre Lapute (UHC) je takođe potpuno spreman

**Comment by PiweeX** [comment]
svim igracima jutros oko 12:00 stigla je notifikacija za 7.7.

**Comment by PiweeX** [comment]
Kao šlag na tortu Borbe za Laputu je u poslednjih nekoliko dana dobio ogromne tehničke promene, čet je popravljen, laputa kanal popravljen i još bezbroj stvari o kojima sam ispisao u testnet završetak issue-u i na samom discordu pre svega u zbor kanalu

borbe za laputu su dobile veće preuređenje i stvari koje se čekaju od 2021. poput nether shopa, tu je došao i end shop kao bonus ali i shop za močvare koji je samo izgrađen i najavljeno je kad će biti pušten, takođe uz to i shop za retke pećinske stvari ali i ispod shop za napitke za ratove koji će doći sutra tokom dana.

Tu je i novi natpis na laputi jer je velik deo lapute dobio stilska preuređenja, osvežili smo sve novitetima jer je bilo prazno oko recimo mesta gde se prodaju stvari, tu su sad ukrasi ali i nove stvari za prodaju poput meda

drva su takođe na laputi za prodaju po niskoj ceni u poslednje vreme, uz to i torta može da se prodaje i cvekla odma do pšenice s tim da je i pšenica vraćena a pšenica je zamenjena cveklom

![250391956-d24f5622-493d-4c79-ab66-8a57e15f56e5](https://github.com/PiweeX/HogRealms/assets/33425430/dcfd0391-3578-44c1-8ec8-9f2eb604e5bd)

**Comment by PiweeX** [comment]
Premijerno vest pre vremena, vesti koje će se objaviti u narednih 5 dana do 7.7. 6 godišnjice Hoga

![OBAVESTENIJA (2)](https://github.com/PiweeX/HogRealms/assets/33425430/c189b664-7612-46b4-8451-c19f40b3a75b)

**Comment by PiweeX** [comment]
Premijerno vest pre vremena, vesti koje će se objaviti u narednih 5 dana do 7.7. 6 godišnjice Hoga
(2)

![OBAVESTENIJA (3)](https://github.com/PiweeX/HogRealms/assets/33425430/4a23cf57-3d95-4197-8db1-ea407a25a1e9)

**Comment by PiweeX** [comment]
Premijerno vest pre vremena, vesti koje će se objaviti u narednih 5 dana do 7.7. 6 godišnjice Hoga
(3)

![OBAVESTENIJA (4)](https://github.com/PiweeX/HogRealms/assets/33425430/c60db1ac-3813-40bf-b622-1872b7d4363d)

**Comment by PiweeX** [comment]
Premijerno vest pre vremena, vesti koje će se objaviti u narednih 5 dana do 7.7. 6 godišnjice Hoga
(4)

![OBAVESTENIJA](https://github.com/PiweeX/HogRealms/assets/33425430/e6ece21e-69ec-4e7a-81d1-307b51803dd0)

**Comment by PiweeX** [comment]
Premijerno vest pre vremena, vesti koje će se objaviti u narednih 5 dana do 7.7. 6 godišnjice Hoga
(5)

![OBAVESTENIJA (1)](https://github.com/PiweeX/HogRealms/assets/33425430/04d8b7f7-db42-4da1-87ca-49ed0ac661de)

**Comment by PiweeX** [comment]
1 vest za Mađarsku je već objavljena malo pre. Inače posle dužeg vremena prva vest

**Comment by PiweeX** [comment]
poruka sa discorda

Pred 7.7. krenulo je održavanje povodom 6 godina Hoga

Server i ovaj discord čet su zaključani do 7.7. kada će biti održan UHC kup za 2023. godinu i kada će biti otvoreni Iznad Lapute serijal (SkyBlock podserver) i BedWars mini igra na Platformama

s vremena na vreme ću kačiti obaveštenja o updateovima na hogrealms Instagram koji je zvanični instagram od servera.

**Comment by PiweeX** [comment]
ovaj update mnogi čekaju od početka servera pre 6 godina, međutim moram reći da je ovo samo deo velike završne faze tehničkih radova na Hogu koji smo označili kao mainnet.

mainnet faza je faza koja se aktivno radi od 2017. godine a koja je najavljena 2021. godine kada je otvoren Decentraland podserver sa državama koji je tad bio prvi takav server a sad ih ima dosta. 

dosta energije je uloženo u ceo projekat, 454 zatvorena (rešena) issue-a tehničkih problema u poslednjih 11 meseci, s tim da u to ne ulaze updateovi platformi od Drowneda, i build škole od BTE partnera.

mainnet bi trebao da bude završen do 9.9. što je za samo 2 meseca. Da li će biti tog datuma ne mogu da obećam jer puno stvari ne zavisi od nas, prošli put kad smo trebali da pustimo mainnet radovi su nam odloženi na skoro godinu dana zbog DDOs napada od strane drugih servera što smo nakandno prijavili MUPu.

**Comment by PiweeX** [comment]
Hog je bio najigraniji server na Balkanu od 2021. do 2022. punih godinu dana dok nismo počeli da dobijamo napade sa više strana, od tad dakle u poslednjih 8 i više meseci server je postao zatvorenijeg tipa, reklame od tad nisu izlazile, uključena je whitelista i jednostavno server nije bio igriv. Mainnet je blizu, ovo je samo korak ka njemu, na skoro svakom podserveru odrađene su ogromne reforme

**Comment by PiweeX** [comment]
Radio bot 2018. je spreman


![fnI1-HdBTjeuVOgkdnDS_g](https://github.com/PiweeX/HogRealms/assets/33425430/6a500819-cab5-4a58-93d7-a242e08c6257)

**Comment by PiweeX** [comment]
Zatvaram ovaj issue, mnogo lep dan.

sve je prošlo po planu sem UHC-a, pošto je kup za 2023. odložen zbog pretnji angor kopije Hoga da će server biti ddosovan za rođendan jednostavno smo odložili i održali običan UHC

tako da je UHC jako slabo prošao, do sad sa najmanje ljudi nažalost jer su se ljudi nadali kupu, ali eto, zadovoljan sam kako je sve prošlo

slike i ostale stvari sam kačio na discord i na instagram, ovde ću neke random slike što izvučem

**Comment by PiweeX** [comment]
![2023-07-07_15 58 55](https://github.com/PiweeX/HogRealms/assets/33425430/10e4195b-a28a-4c95-b36c-27083f3ffc0b)
![2023-07-07_15 07 13](https://github.com/PiweeX/HogRealms/assets/33425430/3b0b805f-ed30-4f4e-bf54-e3139e122918)

**Comment by PiweeX** [comment]
![2023-07-07_15 22 14](https://github.com/PiweeX/HogRealms/assets/33425430/89bd1d1b-0797-4770-8a4f-5798f1302607)
![2023-07-07_15 22 09](https://github.com/PiweeX/HogRealms/assets/33425430/b3d166f3-fe33-4d50-bc64-e865a1808d87)
![2023-07-07_15 33 32](https://github.com/PiweeX/HogRealms/assets/33425430/ac144fc2-4089-458a-934d-0eaaa2043398)
![2023-07-07_15 41 12](https://github.com/PiweeX/HogRealms/assets/33425430/ac7f6945-e90e-49e3-be80-5e3efe11dff1)

**Comment by PiweeX** [comment]
![2023-07-07_16 29 06](https://github.com/PiweeX/HogRealms/assets/33425430/181cf6b1-d761-4df7-84c1-7183299533ef)
![2023-07-07_19 02 12](https://github.com/PiweeX/HogRealms/assets/33425430/33dec17f-e3fc-4e31-80d5-a2710e4e81d6)
![2023-07-07_16 16 58](https://github.com/PiweeX/HogRealms/assets/33425430/5a4acd93-0734-4672-bc54-8b95a2062874)

**Comment by PiweeX** [comment]
![2023-07-07_19 10 05](https://github.com/PiweeX/HogRealms/assets/33425430/968ce478-247a-46e2-b967-45e09e69ef13)
![2023-07-07_19 11 39](https://github.com/PiweeX/HogRealms/assets/33425430/67dd3485-a07c-4d77-83fd-ac077463f401)
![2023-07-07_19 10 05](https://github.com/PiweeX/HogRealms/assets/33425430/d8eedf5a-ad78-4432-93f5-5a001e703cbf)

**Comment by PiweeX** [comment]
![2023-07-07_19 42 29](https://github.com/PiweeX/HogRealms/assets/33425430/14db1372-dbad-4d2c-973b-24ae8b347960)
![2023-07-07_19 42 47](https://github.com/PiweeX/HogRealms/assets/33425430/2a3943cd-2ee8-4efb-b9e9-b8202e156030)
![2023-07-07_20 34 51](https://github.com/PiweeX/HogRealms/assets/33425430/3d714b01-e03d-4778-9b72-b569b78c6771)
![2023-07-07_20 37 27](https://github.com/PiweeX/HogRealms/assets/33425430/04aeb049-2e47-44ee-806a-23b03a5f994e)
![2023-07-07_20 39 33](https://github.com/PiweeX/HogRealms/assets/33425430/a8ee24e8-2acf-4d96-82e4-a8e08e2baae7)

**Comment by PiweeX** [comment]
Sva obaveštenja su na discordu, neću ih slati ovde.

bilo ih je više





Hvala vam!

**Comment by PiweeX** [comment]
zapravo evo

7.7.2023. 🎊🎊🎊

danas obeležavamo 6 godina postojanja i aktivnog rada Hoga.

Kao i svake godine skromno obeležimo taj dan, za ovu godinu smo spremili dosta toga što je priprema pred mainnet 9.9.


Danas u 7 puštamo u rad Borbe za Laputu podserver gde su puštene veće novosti koje neki čekaju 2 godine poput nether shopa i end shopa, u 15h kreće po prvi put BedWars na platformama a u 19h se otvara Iznad Lapute podserver serijal što je u prevodu SkyBlock

UHC kup za 2023. će se odložiti zbog pretnji o ddo s od strane vlasnika angor kopije Hoga.

Kup će biti održan u momentu kad nabavimo novu mašinu obzrom da su sa atlas kopije Hoga ponovo podelili IP mašine. Umesto kupa za 2023. danas odrđaće se redovni UHC TO4 meč. Vreme meča je sad 20:30 


želim da ovom porukom zahvalim svima na druženju koje traje godinama. Hog je stvoren pre mnogo godina kako bi okupio sve unikatne servere na Balkanu na 1 mesto, i eto dosta sam zadovoljan kako projekat napreduje, sve što sam zamislio skoro je ostvareno, ostalo je još da pustimo mainnet. O tome koliko je Hog da kažemo uspeo govori da je svaki treći server u regionu sada istog tipa kao naš glavni podserver. Posebna zahvalnost vlasnicima/kreatorima ostalih podservera na Hogu i DAO timu što su ostali na serveru u poslednjih godinu dana kad je serveru bilo najteže u svakom smislu. Vidimo se danas, i da igramo i dogodine! @everyone

**Comment by PiweeX** [comment]
BedWars mini igra je je zvanično otvorena pre oko pola sata na Platforme podserveru 🟢

čestitam ekipi sa platformi na dobro odrađenom podserveru, @bDrowned radi na celokupnim platformama ukupno 4 godine, to je zaista dug period za posvetiti bilo čemu.

Platforme će ostati sjajan podserver za nadmetanje, i za brze igre i opuštanje. BedWars će biti jedna od najboljih mini igara na platformama, usput Hog je danas postao prvi server na Balkanu sa BedWars mini igrom, baš kao što je bio slučaj sa earthom 2021. godine

@everyone

**Comment by PiweeX** [comment]
Iznad Lapute (SkyBlock) podserver je krenuo sa radom! 🟢

BETA verzija je počela, ovo je podserver koji @DjoVani i @djonmla svojom inicijativom rade duži niz meseci.

kao što je i najavljeno danas je otvoren, server još treba da se nadograđuje i nisu sve stvari stigle na otvaranju ali će biti do 9.9.

@everyone

**Comment by adamjackir** [comment]
Wow! 6 years of [HogaToga](https://hogatogapp.com/)—what an incredible journey! Big shoutout to the team for bringing us the best tech updates and apps. Here’s to many more years of innovation and success!
