### ISSUE TITLE
N1 preuređenje

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#488]
treba napraviti da umesto N1 piše N(DH)1 ili samo NDH1 istim fontom

![230x0w](https://github.com/PiweeX/HogRealms/assets/33425430/f407a1a6-c038-4396-aecb-81712c02a6b3)

**Comment by PiweeX** [comment]
napraviti u nekoliko veličina

da bude i u veličini bannera pored ove veličine logo-a

**Comment by mqtko** [comment]
Jos kad bi pogodio ovaj font

**Comment by PiweeX** [comment]
pripremamo

**Comment by PiweeX** [comment]
pronađen font, javićemo u ovaj issue kad bude gotovo

**Comment by mqtko** [comment]
50e po slovu. javi se dm

**Comment by PiweeX** [comment]
krenuli smo u izradu, biće gotovo uskoro

**Comment by NjegosodKrajine** [comment]
Dobro jutro svima otvaram ovaj github da objasnim px neke cinjenice koje ne govorim samo ja nego i drugi.Hog se suocava sa velikim problemima iz vise razloga dok se sami igraci slazu sa tim evo nekih problema:

1.Igraci vise ne igraju vec samo afk po odredjenom vremenu samo da bi prikupili rewards.

2.Drugi deo igraca nece da igra jer im je dosadilo nemaju sta da rade i vecina odlazi na druge servere.

3.Px obecava stvari neke ispunjava al neke i ne.Mi ne zelimo obrcanja nego djela i dokaze da ti to ispunjavas.

4.Veliki problem je Px poslusaj igrace sto ti igraju na serveru dugo vremena oni najbolje znaju sta je dobro a sta ne.

5.Evo u skorije vreme su igraci zamolili da uredis lands i naravno ti si uredio ali si ga samo jos vise upropastio to govori vecina.

6.Slabo se server promovise ali to je i logicno kad ima drugih obaveza.

7.Ne banaj svakog lika kad te pita nesto(ako vredja druge ili tebe opravdano je)mene si bano na 60 DANA jer sam te pitao kakva je situacija u ukrajini stvarno je to ne korektno.

8.Evo jedna sugestija da se doda vise dzelata jer imas postene ljude(nemoj da lazes da nemas) koji igraju sugo vremena a nikad nisu bili banani,jailani,mutovani itd..Evo mojih primera za dzelate:Viktor_23,JaSamIgor,Mladen19(ako vec nije dobio dzelata),FarisSpahic.Jer ne mogu 2 dzelata da sve rade a i dosadi jer nemaju vremena za igru vec samo resavanje problema i tiketa.

To su bili problemi koji su najveci i najpresudniji za dalji razvoj servera(upravo zbog ovih problema ljudi odlaze traze nova poznanstva i server kao sto sam i ja sam bio sudjen na to).

**Comment by PiweeX** [comment]
Gotovo 
![NDH1 a-2](https://github.com/PiweeX/HogRealms/assets/33425430/16718d51-4a8d-4048-a440-c397a986df47)

![NDH1](https://github.com/PiweeX/HogRealms/assets/33425430/3a7bcb05-5ec2-473d-a13b-0839547c81b4)

**Comment by PiweeX** [comment]
> Dobro jutro svima otvaram ovaj github da objasnim px neke cinjenice koje ne govorim samo ja nego i drugi.Hog se suocava sa velikim problemima iz vise razloga dok se sami igraci slazu sa tim evo nekih problema:
> 
> 1.Igraci vise ne igraju vec samo afk po odredjenom vremenu samo da bi prikupili rewards.
> 
> 2.Drugi deo igraca nece da igra jer im je dosadilo nemaju sta da rade i vecina odlazi na druge servere.
> 
> 3.Px obecava stvari neke ispunjava al neke i ne.Mi ne zelimo obrcanja nego djela i dokaze da ti to ispunjavas.
> 
> 4.Veliki problem je Px poslusaj igrace sto ti igraju na serveru dugo vremena oni najbolje znaju sta je dobro a sta ne.
> 
> 5.Evo u skorije vreme su igraci zamolili da uredis lands i naravno ti si uredio ali si ga samo jos vise upropastio to govori vecina.
> 
> 6.Slabo se server promovise ali to je i logicno kad ima drugih obaveza.
> 
> 7.Ne banaj svakog lika kad te pita nesto(ako vredja druge ili tebe opravdano je)mene si bano na 60 DANA jer sam te pitao kakva je situacija u ukrajini stvarno je to ne korektno.
> 
> 8.Evo jedna sugestija da se doda vise dzelata jer imas postene ljude(nemoj da lazes da nemas) koji igraju sugo vremena a nikad nisu bili banani,jailani,mutovani itd..Evo mojih primera za dzelate:Viktor_23,JaSamIgor,Mladen19(ako vec nije dobio dzelata),FarisSpahic.Jer ne mogu 2 dzelata da sve rade a i dosadi jer nemaju vremena za igru vec samo resavanje problema i tiketa.
> 
> To su bili problemi koji su najveci i najpresudniji za dalji razvoj servera(upravo zbog ovih problema ljudi odlaze traze nova poznanstva i server kao sto sam i ja sam bio sudjen na to).

što se tiče svega što si naveo svestan sam i radim na poboljšanju svega što želite, a to što kažeš dokazi pa zato i sve rešavam kroz issueove

što se tiče toga da si pitao pa sam te banovao, to je shvaćeno kao provokacija jer nije bilo iz dobre namere, nekoliko njih u poslednjih par dana je pitalo isto pitanje sa ciljem da isprovocira što ne tolerišemo ne samo za mene nego ne sme bilo koji igrač da se provocira ili vređa
