### ISSUE TITLE
Hog.

### ISSUE THREAD

**Issue by mqtko** [PiweeX/PiweeX#489]
Potruditi se malo oko hoga, malo poraditi na izgledu servera, fixati chat, reklamirati ga na tiktoku, youtube-u, dodati team za reklamiranje, dodati neke nove custom iteme, dodati kompletan novi shop gde treba dodati sve mob dropove rude i ostale stvarcice koje se ne mogu dobiti putem prezivljavanja,  i u kome ce se moci prodavati mnostvo stvari kao sto su rude, neke farm stvari kaktus, sugarcane itd, novi spawn jer je ovaj zastareo i dosadio, na kome ce biti putnik, map link, dodati takodje i crateove koji ce se dobivati votanjemi prilikom evenata. Neka server bude down 2 nedelje ako treba samo da se neke stvari poprave dok se to ne popravi hog nece videti nove igrace realno. Uraditi neke izmene oko staff teama dodati prijave jer je staff spor podosta i kad bi bilo vise igraca trenutni staff nebi stigao nikome da pomogne a i sad mu nesto ne uspeva da resavaju tikete i to. Napraviti mapu sveta da bude na webu a ne samo na aplikaciji radi lakse preglednosti a ne da skidaju igraci bluestacks, organizovati neke evente kao sto su pvp, build, svasta nesto pored UHC-A u kojima ce se dobijati jednokratni custom itemi, crate key ili nesto drugo.

**Comment by mqtko** [comment]
Takodje zaboravio sam reci da treba malo discord urediti nista ne izgleda uredno sve je pobacano i tako.

**Comment by JohnTheOtac** [comment]
Puno trazis. Lock

**Comment by mqtko** [comment]
bump @PiweeX

**Comment by PiweeX** [comment]
stavljeno na glasanje ovde


inače radimo na modernizaciji Hog Borbe za Laputu podservera tako da nek ostane issue

**Comment by PiweeX** [comment]
prihvaćeno i većina stvari je prebačena u nove issue-ove i radi se na njima ili su već urađeni.
