### ISSUE TITLE
Otvaram novi issue od čitave strane nexusa, da se ponovi bitka za carigrad i da se skloni krvavi mač.

### ISSUE THREAD

**Issue by protorner8** [PiweeX/PiweeX#492]
Krvavi mač je viđen op item u bitci za neopolis gdje je igrač daisydaisy__ imao sam 15 ubistva. Istina da je i nexus imao ali djovani nije htio dati boljim pvp-erima. A da se ponavlja rat je zbog krvavog i zbog Vuka koji je promenio strane u sredini rata. Piweeex je sam rekao da smijemo otvoriti issue da se skloni krvavi, ali su ga nerfovani. Igrač (daisydaisy__) je na 6/11/2023 imao normalan krvavi bez nerfa. Očekivali smo da će imati nerfovani ali jbg. Žale se igrači u vc-u da su im nestali itemi. Do svitanja.

**Comment by onepotato69** [comment]
Slažem se. Krvavi mač koji nije enchantan skida 4-5 srca bez critical hita, ima velki reach jedno 6-7 blokova i još je spam oružije. Takodje ima glitch kada ubiješ nekoga sa krvavim on se spawna na svoj chest i umre jos 10 do 15 puta i posle toga pukne originalni andjeoski chest sa svim stvarima. Molim nadležne organe da reaguju na ovo jer je dosta igrača izgubilo dosta dobrih itema.

**Comment by DaniloU08** [comment]
Slažem se da se oduzme krvavi jer i kada je nerfan itemi se dropaju šta znači da mač nije dobro odrađen jer pretpostavljam da nije napravljen da mu se itemi dropaju i da se napravi 10 chestova umesto jednog.
Ovo je drugi rat kako se krvavi koristi kao op mač, meni i ostalima lično je oduzet item koji je navodno jači a slabiji je, kao woden sword dila više od katane i ostalih dobrih itema.
Cela moja država glasa da se rat ponovi pogotovo što su neki menjali strane i ubijen sam

**Comment by Mladen0005** [comment]
Slazem se,krvavi je previse op cak i kad je do sad 5 puta nerfan,a i nije završen jer se desava da ili napravi vise andjeoskih cestova ili se desi da sve stvari padnu na pod.

**Comment by PiweeX** [comment]
nerfali smo krvavi mač jednom ali je nedovoljno očigledno, sad smo mu sklonili lifesteal tako da bi to bilo to

**Comment by PiweeX** [comment]
nerfali smo krvavi mač jednom ali je nedovoljno očigledno, sad smo mu sklonili lifesteal tako da bi to bilo to
