### ISSUE TITLE
katana pre slaba

### ISSUE THREAD

**Issue by bulke504** [PiweeX/PiweeX#498]
Katana je jedan od najtezih oruzij da se nabavi na serveru hogrealms. Zato sto je retka svi bi mislili da je dosta jaka, ali ne nije toliko jaka i skida samo 3 attack damege . Moj odgovor na ovo bi bilo da se att stavi na att normalnog diamantskog sworda a da 3 attt bude dodatak. Da li se slazete ili imate neki kompromis ?

**Comment by mqtko** [comment]
Ne lol katana je dovoljno jaka jer ima spam

**Comment by bulke504** [comment]
da ali spam se lako moze kaunterati

**Comment by bulke504** [comment]
sa shildom

**Comment by bulke504** [comment]
makar da joj stave att na 7 da bude ista ko obican mac . i ako se katana be busta zelim da krvavi jos bude nerfan

**Comment by mqtko** [comment]
Mnogo jako idalje. Sta ako neko nece da koriati shield Ionako katana ima spam i odbacuje lika da ga ne moze hit

**Comment by bulke504** [comment]
al vidi dzabe spam posto 99 % servera nosu shild i zna kako da kauntera katanu

**Comment by Viktor023023** [comment]
7 attack damage je prejako, predlazem da se stavi na 4 5 ili 5 5 kako je bilo i pre, ali 4 5 zvuci normalnije zato sto je 5 5 ipak jako a sada je katana zastupljeniji item

**Comment by mqtko** [comment]
pa katana i jeste 4 5

**Comment by mqtko** [comment]
samo sto postoji i 4 3 verzija

**Comment by Viktor023023** [comment]
uglavnom su 3 4, i neke 3 5, to sam ja video

**Comment by PiweeX** [comment]
Stavljeno na glasanije

**Comment by PiweeX** [comment]
katana ce dugorocno biti izbacena sa servera jer smo sinoc izbacili 95% itema iz default oraxena kao i pre 2 nedelje neke iteme jer uskoro dodajemo sve nase iteme
