### ISSUE TITLE
Npceve popraviti

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#500]

**Comment by PiweeX** [comment]
opet krenuo aktivno da radim na ovome

od sutra možda prorade, ili večeras

**Comment by PiweeX** [comment]
[22:55:29 ERROR]: [Citizens] v2.0.32-SNAPSHOT (build 3133) is not compatible with Minecraft v1_19_R2 - try upgrading Minecraft or Citizens. Disabling...

**Comment by PiweeX** [comment]
JOŠ UVEK IMA ERROR, NE ZNAM ZAŠTO. imamo najnoviji plugin uvek, updateamo i jar servera i sve ali ne radi ni kad izbacimo stari folder više puta. Na ostalim podserverima radi zaista ne znam

**Comment by mqtko** [comment]
godisnjica hoga za koji dan ti nemas pola servera lmao. chat shop npceve tunic vozila i sve ostalo

**Comment by vukstrale** [comment]
> godisnjica hoga za koji dan ti nemas pola servera lmao. chat shop npceve tunic vozila i sve ostalo

i u svemu tome najmanje mu trebaš ti da zvocaš

**Comment by PiweeX** [comment]
> godisnjica hoga za koji dan ti nemas pola servera lmao. chat shop npceve tunic vozila i sve ostalo

Važi matko stručnjače

**Comment by mqtko** [comment]
> > godisnjica hoga za koji dan ti nemas pola servera lmao. chat shop npceve tunic vozila i sve ostalo
> 
> Važi matko stručnjače

vidi barem da ti ne pukne uhc kup na godisnjici lmfao

**Comment by mqtko** [comment]
> > godisnjica hoga za koji dan ti nemas pola servera lmao. chat shop npceve tunic vozila i sve ostalo
> 
> i u svemu tome najmanje mu trebaš ti da zvocaš

ne cmari se majmune za unban

**Comment by vukstrale** [comment]
> > > godisnjica hoga za koji dan ti nemas pola servera lmao. chat shop npceve tunic vozila i sve ostalo
> > 
> > 
> > i u svemu tome najmanje mu trebaš ti da zvocaš
> 
> ne cmari se majmune za unban

već sam dobio unban kidu jedan neobavešteni

**Comment by mqtko** [comment]
> > > > godisnjica hoga za koji dan ti nemas pola servera lmao. chat shop npceve tunic vozila i sve ostalo
> > > 
> > > 
> > > i u svemu tome najmanje mu trebaš ti da zvocaš
> > 
> > 
> > ne cmari se majmune za unban
> 
> već sam dobio unban kidu jedan neobavešteni

Normalno da si dobio unban kad px deli unbanove jer mu server propada lmao

**Comment by vukstrale** [comment]
> > > > > godisnjica hoga za koji dan ti nemas pola servera lmao. chat shop npceve tunic vozila i sve ostalo
> > > > 
> > > > 
> > > > i u svemu tome najmanje mu trebaš ti da zvocaš
> > > 
> > > 
> > > ne cmari se majmune za unban
> > 
> > 
> > već sam dobio unban kidu jedan neobavešteni
> 
> Normalno da si dobio unban kad px deli unbanove jer mu server propada lmao

Da vidim tvoj server siso stara

**Comment by mqtko** [comment]
> > > > > > godisnjica hoga za koji dan ti nemas pola servera lmao. chat shop npceve tunic vozila i sve ostalo
> > > > > 
> > > > > 
> > > > > i u svemu tome najmanje mu trebaš ti da zvocaš
> > > > 
> > > > 
> > > > ne cmari se majmune za unban
> > > 
> > > 
> > > već sam dobio unban kidu jedan neobavešteni
> > 
> > 
> > Normalno da si dobio unban kad px deli unbanove jer mu server propada lmao
> 
> Da vidim tvoj server siso stara

 Ja barem ne otvaram servere ukoliko ne znam da ih vodim.

**Comment by PiweeX** [comment]
prebačeno u issue o statistici na laputi
