### ISSUE TITLE
Nove stvari za prodaju

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#516]
Dodata mogucnost za prodaju cake, a berrot takođe umesto pšenice stim da je cena sa 22$ povećana na 27$

takođe brewing stend za kupovinu pošto nema više na erwards, košta 500k u specijalnim ponudama kod enč table koja sad umesto 140k košta 500k takođe

i pošto nemamo neder na serveru niti ćemo ga IKAD imati jer je server tako zamišljen mislio sam da dodamo deo u lidlu gde će ići napitci, to će povećati masivnu nabavku pri svakom ratu, već sam napravio deo gde će ići ta prostorija, merdevine ka dole čim se uđe u lidl

**Comment by PiweeX** [comment]
takođe da napomenem da smo juče obrisali 95% custom itema iz default oraxena

spremamo 60 novih custom itema + dodatno 8 novih armora

**Comment by PiweeX** [comment]
takođe slime ball je povećan na 2800$



molim ekonomistu da poveća cene svih boja u shopu 

za sad su odradili super stvar, trident košta 400k a stalno se menja cena nekim itemima

**Comment by JaSamIgor** [comment]
brate zasto je berrot stavljen umjesto psenice, zar nije lakse samo da stavis oboje. nema smisla sklanjati psenicu kada vec ogromne farme postoje na serveru i kada je to pouzdan izvor prihoda

**Comment by PiweeX** [comment]
> brate zasto je berrot stavljen umjesto psenice, zar nije lakse samo da stavis oboje. nema smisla sklanjati psenicu kada vec ogromne farme postoje na serveru i kada je to pouzdan izvor prihoda

prihvatićemo predlog, biće vraćena pšenica po staroj ceni a ostaće berrot
