### ISSUE TITLE
Support rank

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#547]
Za mladena i svakog ko bude imao u buduće

Komande:

**Comment by NemanjaRusija** [comment]
> Za mladena i svakog ko bude imao u buduće
> 
> Komande:

Mute, ban, muteip, banip, mutechat, dupeip, staffhistory, jail.

**Comment by PiweeX** [comment]
na support rank podeseno kao sto pise


Mute, ban, muteip, banip, mutechat, dupeip, staffhistory, jail.

**Comment by PiweeX** [comment]
podesen je default takodje tako da sve ostale komande rade na support ranku

**Comment by PiweeX** [comment]
Mladenu podesen rank, sve je spremno. Gasim issue
