### ISSUE TITLE
NOVI DISCORD EMOJII!! (gotovo 99%)

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#550]

**Comment by PiweeX** [comment]
![wmaGPeV8RfKBrAyZoUBl5g](https://github.com/PiweeX/HogRealms/assets/33425430/0ba4fe45-3a83-4558-b66e-7bc8be917df1)

**Comment by PiweeX** [comment]
nešto što sam najavio pre ne znam koliko, možda 2 meseca u nekom predhodnom issue-u

napokon je sve ubačeno što treba


takođe neki emojii koji se ne uklapaju su izbačeni, dok su neki i ostali jer su vrlo slični tj ne ispadaju toliko iz tematike, verovatno će ostati i u buduće.

što se tiče gifova oni će takođe biti preuređeni, možda obrisani i skroz a možda ostane samo par, recimo bananu ćemo izbaciti

**Comment by mqtko** [comment]
alo decko ostavi credits ljudima sta krades samo

**Comment by PiweeX** [comment]
> alo decko ostavi credits ljudima sta krades samo

Svi emojii koji su ubačeni su plaćeni, upravo zbog toga. Pozdrav

**Comment by PiweeX** [comment]
GOTOVO!
