### ISSUE TITLE
Vratiti Hihihiha emoji na discord

### ISSUE THREAD

**Issue by vukstrale** [PiweeX/PiweeX#552]
Hihihiha emoji je srce i duša servera, izbacivanje Hihihiha emojia je svetogrdje i verujem da smo svi razočarani. Molim sve fanove Hihihiha emojia da glasaju za njegov povratak kao najjači emoji ikad.

**Comment by M1h4il0** [comment]
Ocemo nazad Hihihiha!!

**Comment by NjegosodKrajine** [comment]
Slazem se sa Vukom hihihiha on top!

**Comment by Viktor023023** [comment]
Vratiti momentalno!

**Comment by PiweeX** [comment]
HIHIHHAHAHA

**Comment by mqtko** [comment]
ne gubite se kidare
