### ISSUE TITLE
Nether stvari u shopu, end stvari u shopu, napitci u shopu (gotovo 100%)

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#557]

**Comment by PiweeX** [comment]
Nova stvar, /warp blackshop

stvari iz nethera koje mnogi čekaju od 2021.

stvari iz enda dodatno i stvari iz močvare kao i stvari iz pećina, samo što je za sad samo nether i end otključan

![2023-07-02_19 12 10](https://github.com/PiweeX/HogRealms/assets/33425430/7a67533e-f125-48c3-8836-15fd71332822)

**Comment by PiweeX** [comment]
moze med da se prodaje sad

dodat je kod slike kralja gde je vracena psenica posto je uklonjena zbog cvekle, dakle sad tu ima 3 stvari za prodaju

**Comment by PiweeX** [comment]
![2023-07-02_19 32 44](https://github.com/PiweeX/HogRealms/assets/33425430/4058e18a-0e8b-4cbc-972f-ce68876b73c6)

**Comment by PiweeX** [comment]
Novo uredjenje kod kralja, prvo uredjenje ikada u tom delu lapute

![2023-07-02_19 33 25](https://github.com/PiweeX/HogRealms/assets/33425430/f4a4d780-17b0-44d3-b23f-d65a43757816)

**Comment by PiweeX** [comment]
NOVO kod prodaje torti, totalno novo preuredjenje od onog ranije.

![2023-07-02_19 42 26](https://github.com/PiweeX/HogRealms/assets/33425430/875431bd-de98-4c0e-95dd-97ae755992e8)
![2023-07-02_19 40 22](https://github.com/PiweeX/HogRealms/assets/33425430/18b0a80d-a8e5-4f1a-80e3-e7da31770a07)

**Comment by PiweeX** [comment]
ostalo je još za napitke, napravili smo prostoriju u tornju koji je bio odma do specijalne ponude koja stoji tu 2 godine i koja ima 3 itema

ti itemi su pomereni na drugu stranu jer se taj toranj pretvara u toranj za napitke za ratove. To je stvar koja će doći do kraja leta

**Comment by PiweeX** [comment]
drago mi je da smo ovoliko toga uspeli da uradimo za ovih par dana

veliko hvala conetu Mladenu i Viktoru na pomoći oko svega, preporodili smo laputu za ono što joj predstoji.

**Comment by PiweeX** [comment]
NOVI BANER ZA KOD TORTI.


![NajstarijiServer](https://github.com/PiweeX/HogRealms/assets/33425430/5f486988-40ed-4269-91d5-0ac78658f6f3)

**Comment by PiweeX** [comment]
Evo kako je to ispalo u igri, taman

![2023-07-02_20 37 48](https://github.com/PiweeX/HogRealms/assets/33425430/dde46fba-e52c-4157-b300-ddadbbe906f2)
![2023-07-02_20 38 03](https://github.com/PiweeX/HogRealms/assets/33425430/d24f5622-493d-4c79-ab66-8a57e15f56e5)

**Comment by PiweeX** [comment]
GOTOVO!

**Comment by DaniloU08** [comment]
Narode aj da se vrati playtime za dmd ili neth armor, ljudima je od ratova ispucalo a neki imaju i po 50-60 dana playtimea koj su skupljali da bi dobili armore, nije u redu prvenstveno prema novim igračima jer nemaju opciju za bolji armor od irona.
