### ISSUE TITLE
Zakoni DC:

### ISSUE THREAD

**Issue by NemanjaRusija** [PiweeX/PiweeX#558]
Dodati zakone što je px napisao:

Dopuniti za slanje tuđih privatnih informacija u šta spadaju slike/snimci/mejlovi/brojevi i stvari iz ličnog života koje bi na bilo koji način ugrozile nekoga

Dopuniti i za krivične postupke

takođe webhook treba da se zove Hogline 

**DO VIKENDA URADITI**

**Comment by PiweeX** [comment]
Sutra preuređujem zakone

glavna stvar jeste da budu kraći i jednostavniji

**Comment by PiweeX** [comment]
80% preuređeno, zatvoriću issue
