### ISSUE TITLE
Discord radio bot za Hogovi (SMP discord)

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#559]
Update za bota je spreman, glavni problem prošlog bota bilo je stalno krešovanje, problemi na panelu i stalno je tražio update, jedva da nije ni radio, radio je do pola, moralo je non stop da se update-a ytdl i da se starta, pa se pokvari config pa briši sa panela pa dodaj opet pa isto ne radi

sad su ti problemi rešeni, u toku sam testiranja bota tako da bi uskoro trebao biti za stalno ubačen na HogRealms discord gde takav bot postoji od 2018. kada ga je Kinez prvi put napravio

drugi bot, tačnije isti samo sa drugom muzikom će biti ubačen na Hogovi discord od igrača SMP-a ili sad Unutar Lapute podservera

**Comment by PiweeX** [comment]
stavljen je bot iz 2018. na hogovi discord, ceka se update i resavamo i ostale botove

**Comment by NekrosBurek** [comment]
![HoorayLetsgoGIF](https://github.com/PiweeX/HogRealms/assets/30303273/bd102089-1bcc-40ef-9020-633473ff73b9)
