### ISSUE TITLE
Novi itemi za bolji rp (oraxen treba da ostane)

### ISSUE THREAD

**Issue by onepotato69** [PiweeX/PiweeX#563]
https://www.spigotmc.org/resources/combat-weaponry-plus-1-16-x.84248/

Ovo iznad je link plugina slobodno pogledajte.

Taj plugin je kao ono sto je bilo da se krafta samo sto imas emerald stvari isto da kraftas i mnogo vise oruzija sa lepsim i boljim teksutrama i pomoglo bi u rpu pogotovo ako se izbace emerald i dmd recepti odatle. Jos jedna dobra stvar je to sto imaš jedan shield i polako ga mozes upgradeati do emeralda ali moras  prvo wood pa stone pa iron pa dmd pa netherite pa emrald ali naravno to je samo shield nisu sva oruzija. Ako ovo ubaciš mi ćemo biti jedini geopolitički server koji koristi taj plugin.

**Comment by PiweeX** [comment]
Nažalost nije moguće jer je ovo 1.16 verzija

ipak poradićemo na dodavanju veoma sličnih itema u narednom periodu, bikvalno su isti
