### ISSUE TITLE
Predlog od coneta da se blokira bacanje na laputi

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#575]

**Comment by PiweeX** [comment]
uskoro

**Comment by Viktor023023** [comment]
sto to, ako hocu nekome da dam nesto dropamo na spawnu??

**Comment by PiweeX** [comment]
preko lapute

**Comment by aca6978** [comment]
piweeX dodaj da se sa rare diamondima moze praviti barem mac ili neki deo armmora
💯

**Comment by PiweeX** [comment]
Blokirano dropanje na laputi 

Takođe omogućeno da se uzima čest od stvari kad te neko ubije

**Comment by PiweeX** [comment]
> sto to, ako hocu nekome da dam nesto dropamo na spawnu??

Laputa komanda, ekonomija, ideš do nekog ploviš itd

**Comment by PiweeX** [comment]
> piweeX dodaj da se sa rare diamondima moze praviti barem mac ili neki deo armmora 💯

Rare diamondi su isključeni, tj nemaju svrhu niti će
