### ISSUE TITLE
automatski restart na pre lapute

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#593]

**Comment by misteruki** [comment]
trebalo bi na hog da se doda ono zbog cega ljudi igraju druge servere hvalitetan shop... Da se bolje i vise reklamira da se doda nesto novo nesto sto nijedan server nema sto je sad naprimer ova olimpijada koju radimo da se nerfa krvarenje da se vrati nerfana marikhuana ali marihuana da se nerfa samo ako ce krvarenje da se nerfa da se vozila poprave i  creitovi da  se dodaju i da kad kazete da ce nesto izaci dat da izadje tad da budete malo objektivniji jami je jedamput mjutan razlog kidara i da popravite rewards i da dodate da se nesto moze kraftati kako nastavimo vise se stik nece moci craftati vec ce se dobijati preko pleytimea

**Comment by PiweeX** [comment]
rešeno

**Comment by PiweeX** [comment]
> trebalo bi na hog da se doda ono zbog cega ljudi igraju druge servere hvalitetan shop... Da se bolje i vise reklamira da se doda nesto novo nesto sto nijedan server nema sto je sad naprimer ova olimpijada koju radimo da se nerfa krvarenje da se vrati nerfana marikhuana ali marihuana da se nerfa samo ako ce krvarenje da se nerfa da se vozila poprave i creitovi da se dodaju i da kad kazete da ce nesto izaci dat da izadje tad da budete malo objektivniji jami je jedamput mjutan razlog kidara i da popravite rewards i da dodate da se nesto moze kraftati kako nastavimo vise se stik nece moci craftati vec ce se dobijati preko pleytimea

u poseban issue
