### ISSUE TITLE
Nalepnica 2

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/PiweeX#596]
Nalepnica "Svaki rob koji kroči na srpsko tlo postaje slobodan čovek"

**Comment by PiweeX** [comment]
ideja za dizajn je da idu Ruska i ukrajinska zastava što će uz taj akt Sretenskog ustava simbolizovati trenutno stanje u ukrajini

**Comment by marepleb** [comment]
Kako ti se cini nesto ovako? 
![Сваки роб који крочи на српско тло](https://github.com/PiweeX/HogRealms/assets/107114906/9f20f1ba-f1df-4414-92dc-4d55a10b8d8c)

**Comment by PiweeX** [comment]
> Kako ti se cini nesto ovako? ![Сваки роб који крочи на српско тло](https://user-images.githubusercontent.com/107114906/262553923-9f20f1ba-f1df-4414-92dc-4d55a10b8d8c.png)

Smisliću nešto na taj fazon, samo što mora da bude format manji jer je za nalepnice za lepljenje po gradu. A i font treba biti kao da je nacrtano samo sam zaboravio kako se dodaje taj u ps

**Comment by marepleb** [comment]
> > Kako ti se cini nesto ovako? ![Сваки роб који крочи на српско тло](https://user-images.githubusercontent.com/107114906/262553923-9f20f1ba-f1df-4414-92dc-4d55a10b8d8c.png)
> 
> Smisliću nešto na taj fazon, samo što mora da bude format manji jer je za nalepnice za lepljenje po gradu. A i font treba biti kao da je nacrtano samo sam zaboravio kako se dodaje taj u ps

ma uradio sam ga preko canve za 5 minuta al da format je naplenica
